import type { TaskContent } from '@/core/task_content';

export const RESUME_TASKS: Record<string, TaskContent[]> = {
  'positioning-clarity': [
    {
      id: 'cy-pc-target-role',
      title: 'Define Your Target Cybersecurity Role',
      objective: 'Create a clear positioning statement for your cybersecurity job search.',
      instructions: [
        'Open 5 current cybersecurity job postings: SOC Analyst, Security Engineer, or Penetration Tester.',
        'Identify common requirements: SIEM tools, certifications, scripting languages.',
        'Write one sentence: "Cybersecurity professional specializing in [domain] using [tools]."',
        'Read it aloud. Remove every unnecessary word.',
      ],
      completionCriteria: [
        'Positioning statement is under 20 words',
        'At least 2 security tools mentioned',
        'Domain (blue team / red team / GRC) is explicit',
      ],
      estimatedMinutes: 20,
      difficulty: 1,
      tips: [
        'Avoid generic titles like "Cybersecurity Enthusiast".',
        'Mirror wording from actual job descriptions.',
        'Blue team vs red team vs GRC — pick one direction first.',
      ],
      expectedOutcome: 'A clear positioning statement that guides your resume and LinkedIn.',
    },
    {
      id: 'cy-pc-market-analysis',
      title: 'Analyze Cybersecurity Job Market',
      objective: 'Build a prioritized list of skills employers consistently request.',
      instructions: [
        'Collect 10 job descriptions for your target role.',
        'Highlight every tool, certification, framework, and soft skill.',
        'Count how often each requirement appears.',
        'Create a ranked list of the 10 most common requirements.',
      ],
      completionCriteria: [
        '10 job postings analyzed',
        '20+ requirements extracted',
        'Top 10 ranked by frequency',
      ],
      estimatedMinutes: 30,
      difficulty: 1,
      tips: [
        'Use postings from the last 3 months.',
        'Group similar tools: Splunk + ELK = SIEM category.',
        'Note clearance requirements separately.',
      ],
      expectedOutcome: 'A keyword list that guides resume customization and skill development.',
    },
    {
      id: 'cy-pc-resume-alignment',
      title: 'Evaluate Resume Alignment',
      objective: 'Measure how closely your resume matches your target cybersecurity role.',
      instructions: [
        'Read your resume from top to bottom.',
        'Mark every section that supports your target role.',
        'Highlight sections that are irrelevant or distracting.',
        'Write a short list of improvements needed.',
      ],
      completionCriteria: [
        'Every resume section reviewed',
        'At least 3 improvements documented',
        'Irrelevant content identified',
      ],
      estimatedMinutes: 25,
      difficulty: 1,
      tips: [
        'Pretend you are a security recruiter scanning in 6 seconds.',
        'Irrelevant experience (e.g., retail) should be minimal or removed.',
        'Certifications and tools should appear in the top third.',
      ],
      expectedOutcome: 'A prioritized action list for improving resume positioning.',
    },
    {
      id: 'cy-pc-validate',
      title: 'Validate Your Positioning',
      objective: 'Confirm that another person immediately understands your target role.',
      instructions: [
        'Share your positioning statement with two people.',
        'Ask them what cybersecurity role you are targeting.',
        'Record every misunderstanding.',
        'Refine based on consistent feedback.',
      ],
      completionCriteria: [
        'Feedback from 2 reviewers',
        'At least 1 improvement applied',
        'Both reviewers identify the correct role',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Use mentors, SOC analysts, or hiring managers if available.',
        'If feedback conflicts, prioritize clarity over creativity.',
      ],
      expectedOutcome: 'A validated positioning statement ready for your resume.',
    },
  ],
  'cyber-skills-matrix': [
    {
      id: 'cy-sm-inventory',
      title: 'Build Security Skills Inventory',
      objective: 'Create a comprehensive list of all security tools and technologies you can use.',
      instructions: [
        'List every security tool, framework, and platform you have used.',
        'Categorize: Network Analysis, SIEM, Vulnerability Scanning, Forensics, Scripting.',
        'Rate your proficiency: Beginner, Intermediate, Advanced.',
        'Verify each skill with a project or lab experience.',
      ],
      completionCriteria: [
        'At least 15 skills listed across 4+ categories',
        'Each skill has a proficiency rating',
        'Every skill is backed by experience or lab work',
      ],
      estimatedMinutes: 30,
      difficulty: 1,
      tips: [
        'Include both Blue Team and Red Team tools.',
        'Certifications count as validated skills.',
        'Be honest — inflated lists destroy credibility.',
      ],
      expectedOutcome: 'A structured skills inventory ready for your resume.',
    },
    {
      id: 'cy-sm-gap-analysis',
      title: 'Match Skills to Job Postings',
      objective: 'Identify gaps between your skills and what employers want.',
      instructions: [
        'Open 5 target job postings.',
        'Highlight every tool and technology mentioned.',
        'Compare against your inventory.',
        'Identify the top 3 missing skills.',
      ],
      completionCriteria: [
        '5 job postings analyzed',
        'Gap analysis completed',
        'Top 3 missing skills identified',
      ],
      estimatedMinutes: 25,
      difficulty: 1,
      tips: [
        'Focus on tools that appear in 3+ postings.',
        'Some gaps can be filled with home lab projects.',
        'Certifications bridge skill gaps quickly.',
      ],
      expectedOutcome: 'A skills section optimized for ATS and recruiter screening.',
    },
    {
      id: 'cy-sm-evidence',
      title: 'Document Proficiency Evidence',
      objective: 'Prepare proof for every skill you claim on your resume.',
      instructions: [
        'For each skill, write one sentence describing how you used it.',
        'Link to projects, labs, CTFs, or certifications where possible.',
        'Remove skills you cannot explain or demonstrate.',
        'Practice explaining your top 5 skills in 30 seconds each.',
      ],
      completionCriteria: [
        'Every skill has supporting evidence',
        'Top 5 skills have elevator-pitch explanations',
        'No unsupported claims remain',
      ],
      estimatedMinutes: 35,
      difficulty: 2,
      tips: [
        'Home lab work is valid evidence.',
        'CTF competitions demonstrate practical skills.',
        'Certifications provide third-party validation.',
      ],
      expectedOutcome: 'A defensible skills section with ready explanations.',
    },
  ],
  'resume-structure': [
    {
      id: 'cy-rs-audit',
      title: 'Audit Resume Structure',
      objective: 'Identify structural issues in your current resume.',
      instructions: [
        'Copy your resume into a plain text editor.',
        'Check if sections are clearly separated.',
        'Verify consistent formatting throughout.',
        'List all structural problems found.',
      ],
      completionCriteria: [
        'Plain text version is readable',
        'Formatting inconsistencies documented',
        'Section order is logical',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'If plain text looks broken, ATS will struggle too.',
        'Standard sections: Header, Summary, Experience, Skills, Certifications, Education.',
      ],
      expectedOutcome: 'A list of structural improvements needed.',
    },
    {
      id: 'cy-rs-rebuild',
      title: 'Rebuild with Security Focus',
      objective: 'Restructure your resume to highlight security experience.',
      instructions: [
        'Use a single-column, ATS-friendly layout.',
        'Add clear section headers including Certifications.',
        'Ensure consistent spacing and bullet style.',
        'Keep total length to 1-2 pages.',
      ],
      completionCriteria: [
        'Single-column layout used',
        'Certifications section is prominent',
        'Consistent formatting throughout',
      ],
      estimatedMinutes: 25,
      difficulty: 1,
      tips: [
        'Security resumes: 1 page for junior, 2 pages for experienced.',
        'Place Certifications near the top for security roles.',
        'Government ATS is stricter than corporate ATS.',
      ],
      expectedOutcome: 'A clean, ATS-friendly resume structure.',
    },
  ],
  'home-lab-showcase': [
    {
      id: 'cy-hl-architecture',
      title: 'Document Lab Architecture',
      objective: 'Create a clear description of your home lab environment.',
      instructions: [
        'List all VMs, containers, and tools in your lab.',
        'Describe the network topology.',
        'Create a diagram using draw.io or similar.',
        'Note which technologies you configured from scratch.',
      ],
      completionCriteria: [
        'Lab components are listed',
        'Network topology diagram is created',
        'Configuration effort is noted for each component',
      ],
      estimatedMinutes: 30,
      difficulty: 2,
      tips: [
        'Include: SIEM (Splunk/ELK), firewall (pfSense), vulnerable machines (VulnHub).',
        'Both attack and defense components should be visible.',
      ],
      expectedOutcome: 'A lab architecture document ready for your portfolio.',
    },
    {
      id: 'cy-hl-writeups',
      title: 'Write Lab Scenario Write-ups',
      objective: 'Document 3 attack/defense scenarios from your lab.',
      instructions: [
        'Choose 3 attack scenarios you simulated.',
        'Document the attack path, detection, and response for each.',
        'Include screenshots of logs, alerts, and analysis.',
        'Write a brief lesson learned for each.',
      ],
      completionCriteria: [
        '3 scenarios documented',
        'Each has attack path, detection, and response',
        'Screenshots included',
      ],
      estimatedMinutes: 45,
      difficulty: 3,
      tips: [
        'Common scenarios: phishing simulation, lateral movement, data exfiltration.',
        'Show both successful and failed detections.',
        'Include MITRE ATT&CK technique IDs.',
      ],
      expectedOutcome: 'Portfolio-ready write-ups demonstrating practical skills.',
    },
  ],
  'incident-response-stories': [
    {
      id: 'cy-ir-storybank',
      title: 'Build IR Story Bank',
      objective: 'Create 3 incident response stories using STAR format.',
      instructions: [
        'Identify 3 incidents from work, labs, or CTFs.',
        'Write each using: Situation, Task, Action, Result.',
        'Highlight technical decisions and tools used.',
        'Keep each story under 2 minutes when spoken.',
      ],
      completionCriteria: [
        '3 stories documented in STAR format',
        'Each highlights different security skills',
        'Stories are under 2 minutes each',
      ],
      estimatedMinutes: 35,
      difficulty: 2,
      tips: [
        'Include at least one story with a negative outcome you learned from.',
        'Mention specific tools: Splunk, Wireshark, SIEM.',
        'Quantify impact: time saved, breaches prevented.',
      ],
      expectedOutcome: 'A story bank ready for interviews and resume bullets.',
    },
    {
      id: 'cy-ir-practice',
      title: 'Practice Verbal Delivery',
      objective: 'Refine your IR stories for interview delivery.',
      instructions: [
        'Record yourself telling each story.',
        'Time each delivery.',
        'Identify filler words and pauses.',
        'Refine until each story flows naturally.',
      ],
      completionCriteria: [
        'Stories are recorded and reviewed',
        'Each story is under 2 minutes',
        'Filler words are minimized',
      ],
      estimatedMinutes: 25,
      difficulty: 2,
      tips: [
        'Practice with a friend if possible.',
        'Focus on clarity, not speed.',
        'Use action verbs: detected, contained, eradicated, recovered.',
      ],
      expectedOutcome: 'Polished IR stories ready for any interview.',
    },
  ],
  'resume-ats': [
    {
      id: 'cy-ats-keywords',
      title: 'Extract Security Keywords',
      objective: 'Build a cybersecurity-specific keyword list from job postings.',
      instructions: [
        'Collect 10 job postings for your target role.',
        'Extract every tool, certification, and framework mentioned.',
        'Count frequency of each keyword.',
        'Create a prioritized keyword list.',
      ],
      completionCriteria: [
        '10 job postings analyzed',
        '20+ keywords extracted',
        'Keywords ranked by frequency',
      ],
      estimatedMinutes: 30,
      difficulty: 1,
      tips: [
        'Include: SIEM, IDS/IPS, NIST, MITRE ATT&CK, Python, Bash.',
        'Include certifications: Security+, CEH, OSCP, CISSP.',
        'Government roles often require specific clearance keywords.',
      ],
      expectedOutcome: 'A keyword list for ATS optimization.',
    },
    {
      id: 'cy-ats-integrate',
      title: 'Integrate Keywords Naturally',
      objective: 'Add keywords to your resume without keyword stuffing.',
      instructions: [
        'Add top keywords to your Summary section.',
        'Include keywords in Experience bullet points.',
        'List keywords in the Skills section.',
        'Ensure keywords appear in context, not as lists.',
      ],
      completionCriteria: [
        'Top 10 keywords appear in Summary',
        'Keywords used in Experience bullets',
        'No keyword stuffing detected',
      ],
      estimatedMinutes: 30,
      difficulty: 2,
      tips: [
        'Use exact phrases from job postings.',
        'Avoid hiding keywords in white text or tiny fonts.',
        'Government ATS is especially strict about formatting.',
      ],
      expectedOutcome: 'An ATS-optimized resume with natural keyword integration.',
    },
  ],
};
