import type { TaskContent } from '@/core/task_content';

export const APPLICATION_TASKS: Record<string, TaskContent[]> = {
  'application-tracking': [
    {
      id: 'at-create-tracker',
      title: 'Create Application Tracking System',
      objective: 'Set up a reliable system to manage your job applications.',
      instructions: [
        'Open a spreadsheet app or Trello/Notion.',
        'Create columns: Company, Role, Date Applied, Status, Next Step, Follow-Up Date, Notes.',
        'Add 5 companies you plan to apply to this week.',
        'Set up a color-coding system for statuses: Applied, Screening, Interview, Offer, Rejected.',
      ],
      completionCriteria: [
        'Tracking system created with all required columns',
        '5 target companies added',
        'Status color-coding defined and applied',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Include a column for application materials (resume version, cover letter).',
        'Set a recurring reminder to update your tracker every Monday.',
        'Track company research links in the notes column.',
      ],
      expectedOutcome: 'A fully functional tracking system to manage your job search pipeline.',
    },
    {
      id: 'at-review-pipeline',
      title: 'Review and Optimize Your Pipeline',
      objective: 'Analyze your application pipeline for bottlenecks and gaps.',
      instructions: [
        'Review all entries in your tracker from the past month.',
        'Calculate: applications sent, responses received, interviews scheduled.',
        'Identify where the bottleneck is (low volume, low response rate, interview conversion).',
        'Set 2 specific actions to address the biggest bottleneck.',
      ],
      completionCriteria: [
        'Monthly application metrics calculated',
        'Bottleneck identified with supporting data',
        '2 action items created to address bottleneck',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'A 5% response rate is normal for cold applications.',
        'Referrals typically have 10x higher response rates.',
        'If volume is high but responses are low, focus on tailoring.',
      ],
      expectedOutcome: 'Data-driven understanding of your pipeline health and targeted improvement actions.',
    },
    {
      id: 'at-priority-matrix',
      title: 'Create a Company Priority Matrix',
      objective: 'Rank target companies by fit and likelihood.',
      instructions: [
        'List all companies in your tracker.',
        'Score each on: Role Fit (1-5), Culture Fit (1-5), Likelihood (1-5), Priority (1-5).',
        'Calculate a total score for each company.',
        'Sort by priority and focus your energy on top-tier companies.',
      ],
      completionCriteria: [
        'All companies scored across 4 dimensions',
        'Priority ranking calculated and sorted',
        'Top 3 priority companies identified for focused effort',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Apply to high-priority companies first each week.',
        'Spend extra time tailoring applications for top-tier targets.',
        'Revisit your priority matrix monthly as your search evolves.',
      ],
      expectedOutcome: 'A ranked list of target companies to focus your application energy effectively.',
    },
  ],
  'cover-letter': [
    {
      id: 'cl-create-template',
      title: 'Create a Modular Cover Letter Template',
      objective: 'Build a reusable template that can be quickly customized per application.',
      instructions: [
        'Write a 3-paragraph template: intro + your fit + closing.',
        'Define placeholders in brackets: [Company], [Role], [Specific Initiative].',
        'Write the "why you" section as a fill-in-the-blank format.',
        'Save as a master template file in your documents folder.',
      ],
      completionCriteria: [
        '3-paragraph template completed',
        'Placeholders clearly marked with brackets',
        'Master template saved as reusable file',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Keep your template to 250-400 words max.',
        'Focus 80% of the letter on the employer, 20% on you.',
        'Research the company before customizing — generic letters are obvious.',
      ],
      expectedOutcome: 'A reusable cover letter template that enables quick, personalized applications.',
    },
    {
      id: 'cl-customize-one',
      title: 'Customize Letter for a Target Application',
      objective: 'Practice tailoring your cover letter to a specific job posting.',
      instructions: [
        'Select one active job posting you want to apply for.',
        'Research the company: recent news, products, mission, culture.',
        'Customize your template: reference specific company initiatives.',
        'Address the top 3 job requirements with your matching experience.',
      ],
      completionCriteria: [
        'Company-specific research completed',
        'Top 3 requirements addressed with personal experience',
        'Company name and role-specific details inserted throughout',
      ],
      estimatedMinutes: 15,
      difficulty: 3,
      tips: [
        'Read the company blog or recent press releases for talking points.',
        'Mention a specific product or feature you admire.',
        'Use the same keywords from the job description in your letter.',
      ],
      expectedOutcome: 'A tailored, company-specific cover letter ready for submission.',
    },
    {
      id: 'cl-get-feedback',
      title: 'Get Cover Letter Feedback',
      objective: 'Validate your letter effectiveness before sending.',
      instructions: [
        'Send your customized letter to a peer or mentor for review.',
        'Ask specifically: Is the opening compelling? Is the fit clear? Is it the right length?',
        'Incorporate feedback and revise.',
        'Read the final version aloud before submitting.',
      ],
      completionCriteria: [
        'Letter reviewed by at least 1 peer',
        'Specific feedback incorporated',
        'Final version read aloud and approved',
      ],
      estimatedMinutes: 5,
      difficulty: 2,
      tips: [
        'Ask reviewers to be brutally honest — kind feedback does not help you improve.',
        'Check for typos by reading backwards.',
        'Ensure the file name includes your name and the target company.',
      ],
      expectedOutcome: 'A polished, reviewed cover letter ready for submission.',
    },
  ],
  'follow-up-strategy': [
    {
      id: 'fs-create-templates',
      title: 'Create 3 Follow-Up Email Templates',
      objective: 'Prepare professional follow-up messages for each application stage.',
      instructions: [
        'Template 1: Post-application follow-up (1 week after submitting).',
        'Template 2: Post-interview thank you (within 24 hours of interview).',
        'Template 3: Check-in (2 weeks after last communication).',
        'Each template should have placeholders for personalization.',
      ],
      completionCriteria: [
        'Post-application template written',
        'Post-interview thank you template written',
        'Follow-up check-in template written',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Keep follow-ups to 3-4 sentences — respect their time.',
        'Always add value: mention something from the conversation, share a relevant article.',
        'Use a polite, professional tone without being pushy.',
      ],
      expectedOutcome: '3 ready-to-use follow-up templates for every stage of the application process.',
    },
    {
      id: 'fs-schedule-reminders',
      title: 'Schedule Follow-Up Reminders',
      objective: 'Set up a system to never miss a follow-up opportunity.',
      instructions: [
        'For each active application, set a 7-day follow-up reminder.',
        'Add a 24-hour post-interview thank-you reminder.',
        'Configure notifications on your phone or calendar app.',
        'Test the reminder system with a sample entry.',
      ],
      completionCriteria: [
        '7-day reminders set for active applications',
        '24-hour post-interview reminders configured',
        'Reminder system tested and confirmed working',
      ],
      estimatedMinutes: 5,
      difficulty: 1,
      tips: [
        'Use a calendar app with push notifications for reliability.',
        'Include the company name and role in the reminder title.',
        'Set reminders for 10 AM on weekdays for professional timing.',
      ],
      expectedOutcome: 'An automated reminder system ensuring timely follow-ups on every application.',
    },
    {
      id: 'fs-etiquette-review',
      title: 'Review Follow-Up Best Practices',
      objective: 'Learn proper timing and etiquette for professional follow-ups.',
      instructions: [
        'Research recommended follow-up timing for each application stage.',
        'Learn what to include and avoid in follow-up messages.',
        'Document 5 key etiquette rules for reference.',
        'Review your past follow-ups against these best practices.',
      ],
      completionCriteria: [
        'Timing guidelines researched and documented',
        '5 etiquette rules documented',
        'Past follow-ups reviewed against best practices',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Do not follow up more than once per week.',
        'Never sound frustrated or entitled in follow-ups.',
        'If rejected, a gracious reply leaves a positive lasting impression.',
      ],
      expectedOutcome: 'A reference guide for professional follow-up etiquette to guide all your communications.',
    },
  ],
  'application-volume': [
    {
      id: 'av-set-weekly-target',
      title: 'Set a Realistic Weekly Application Target',
      objective: 'Define a sustainable application volume that fits your schedule.',
      instructions: [
        'Calculate how many hours per week you can dedicate to applications.',
        'Estimate time per application: 30 min research + 15 min tailoring.',
        'Set a weekly target based on available time (minimum 3, ideal 5-10).',
        'Block dedicated time slots in your calendar for focused applications.',
      ],
      completionCriteria: [
        'Weekly hours calculated and allocated',
        'Application time budget estimated',
        'Weekly target set with calendar blocks',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Quality matters more than quantity — 5 tailored beats 20 generic.',
        'Batch similar tasks: research all companies Monday, write all letters Tuesday.',
        'Protect your application time like any important meeting.',
      ],
      expectedOutcome: 'A realistic weekly application plan with time budgeted in your calendar.',
    },
    {
      id: 'av-batch-session',
      title: 'Complete a Batch Application Session',
      objective: 'Practice focused, efficient application submission using batching.',
      instructions: [
        'Prepare materials beforehand: resume versions, cover letter template, portfolio links.',
        'Select 3 job postings to apply for in this session.',
        'Apply to all 3 in one sitting, customizing each as needed.',
        'Update your tracker immediately after each submission.',
      ],
      completionCriteria: [
        '3 applications submitted in one session',
        'Each application customized for the specific role',
        'Tracker updated with all submission details',
      ],
      estimatedMinutes: 30,
      difficulty: 3,
      tips: [
        'Set a timer for each application (20-30 min) to maintain pace.',
        'Prepare common answers (e.g., "Why this company?") ahead of time.',
        'Take a 5-minute break between applications to stay fresh.',
      ],
      expectedOutcome: '3 completed, tailored applications submitted and tracked in a focused session.',
    },
    {
      id: 'av-review-metrics',
      title: 'Review Application Metrics and Adjust',
      objective: 'Use data to optimize your application strategy.',
      instructions: [
        'After 20 applications, calculate your metrics: response rate, interview rate, offer rate.',
        'Compare against benchmarks: 5% response, 2% interview, 0.5% offer for cold applications.',
        'If below benchmarks, identify the weakest step in your process.',
        'Adjust your strategy: improve resume, target different roles, or increase volume.',
      ],
      completionCriteria: [
        '20-application metrics calculated',
        'Metrics compared against benchmarks',
        'Strategy adjustment documented',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Track which sources yield the best responses (LinkedIn, company site, referral).',
        'If response rate is low, focus on resume and targeting.',
        'If interview rate is low after screening, focus on interview prep.',
      ],
      expectedOutcome: 'Data-driven strategy adjustments to improve your application conversion rates.',
    },
  ],
  'company-research': [
    {
      id: 'cr-research-five',
      title: 'Research 5 Target Companies Deeply',
      objective: 'Build detailed intelligence on your priority companies.',
      instructions: [
        'Select 5 companies from your priority matrix.',
        'For each: research mission, products, funding, culture, recent news.',
        'Check their careers page for open roles and culture content.',
        'Set up job alerts for each company to get notified of new openings.',
      ],
      completionCriteria: [
        '5 companies researched with detailed notes',
        'Each company documented: size, stage, culture, recent news',
        'Job alerts configured for all 5 companies',
      ],
      estimatedMinutes: 25,
      difficulty: 2,
      tips: [
        'Follow company pages on LinkedIn for real-time updates.',
        'Glassdoor and Blind give insight into company culture.',
        'Set up Google Alerts for company names to stay informed.',
      ],
      expectedOutcome: 'Comprehensive intelligence on 5 target companies enabling informed applications and interviews.',
    },
    {
      id: 'cr-identify-connections',
      title: 'Find Mutual Connections at Target Companies',
      objective: 'Leverage your network for referrals and insights.',
      instructions: [
        'For each target company, search LinkedIn for "People also viewed" and mutual connections.',
        'Identify 1-2 people per company who could provide a referral or information.',
        'Note their names, roles, and how you are connected.',
        'Plan your outreach: personalized message referencing the mutual connection.',
      ],
      completionCriteria: [
        'Mutual connections identified at each target company',
        '1-2 potential referral contacts per company documented',
        'Outreach plan created for each contact',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'A warm referral increases your interview chance by 10x.',
        'Connect before you need the favor — build relationships early.',
        'Ask for advice, not a job — it is more comfortable for both sides.',
      ],
      expectedOutcome: 'A network map of connections at target companies with an outreach strategy.',
    },
  ],
  'application-tailoring': [
    {
      id: 'at-map-requirements',
      title: 'Map Job Requirements to Your Experience',
      objective: 'Systematically align your resume with job posting requirements.',
      instructions: [
        'Take one job posting and list the top 8 requirements.',
        'For each requirement, write your matching experience from your master resume.',
        'Highlight the 3 strongest matches and 1 gap to address.',
        'Reorder your resume bullet points to lead with strongest matches.',
      ],
      completionCriteria: [
        '8 job requirements mapped to personal experience',
        '3 strongest matches identified for emphasis',
        'Resume reordered to prioritize matching content',
      ],
      estimatedMinutes: 15,
      difficulty: 3,
      tips: [
        'Use exact phrasing from the job description in your resume where accurate.',
        'If you have a gap, note how your transferable skills apply.',
        'Tailoring can increase your match score by 30-40%.',
      ],
      expectedOutcome: 'A tailored resume that aligns closely with the target job description.',
    },
    {
      id: 'at-cover-letter-sync',
      title: 'Sync Cover Letter With Tailored Resume',
      objective: 'Ensure your cover letter and resume tell the same targeted story.',
      instructions: [
        'After tailoring your resume, update your cover letter to match the same points.',
        'Reference the same key achievements emphasized in your resume.',
        'Use consistent language between both documents.',
        'Verify both documents use the same version number in filenames.',
      ],
      completionCriteria: [
        'Cover letter and resume reference the same key achievements',
        'Consistent language used across both documents',
        'Both files saved with matching version labels',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Recruiters read both documents — they should complement, not repeat.',
        'The cover letter adds context that resume bullets cannot.',
        'Use the cover letter to explain transitions or gaps if needed.',
      ],
      expectedOutcome: 'A coordinated application package with aligned resume and cover letter.',
    },
  ],
  'portfolio-submission': [
    {
      id: 'ps-github-cleanup',
      title: 'Clean Up Your GitHub or Portfolio',
      objective: 'Ensure your public work showcases your best skills.',
      instructions: [
        'Review your GitHub profile as a recruiter would see it.',
        'Pin your top 3 repositories that best demonstrate your skills.',
        'Write or update README files for each pinned repo with clear descriptions.',
        'Remove or archive incomplete or low-quality repos from visibility.',
      ],
      completionCriteria: [
        'Top 3 repositories pinned',
        'Each pinned repo has a complete README',
        'Low-quality repos archived or made private',
      ],
      estimatedMinutes: 20,
      difficulty: 2,
      tips: [
        'A clean GitHub profile is often more convincing than a resume for technical roles.',
        'Include a link to your deployed projects if applicable.',
        'README should explain: what, why, how, and how to run it.',
      ],
      expectedOutcome: 'A polished, recruiter-friendly GitHub profile showcasing your best work.',
    },
    {
      id: 'ps-portfolio-website',
      title: 'Create or Update Portfolio Website',
      objective: 'Build a central hub for your professional work and brand.',
      instructions: [
        'If you have a portfolio, audit it for outdated content and broken links.',
        'If you do not have one, create a simple page with: about, projects, resume, contact.',
        'Add your 3 best projects with descriptions, tech stack, and links.',
        'Ensure the site loads quickly and is mobile-responsive.',
      ],
      completionCriteria: [
        'Portfolio website exists or is updated',
        '3 best projects featured with descriptions and links',
        'Site is mobile-responsive and loads in under 3 seconds',
      ],
      estimatedMinutes: 30,
      difficulty: 3,
      tips: [
        'A simple, clean portfolio beats a flashy, slow one.',
        'Include testimonials or results from your projects.',
        'Add Google Analytics to track who visits your portfolio.',
      ],
      expectedOutcome: 'A professional portfolio website that showcases your work and strengthens your application.',
    },
  ],
  'referral-strategy': [
    {
      id: 'rs-request-referral',
      title: 'Request Referrals From Network',
      objective: 'Get referred to target companies through your connections.',
      instructions: [
        'Identify 3 companies where you have a strong connection (alumni, former colleague).',
        'Write a personalized message requesting a referral.',
        'Include your resume, target role, and a brief explanation of why you are a good fit.',
        'Make it easy: offer to draft the referral note for them.',
      ],
      completionCriteria: [
        '3 referral requests sent to connections',
        'Each request includes resume and target role',
        'Referral materials prepared for easy forwarding',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Referrals have a 10-20x higher chance of landing an interview.',
        'Be respectful of their time and reputation — only ask if you are genuinely qualified.',
        'Follow up with a thank-you regardless of outcome.',
      ],
      expectedOutcome: '3 referral requests sent to connections at target companies.',
    },
    {
      id: 'rs-build-referral-network',
      title: 'Build a Referral Network',
      objective: 'Expand your referral potential through strategic networking.',
      instructions: [
        'Identify alumni groups, professional organizations, and Slack communities.',
        'Join 2 relevant professional communities this week.',
        'Introduce yourself and participate in discussions.',
        'Note members who work at your target companies for future referral requests.',
      ],
      completionCriteria: [
        '2 professional communities joined',
        'Introduction posted in each community',
        'Target company contacts identified in communities',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Alumni networks are the easiest source of warm referrals.',
        'Be a giver, not just a taker — help others before asking for help.',
        'Slack communities often have dedicated job channels.',
      ],
      expectedOutcome: 'An expanded professional network with referral potential at target companies.',
    },
  ],
};
