import type { TaskContent } from '@/core/task_content';

export const INTERVIEW_TASKS: Record<string, TaskContent[]> = {
  'interview-prep': [
    {
      id: 'ip-star-stories',
      title: 'Write 3 STAR Stories',
      objective: 'Prepare compelling behavioral stories covering different competencies.',
      instructions: [
        'Select 3 key competencies: leadership, problem-solving, collaboration.',
        'For each, write a story using STAR: Situation, Task, Action, Result.',
        'Ensure each story has a clear conflict and a quantified result.',
        'Compact each story to 90 seconds when spoken aloud.',
      ],
      completionCriteria: [
        '3 stories written in STAR format',
        'Each story covers a different competency',
        'Each story includes a specific metric or outcome',
      ],
      estimatedMinutes: 25,
      difficulty: 3,
      tips: [
        'Strongest stories have a clear "before and after" with metrics.',
        'If you lack a result, explain what you learned.',
        'Practice telling the story without notes — it should feel natural.',
      ],
      expectedOutcome: '3 well-structured STAR stories ready for behavioral interview questions.',
    },
    {
      id: 'ip-common-questions',
      title: 'Prepare Answers to 10 Common Questions',
      objective: 'Be ready for the most frequently asked interview questions.',
      instructions: [
        'Compile a list of 10 common questions for your role and level.',
        'Write 2-3 sentence answers for each, referencing your STAR stories.',
        'Identify which of your 3 stories maps to each question.',
        'Highlight keywords from the job description to weave into answers.',
      ],
      completionCriteria: [
        '10 common questions compiled',
        '2-3 sentence answer written for each',
        'STAR story mapping complete for all applicable questions',
      ],
      estimatedMinutes: 20,
      difficulty: 2,
      tips: [
        'Most behavioral questions map to one of 5-6 core competencies.',
        'Use the same story for multiple questions — different framing.',
        'Record yourself answering to check for clarity and conciseness.',
      ],
      expectedOutcome: 'A prepared set of answers to common interview questions with story references.',
    },
    {
      id: 'ip-company-prep',
      title: 'Research Company for Interview',
      objective: 'Know the company inside-out before your interview.',
      instructions: [
        'Review the company website, especially About, Blog, and Careers pages.',
        'Read their latest 3 blog posts or press releases.',
        'Check recent news: funding, acquisitions, product launches, leadership changes.',
        'Prepare 5 thoughtful questions to ask about the role, team, and company.',
      ],
      completionCriteria: [
        'Company website thoroughly reviewed',
        '3 recent news items identified',
        '5 questions prepared to ask the interviewer',
      ],
      estimatedMinutes: 20,
      difficulty: 2,
      tips: [
        'Good questions show you did your homework and are serious.',
        'Ask about challenges, growth opportunities, and team dynamics.',
        'Avoid questions answered on the company website.',
      ],
      expectedOutcome: 'Deep company knowledge and 5 thoughtful questions demonstrating genuine interest.',
    },
  ],
  'mock-interview': [
    {
      id: 'mi-schedule-session',
      title: 'Schedule a Mock Interview',
      objective: 'Book a practice interview with someone who can give honest feedback.',
      instructions: [
        'Find a peer, mentor, or use a mock interview platform.',
        'Agree on format: behavioral, technical, or mixed.',
        'Set a date and time, allowing 45-60 minutes.',
        'Share your resume and target role with your interviewer in advance.',
      ],
      completionCriteria: [
        'Mock interview date and time confirmed',
        'Interview format agreed upon',
        'Resume and target role shared with interviewer',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Ask a friend in a similar role to be the interviewer.',
        'Use professional mock interview services if available.',
        'Treat the mock interview as seriously as a real one.',
      ],
      expectedOutcome: 'A confirmed mock interview session with clear format and prepared materials.',
    },
    {
      id: 'mi-review-recording',
      title: 'Review Mock Interview Recording',
      objective: 'Analyze your performance to identify improvement areas.',
      instructions: [
        'Record the mock interview (with permission).',
        'Watch the recording and score yourself: clarity, confidence, structure, content.',
        'Note filler words ("um," "like"), long pauses, or rambling answers.',
        'Identify 3 specific areas to improve for the next session.',
      ],
      completionCriteria: [
        'Mock interview recorded and reviewed',
        'Self-scoring completed across 4 dimensions',
        '3 improvement areas identified and documented',
      ],
      estimatedMinutes: 30,
      difficulty: 2,
      tips: [
        'Watch on 1.5x speed first for an overall impression, then normal speed for details.',
        'Pay attention to body language and facial expressions.',
        'Check if your answers were concise or if you rambled.',
      ],
      expectedOutcome: 'A detailed self-assessment of your interview performance with targeted improvement areas.',
    },
    {
      id: 'mi-practice-weakness',
      title: 'Practice Weakest Question 3 Times',
      objective: 'Turn your weakest answer into a strength through repetition.',
      instructions: [
        'From the mock interview review, identify the question you answered worst.',
        'Write an improved version of your answer.',
        'Record yourself answering this question.',
        'Repeat until you are satisfied with the recording.',
      ],
      completionCriteria: [
        'Weakest question identified from mock review',
        'Improved answer written',
        '3 recordings made with visible improvement',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Repetition builds muscle memory for answers.',
        'Practice with a timer — most answers should be 60-90 seconds.',
        'Ask a friend for feedback after your third attempt.',
      ],
      expectedOutcome: 'A polished, confident answer to your previously weakest interview question.',
    },
  ],
  'technical-prep': [
    {
      id: 'tp-algorithm-practice',
      title: 'Solve 2 Medium Algorithm Problems',
      objective: 'Practice technical problem-solving under realistic conditions.',
      instructions: [
        'Choose 2 medium-difficulty problems from LeetCode or similar platform.',
        'Set a 30-minute timer for each problem.',
        'Write your solution, then test it with edge cases.',
        'Review the optimal solution and note what you could improve.',
      ],
      completionCriteria: [
        '2 problems solved within time limit',
        'Solutions tested with edge cases',
        'Optimal solution reviewed and differences noted',
      ],
      estimatedMinutes: 30,
      difficulty: 4,
      tips: [
        'Read the problem twice before coding.',
        'Explain your approach out loud as you code.',
        'If stuck after 15 minutes, look at the solution and learn from it.',
      ],
      expectedOutcome: '2 completed algorithm solutions with analysis of optimal approaches.',
    },
    {
      id: 'tp-walkthrough-record',
      title: 'Record Solution Walkthrough',
      objective: 'Practice explaining technical solutions clearly and confidently.',
      instructions: [
        'Select one problem you solved recently.',
        'Restate the problem in your own words.',
        'Explain your approach step by step, including trade-offs.',
        'Record a 5-minute walkthrough as if presenting to an interviewer.',
      ],
      completionCriteria: [
        '5-minute walkthrough recording made',
        'Problem restated clearly in own words',
        'Trade-offs and alternatives discussed',
      ],
      estimatedMinutes: 15,
      difficulty: 3,
      tips: [
        'Interviewers care about your thought process as much as the solution.',
        'Use examples or diagrams if helpful.',
        'State time and space complexity before the interviewer asks.',
      ],
      expectedOutcome: 'A recorded technical walkthrough demonstrating clear communication of complex solutions.',
    },
    {
      id: 'tp-common-patterns',
      title: 'Study Common Technical Patterns',
      objective: 'Build a mental library of solution patterns for quick reference.',
      instructions: [
        'Review 5 common patterns: two pointers, sliding window, BFS/DFS, dynamic programming, binary search.',
        'For each pattern, write when to use it and a template solution.',
        'Solve 1 problem per pattern to reinforce understanding.',
        'Create a cheat sheet for quick review before interviews.',
      ],
      completionCriteria: [
        '5 patterns studied with use cases documented',
        '1 problem solved per pattern',
        'Cheat sheet created for review',
      ],
      estimatedMinutes: 30,
      difficulty: 4,
      tips: [
        'Most technical interview problems use one of 10-15 patterns.',
        'Focus on recognizing the pattern rather than memorizing solutions.',
        'Practice identifying patterns in new problems quickly.',
      ],
      expectedOutcome: 'A framework for recognizing and applying common algorithm patterns in interviews.',
    },
  ],
  'interview-mindset': [
    {
      id: 'im-confidence-list',
      title: 'Write a Confidence Evidence List',
      objective: 'Build genuine confidence by reviewing your real accomplishments.',
      instructions: [
        'List 10 specific accomplishments from your career that you are proud of.',
        'For each, write 1-2 sentences describing the challenge and your impact.',
        'Read this list before each interview to ground yourself in evidence.',
        'Add new accomplishments as you progress in your job search.',
      ],
      completionCriteria: [
        '10 accomplishments documented with impact',
        'List saved and accessible before interviews',
        'Review habit established for pre-interview ritual',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'This is not for your resume — it is for your mindset.',
        'Include accomplishments from work, volunteering, side projects.',
        'Evidence-based confidence is more durable than positive thinking alone.',
      ],
      expectedOutcome: 'A personal confidence document that reminds you of your proven capabilities.',
    },
    {
      id: 'im-preparation-routine',
      title: 'Build a Pre-Interview Preparation Routine',
      objective: 'Create a repeatable ritual that puts you in the right mindset.',
      instructions: [
        'Design a 15-minute pre-interview routine: 5 min breathing, 5 min review, 5 min visualization.',
        'Write down your breathing exercises or meditation script.',
        'Prepare your review checklist: company notes, your questions, STAR stories.',
        'Practice the routine before your next mock interview.',
      ],
      completionCriteria: [
        '15-minute pre-interview routine designed',
        'Breathing exercises documented',
        'Review checklist prepared',
        'Routine tested in mock setting',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Deep breathing reduces cortisol and improves focus.',
        'Visualization of success activates the same neural pathways as actual performance.',
        'Consistency is key — same routine every time creates a conditioned response.',
      ],
      expectedOutcome: 'A tested pre-interview routine that reduces anxiety and improves performance.',
    },
    {
      id: 'im-positive-reframe',
      title: 'Practice Reframing Anxiety as Excitement',
      objective: 'Transform interview nerves into productive energy.',
      instructions: [
        'Identify the physical signs of your interview anxiety (racing heart, shallow breath).',
        'Research the "anxiety reappraisal" technique — anxiety and excitement are physiologically similar.',
        'When you feel nervous, say: "I am excited. My body is preparing me to perform."',
        'Practice this reframing during your mock interview.',
      ],
      completionCriteria: [
        'Physical anxiety signs identified',
        'Anxiety reappraisal technique understood',
        'Reframing practiced in mock interview setting',
      ],
      estimatedMinutes: 5,
      difficulty: 2,
      tips: [
        'Studies show reframing anxiety as excitement improves performance.',
        'Your body does not know the difference — label the feeling as energy.',
        'Combine with deep breathing for best results.',
      ],
      expectedOutcome: 'A psychological technique to channel interview nerves into positive performance energy.',
    },
  ],
  'behavioral-prep': [
    {
      id: 'bp-competency-stories',
      title: 'Map Stories to Core Competencies',
      objective: 'Cover all likely behavioral interview topics with prepared stories.',
      instructions: [
        'Identify 10 core competencies interviewers evaluate: leadership, teamwork, conflict, failure, initiative, adaptability, communication, problem-solving, ownership, growth.',
        'Map your STAR stories and experiences to each competency.',
        'Identify which competencies lack a strong story and create one.',
        'Keep a reference table of competency → story for quick recall.',
      ],
      completionCriteria: [
        '10 competencies identified and documented',
        'At least 1 story mapped per competency',
        'Gaps filled for uncovered competencies',
      ],
      estimatedMinutes: 20,
      difficulty: 2,
      tips: [
        'One strong story can cover multiple competencies with different framing.',
        'Competencies like "failure" and "conflict" are often the most revealing.',
        'Use the job description to prioritize which competencies to emphasize.',
      ],
      expectedOutcome: 'A comprehensive story bank covering all likely behavioral interview topics.',
    },
    {
      id: 'bp-before-after',
      title: 'Prepare "Before and After" Examples',
      objective: 'Showcase your ability to create positive change.',
      instructions: [
        'Select 2 situations where you improved a process, team, or product.',
        'Document the "before" state: metrics, pain points, challenges.',
        'Document the "after" state: improvements, metrics, impact.',
        'Quantify the delta: "Reduced X by Y%," "Increased Z by W."',
      ],
      completionCriteria: [
        '2 before-and-after scenarios documented',
        'Each has quantified metrics for both states',
        'Your specific contribution clearly articulated',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Recruiters love concrete examples of positive impact.',
        'The clearer the "before" problem, the more impressive the "after."',
        'Use data: percentages, dollars, time saved, users impacted.',
      ],
      expectedOutcome: '2 compelling change-impact stories with clear before-and-after metrics.',
    },
    {
      id: 'bp-challenge-question',
      title: 'Prepare "Biggest Challenge" Answer',
      objective: 'Have a standout answer for one of the most common interview questions.',
      instructions: [
        'Select a significant professional challenge you overcame.',
        'Structure your answer: what made it challenging, your approach, the outcome.',
        'Focus on your specific actions and decision-making process.',
        'End with what you learned and how it shaped you professionally.',
      ],
      completionCriteria: [
        'Challenge story selected and structured',
        'Personal actions and decisions clearly articulated',
        'Learning and growth outcomes included',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Avoid sounding like you blame others for the challenge.',
        'The best challenges show growth, not just difficulty.',
        'If the outcome was not perfect, focus on what was learned.',
      ],
      expectedOutcome: 'A polished answer to "Tell me about a challenge you faced" that demonstrates resilience.',
    },
  ],
  'system-design-prep': [
    {
      id: 'sd-design-session',
      title: 'Complete a System Design Session',
      objective: 'Practice architecting a scalable system under interview conditions.',
      instructions: [
        'Select a common system design problem (e.g., design a URL shortener, chat system).',
        'Set a 45-minute timer for the complete design session.',
        'Cover: requirements, estimation, data model, API, high-level design, deep dive.',
        'Document your design with diagrams and trade-off notes.',
      ],
      completionCriteria: [
        'System design completed with all sections',
        'Requirements and constraints documented',
        'Trade-offs and alternatives discussed',
      ],
      estimatedMinutes: 45,
      difficulty: 5,
      tips: [
        'Start by clarifying requirements — do not assume anything.',
        'Estimate scale before designing — it drives your choices.',
        'Identify the most interesting part and deep dive there.',
      ],
      expectedOutcome: 'A complete system design artifact demonstrating architectural thinking.',
    },
    {
      id: 'sd-practice-frameworks',
      title: 'Practice Using Design Frameworks',
      objective: 'Apply structured frameworks to system design problems.',
      instructions: [
        'Learn 3 design frameworks: C4 model, SOLID principles, CAP theorem.',
        'Practice explaining when and why to use each framework.',
        'Apply each framework to a different design problem.',
        'Record yourself explaining your framework choice for one problem.',
      ],
      completionCriteria: [
        '3 design frameworks studied and understood',
        'Each framework applied to a practice problem',
        'Framework choice rationale recorded and reviewed',
      ],
      estimatedMinutes: 30,
      difficulty: 4,
      tips: [
        'Design frameworks show structured, experienced thinking.',
        'Choosing the right tool for the problem is as important as the solution.',
        'Interviewers appreciate when you explicitly state your design philosophy.',
      ],
      expectedOutcome: 'Fluency in applying design frameworks to communicate architectural decisions.',
    },
    {
      id: 'sd-tradeoff-analysis',
      title: 'Practice Trade-off Analysis',
      objective: 'Develop the ability to evaluate design decisions critically.',
      instructions: [
        'Select one design problem and create 2 alternative solutions.',
        'For each alternative, list pros and cons across: performance, cost, complexity, scalability.',
        'Write a recommendation explaining which alternative is better and why.',
        'Practice verbalizing this analysis as if in an interview.',
      ],
      completionCriteria: [
        '2 alternative solutions designed',
        'Pros and cons documented for each alternative',
        'Recommendation written with clear rationale',
      ],
      estimatedMinutes: 20,
      difficulty: 4,
      tips: [
        'There is no perfect design — trade-offs are expected and valued.',
        'Show that you considered multiple dimensions before deciding.',
        'Good trade-off analysis often impresses more than the design itself.',
      ],
      expectedOutcome: 'A demonstrated ability to evaluate design options and make informed trade-off decisions.',
    },
  ],
  'on-site-prep': [
    {
      id: 'os-logistics-plan',
      title: 'Plan On-Site Interview Logistics',
      objective: 'Eliminate logistical stress so you can focus on performing.',
      instructions: [
        'Confirm interview schedule: times, locations, interviewer names and titles.',
        'Plan your route: travel time, parking or public transit, backup options.',
        'Pack your bag: laptop, charger, portfolio, water, snacks, notepad, pens.',
        'Prepare your outfit: professional attire appropriate for the company culture.',
      ],
      completionCriteria: [
        'Schedule confirmed with all details',
        'Travel plan with backup options ready',
        'Bag packed with all essentials',
        'Outfit selected and prepared',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Arrive 15 minutes early — not 30 seconds, not 30 minutes.',
        'Bring physical copies of your resume (3-5 copies).',
        'Research the lunch situation — some companies provide it, some do not.',
      ],
      expectedOutcome: 'Complete logistical preparation ensuring a stress-free interview day.',
    },
    {
      id: 'os-energy-management',
      title: 'Plan Energy Management for Full Day',
      objective: 'Maintain peak mental performance across multiple interview rounds.',
      instructions: [
        'Plan your meals: eat a protein-rich breakfast, pack healthy snacks.',
        'Schedule mental breaks between interviews: bathroom, water, deep breathing.',
        'Identify your energy dip time and plan a strategy (coffee, walk, stretch).',
        'Prepare a "reset" routine for between rounds: 2-minute breathing, review notes.',
      ],
      completionCriteria: [
        'Meal and snack plan prepared',
        'Mental break strategy defined',
        'Between-round reset routine practiced',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Your energy is a resource — manage it as carefully as your answers.',
        'Avoid heavy lunches that cause afternoon energy dips.',
        'Use the bathroom or water break between rounds to reset.',
      ],
      expectedOutcome: 'An energy management plan to sustain peak performance throughout a full interview day.',
    },
    {
      id: 'os-follow-up-plan',
      title: 'Prepare Post-On-Site Follow-Up Plan',
      objective: 'Have a plan for timely, effective follow-up after the interview day.',
      instructions: [
        'Write thank-you notes for each interviewer (customize for each person).',
        'Schedule 24-hour reminders to send thank-you emails.',
        'Prepare a post-interview reflection template to capture notes while fresh.',
        'Plan next steps: when to expect updates, how to follow up.',
      ],
      completionCriteria: [
        'Thank-you notes drafted for each interviewer',
        '24-hour reminders set',
        'Reflection template prepared',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Send thank-you emails within 24 hours, personalized to each conversation.',
        'Mention something specific from each interview to show engagement.',
        'Use the reflection template to evaluate company fit while memory is fresh.',
      ],
      expectedOutcome: 'A ready-to-execute follow-up plan ensuring professional post-interview communication.',
    },
  ],
  'phone-screen': [
    {
      id: 'ps-screen-prep',
      title: 'Prepare for Phone Screen',
      objective: 'Ace the initial screening call with recruiters.',
      instructions: [
        'Research the recruiter on LinkedIn before the call.',
        'Prepare your 30-second introduction: who you are, what you do, what you want.',
        'Have your salary expectations and availability ready.',
        'Prepare 3 questions about the role and company.',
      ],
      completionCriteria: [
        'Recruiter researched on LinkedIn',
        '30-second introduction prepared',
        'Salary expectations and availability defined',
        '3 questions prepared to ask',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Phone screens are about fit, not technical depth.',
        'Be enthusiastic but honest about your experience.',
        'Let the recruiter lead the conversation — answer their questions directly.',
      ],
      expectedOutcome: 'Full preparation for a phone screen call with clear talking points and questions.',
    },
    {
      id: 'ps-environment-setup',
      title: 'Set Up Phone Screen Environment',
      objective: 'Ensure a professional, distraction-free call experience.',
      instructions: [
        'Find a quiet room with good acoustics.',
        'Test your microphone, camera, and internet connection.',
        'Close unnecessary browser tabs and applications.',
        'Have your resume, notes, and questions printed or on a second screen.',
      ],
      completionCriteria: [
        'Quiet environment confirmed',
        'Audio/video equipment tested',
        'Reference materials accessible',
      ],
      estimatedMinutes: 5,
      difficulty: 1,
      tips: [
        'Wired headphones are more reliable than Bluetooth.',
        'Turn off phone notifications and computer alerts.',
        'Have a glass of water nearby.',
      ],
      expectedOutcome: 'A professional environment that ensures clear communication during the phone screen.',
    },
  ],
  'interview-followup': [
    {
      id: 'if-thank-you',
      title: 'Send Personalized Thank-You Emails',
      objective: 'Leave a positive lasting impression after each interview.',
      instructions: [
        'Within 2 hours of the interview, write thank-you emails to each interviewer.',
        'Reference a specific topic discussed to show engagement.',
        'Reiterate your enthusiasm for the role and company.',
        'Keep each email to 3-5 sentences.',
      ],
      completionCriteria: [
        'Thank-you email sent to each interviewer',
        'Each email references a specific discussion point',
        'All emails sent within 24 hours of interview',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Personalization matters — generic thank-yous are worse than none.',
        'If you forgot to ask something, now is the time to bring it up.',
        'Proofread twice — a typo in a thank-you leaves a poor impression.',
      ],
      expectedOutcome: 'Personalized thank-you emails sent to all interviewers, reinforcing your candidacy.',
    },
    {
      id: 'if-reflection',
      title: 'Write Interview Reflection',
      objective: 'Capture learnings while the interview is fresh.',
      instructions: [
        'Immediately after the interview, write down every question you remember.',
        'Score your answers: what went well, what could improve.',
        'Note any questions that surprised you or you struggled with.',
        'Document any information learned about the role or company.',
      ],
      completionCriteria: [
        'All questions documented',
        'Self-scoring completed for each answer',
        'Surprising or difficult questions noted for future practice',
        'Company/role insights captured',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Do this immediately after the interview — memory fades fast.',
        'This helps improve for future interviews.',
        'Compare reflections across interviews to spot patterns.',
      ],
      expectedOutcome: 'A detailed interview reflection that captures questions, performance, and insights for improvement.',
    },
    {
      id: 'if-next-steps',
      title: 'Plan Next Steps and Timeline',
      objective: 'Manage expectations and follow-up timing professionally.',
      instructions: [
        'Note any timelines the interviewer provided for next steps.',
        'Set a calendar reminder for the expected response date + 2 days.',
        'Prepare a polite follow-up email template for checking in.',
        'Continue applying to other roles — do not pause your search.',
      ],
      completionCriteria: [
        'Response timeline documented',
        'Follow-up reminder set',
        'Wait-time follow-up email template prepared',
      ],
      estimatedMinutes: 5,
      difficulty: 1,
      tips: [
        'Never stop applying until you have a signed offer.',
        'Following up too soon looks desperate; too late looks disinterested.',
        'One follow-up per week max — more is counterproductive.',
      ],
      expectedOutcome: 'A clear post-interview action plan with timelines and backup strategies.',
    },
  ],
  'presentation-prep': [
    {
      id: 'pp-outline-talk',
      title: 'Outline Your Interview Presentation',
      objective: 'Structure a compelling presentation for presentation-based interviews.',
      instructions: [
        'Define the presentation goal and audience level.',
        'Create a 3-part structure: problem, solution, impact.',
        'Allocate time: intro (10%), main content (70%), Q&A (20%).',
        'Identify the key message you want the audience to remember.',
      ],
      completionCriteria: [
        'Presentation goal and audience defined',
        '3-part structure created with time allocation',
        'Key message identified for audience retention',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Start with a hook — a surprising fact, a story, or a problem.',
        'Use the rule of three: people remember three things.',
        'Leave time for Q&A — it often makes or breaks the presentation.',
      ],
      expectedOutcome: 'A clear outline for an interview presentation with logical flow and key message.',
    },
    {
      id: 'pp-create-slides',
      title: 'Create Presentation Slides',
      objective: 'Design clean, professional slides that support your narrative.',
      instructions: [
        'Create 8-12 slides following your outline.',
        'Use minimal text — keywords and phrases, not paragraphs.',
        'Include diagrams, screenshots, or data visualizations where relevant.',
        'Ensure consistent formatting: fonts, colors, spacing.',
      ],
      completionCriteria: [
        '8-12 slides created following outline',
        'Minimal text per slide (max 5 bullet points)',
        'Visuals included to support key points',
        'Consistent formatting throughout',
      ],
      estimatedMinutes: 30,
      difficulty: 3,
      tips: [
        'Slides are visuals, not your script — they support, not replace, your words.',
        'Use a clean, professional template.',
        'If applicable, include a demo or live code walkthrough.',
      ],
      expectedOutcome: 'A professional slide deck ready for interview presentation delivery.',
    },
    {
      id: 'pp-rehearse',
      title: 'Rehearse Presentation With Recording',
      objective: 'Polish delivery and timing before the actual presentation.',
      instructions: [
        'Record yourself delivering the full presentation.',
        'Review the recording: timing, clarity, body language, transitions.',
        'Adjust content or pacing based on review.',
        'Rehearse again until the presentation fits within the time limit.',
      ],
      completionCriteria: [
        'Full presentation recorded and reviewed',
        'Timing adjusted to fit within limit',
        '2+ rehearsals completed',
      ],
      estimatedMinutes: 30,
      difficulty: 2,
      tips: [
        'Practice transitioning between slides smoothly.',
        'Prepare for technical issues: have offline backups.',
        'Watch for nervous habits: pacing, hand gestures, filler words.',
      ],
      expectedOutcome: 'A polished, timed presentation delivered confidently after multiple rehearsals.',
    },
  ],
};
