import type { TaskContent } from '@/core/task_content';

export const LINKEDIN_TASKS: Record<string, TaskContent[]> = {
  'headline-authority': [
    {
      id: 'ha-draft-options',
      title: 'Draft 3 Headline Options',
      objective: 'Create multiple headline variations to test which performs best.',
      instructions: [
        'Open your LinkedIn profile and navigate to the headline section.',
        'Write 3 headlines combining: your role + specialty + value proposition.',
        'Option 1: Role-focused (e.g., "Senior Software Engineer | React & TypeScript").',
        'Option 2: Problem-focused (e.g., "Helping teams build scalable web applications").',
        'Option 3: Hybrid (e.g., "Software Engineer | React & Node.js | Building products users love").',
      ],
      completionCriteria: [
        '3 headline options written',
        'Each includes role and specialty keywords',
        'Value proposition present in at least 2 options',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Use keywords recruiters search for — check job descriptions for common terms.',
        'Keep headlines under 220 characters (LinkedIn limit).',
        'Add relevant emojis sparingly to stand out in search results.',
      ],
      expectedOutcome: '3 tested headline options ready for A/B testing and final selection.',
    },
    {
      id: 'ha-research-top',
      title: 'Research Top Headlines in Your Field',
      objective: 'Learn from effective headlines used by professionals in your target role.',
      instructions: [
        'Search for people in your target role and location on LinkedIn.',
        'Review the headlines of the top 10 profiles that appear in search.',
        'Note common patterns: keywords, formats, emoji usage, certifications.',
        'Document the elements you want to incorporate into your own headline.',
      ],
      completionCriteria: [
        '10 headlines reviewed and documented',
        'Common keyword patterns identified',
        'Personal headline updated based on research',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Search for your target title and see who ranks high in search.',
        'Notice how they differentiate from others with similar titles.',
        'Look at both generalists and specialists for different approaches.',
      ],
      expectedOutcome: 'A research-informed headline that incorporates proven patterns from your industry.',
    },
    {
      id: 'ha-test-pick',
      title: 'A/B Test and Select Best Headline',
      objective: 'Use feedback to choose the most effective headline.',
      instructions: [
        'Post your top 2 headline options in a relevant LinkedIn group or share with peers.',
        'Ask for specific feedback: which makes you want to learn more?',
        'Monitor which option gets more engagement or positive reactions.',
        'Select the winning headline and update your profile.',
      ],
      completionCriteria: [
        '2 options shared for feedback',
        'Feedback received from at least 3 people',
        'Winning headline selected and applied to profile',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Test different angles: role-first vs. value-first.',
        'Use LinkedIn analytics to track profile views after updating.',
        'Revisit your headline every 3-6 months as your focus evolves.',
      ],
      expectedOutcome: 'A validated, high-impact headline that increases your LinkedIn visibility.',
    },
  ],
  'about-section': [
    {
      id: 'as-draft-paragraphs',
      title: 'Draft 3-Paragraph About Section',
      objective: 'Write a compelling story in the standard three-paragraph format.',
      instructions: [
        'Paragraph 1: Open with who you are — your role, experience, and passion.',
        'Paragraph 2: Describe what you do — key accomplishments and expertise.',
        'Paragraph 3: State what you are looking for — next role, collaboration, or impact.',
        'Keep each paragraph to 3-5 sentences. Write in first person.',
      ],
      completionCriteria: [
        '3 paragraphs written (who, what, what next)',
        'Each paragraph is 3-5 sentences',
        'Written in first person with active voice',
      ],
      estimatedMinutes: 20,
      difficulty: 3,
      tips: [
        'Open with your strongest point — the first line determines if they read on.',
        'Include keywords from your target role descriptions.',
        'End with a call to action: "Open to opportunities in..."',
      ],
      expectedOutcome: 'A complete, story-driven About section that engages visitors and includes SEO keywords.',
    },
    {
      id: 'as-review-examples',
      title: 'Review Compelling About Sections',
      objective: 'Analyze effective About sections to improve your own writing.',
      instructions: [
        'Find 5 LinkedIn profiles with strong, engaging About sections.',
        'Note how they structure their opening, body, and closing.',
        'Identify storytelling techniques: personal anecdotes, metrics, vision.',
        'Extract 3 specific techniques to apply to your About section.',
      ],
      completionCriteria: [
        '5 strong About sections reviewed',
        'Storytelling techniques documented',
        '3 techniques selected for personal application',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Look for profiles with "Featured" sections — these are often well-maintained.',
        'Notice how they transition between professional and personal.',
        'Good About sections show personality while remaining professional.',
      ],
      expectedOutcome: 'A refined About section that uses proven storytelling and engagement techniques.',
    },
    {
      id: 'as-edit-impact',
      title: 'Edit About Section for Impact',
      objective: 'Strengthen your writing by cutting unnecessary words.',
      instructions: [
        'Copy your draft About section into a clean document.',
        'Cut 30% of the word count by removing filler words and weak phrases.',
        'Replace passive voice with active voice throughout.',
        'Read the condensed version — is every word necessary?',
      ],
      completionCriteria: [
        'Word count reduced by 30% from original draft',
        'No passive voice remaining',
        'Core message preserved or strengthened',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Remove: very, really, just, actually, literally, that.',
        'Replace "was responsible for" with "led," "built," "created."',
        'Short sentences are more powerful than long ones.',
      ],
      expectedOutcome: 'A tight, impactful About section where every word earns its place.',
    },
  ],
  'network-connections': [
    {
      id: 'nc-personalized-requests',
      title: 'Send 5 Personalized Connection Requests',
      objective: 'Build your network with meaningful, personalized outreach.',
      instructions: [
        'Identify 5 people in your target industry or companies of interest.',
        'Visit each profile and find a common ground: alma mater, mutual connection, shared interest.',
        'Write a personalized invitation mentioning the specific reason for connecting.',
        'Send all 5 requests and track responses in a spreadsheet.',
      ],
      completionCriteria: [
        '5 personalized requests sent',
        'Each includes a specific reference to their profile',
        'Connection tracking spreadsheet created',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Do not use the generic LinkedIn invite — always customize.',
        'Reference something specific: their recent post, shared group, or mutual connection.',
        'Keep it to 2-3 sentences. Be respectful of their time.',
      ],
      expectedOutcome: '5 new strategic connections and a template for ongoing network building.',
    },
    {
      id: 'nc-engage-content',
      title: 'Engage With 5 Industry Posts',
      objective: 'Increase your visibility by contributing to industry conversations.',
      instructions: [
        'Find 5 recent posts from your target companies or industry leaders.',
        'Read each post thoroughly and understand the key points.',
        'Write a meaningful comment that adds value or asks a thoughtful question.',
        'Reshare one post with your own commentary to establish thought leadership.',
      ],
      completionCriteria: [
        '5 meaningful comments posted',
        '1 post reshared with original commentary',
        'All comments professional and value-adding',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Do not just say "Great post!" — add insight, a question, or a different perspective.',
        'Tag relevant connections if it adds value to the conversation.',
        'Consistent engagement builds your reputation over time.',
      ],
      expectedOutcome: 'Increased LinkedIn visibility through valuable community participation.',
    },
    {
      id: 'nc-audit-network',
      title: 'Audit Your Current Network',
      objective: 'Understand your network composition and identify gaps.',
      instructions: [
        'Export or review your current LinkedIn connections list.',
        'Categorize connections: colleagues, managers, recruiters, industry peers, alumni.',
        'Identify which categories are under-represented.',
        'Set specific targets for growing underrepresented categories.',
      ],
      completionCriteria: [
        'All connections categorized by type',
        'Gap analysis completed with target categories identified',
        'Growth targets set for each under-represented category',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Quality over quantity — 200 relevant connections beat 500 random ones.',
        'Recruiters and hiring managers are high-value connection targets.',
        'Alumni from your school are usually very receptive to connecting.',
      ],
      expectedOutcome: 'A clear picture of your network strengths and gaps with a growth plan.',
    },
  ],
  'linkedin-optimization': [
    {
      id: 'lo-full-audit',
      title: 'Complete Full Profile Audit',
      objective: 'Ensure every section of your LinkedIn profile is optimized.',
      instructions: [
        'Review each section: photo, banner, headline, about, experience, education, skills, recommendations.',
        'Score each section as complete, partial, or missing.',
        'Create an action plan for each section scored below "complete."',
        'Set a deadline to finish all improvements.',
      ],
      completionCriteria: [
        'All profile sections audited and scored',
        'Missing or weak sections identified',
        'Action plan with deadlines created',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Profiles with photos get 21x more profile views.',
        'Profiles with complete sections appear higher in search results.',
        'Use the "Open to Work" feature to signal availability to recruiters.',
      ],
      expectedOutcome: 'A complete LinkedIn profile with a clear improvement action plan.',
    },
    {
      id: 'lo-keyword-insert',
      title: 'Insert Keywords Into Profile',
      objective: 'Improve your LinkedIn search ranking with targeted keywords.',
      instructions: [
        'Compile the top 15 keywords from your target job descriptions.',
        'Distribute keywords across headline, about, experience, and skills sections.',
        'Ensure each keyword appears naturally in context.',
        'Verify that your skills section has the most important skills listed.',
      ],
      completionCriteria: [
        '15 keywords distributed across profile sections',
        'Keywords appear naturally in context',
        'Skills section reordered with top skills first',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'LinkedIn search ranks profiles by keyword density in headline and about.',
        'List skills that recruiters search for — check your target job postings.',
        'Endorse others to receive endorsements back, boosting skill credibility.',
      ],
      expectedOutcome: 'A keyword-optimized LinkedIn profile that ranks higher in recruiter searches.',
    },
    {
      id: 'lo-content-strategy',
      title: 'Create a Content Sharing Strategy',
      objective: 'Establish a consistent LinkedIn presence through regular content sharing.',
      instructions: [
        'Define your content focus areas (e.g., software engineering, career growth).',
        'Create a content calendar: 2 posts per week, 5 engagements per day.',
        'Prepare 4 post drafts in advance: a tip, a story, a question, a resource.',
        'Schedule your first 2 posts for the upcoming week.',
      ],
      completionCriteria: [
        'Content focus areas defined',
        'Content calendar created with weekly targets',
        '4 post drafts ready for publishing',
      ],
      estimatedMinutes: 20,
      difficulty: 3,
      tips: [
        'Share what you know: tutorials, lessons learned, industry insights.',
        'Consistency matters more than perfection — post regularly.',
        'Engage with commenters to boost post visibility in the algorithm.',
      ],
      expectedOutcome: 'A sustainable LinkedIn content strategy with ready-to-publish posts.',
    },
  ],
  'profile-photo': [
    {
      id: 'pp-photo-check',
      title: 'Evaluate Your Current Profile Photo',
      objective: 'Assess whether your current photo makes a professional impression.',
      instructions: [
        'Open your current LinkedIn profile photo in full size.',
        'Check: is it a clear headshot? Is your face visible? Is the background neutral?',
        'Ask 3 peers: does this photo convey professionalism?',
        'If the photo fails any check, plan a new photo session.',
      ],
      completionCriteria: [
        'Current photo evaluated against professional standards',
        'Peer feedback collected from 3 people',
        'Decision made: keep or replace',
      ],
      estimatedMinutes: 5,
      difficulty: 1,
      tips: [
        'A professional headshot increases profile views significantly.',
        'Dress as you would for an interview in your target role.',
        'Use a plain or subtle background — avoid busy environments.',
      ],
      expectedOutcome: 'A decision on your current photo quality and a plan to improve if needed.',
    },
    {
      id: 'pp-new-photo',
      title: 'Take or Select a New Profile Photo',
      objective: 'Get a high-quality professional headshot for your profile.',
      instructions: [
        'If using a smartphone: stand in natural lighting facing a window.',
        'Use a neutral background: plain wall or professional setting.',
        'Take 10-15 shots with different expressions and angles.',
        'Select the best photo and crop to a proper headshot ratio.',
      ],
      completionCriteria: [
        '10+ photos taken in good lighting',
        'Best photo selected and cropped',
        'Photo uploaded to LinkedIn profile',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Wear solid colors — avoid busy patterns or stripes.',
        'Natural light from a window is better than artificial lighting.',
        'Smile naturally — approachable expressions perform better.',
      ],
      expectedOutcome: 'A professional, high-quality profile photo that makes a strong first impression.',
    },
  ],
  'featured-content': [
    {
      id: 'fc-select-assets',
      title: 'Select Your Best Work for Featured Section',
      objective: 'Curate content that demonstrates your expertise and impact.',
      instructions: [
        'Review your portfolio, GitHub, publications, and presentations.',
        'Select 3-5 pieces that best represent your skills and achievements.',
        'Ensure each piece is accessible (public link, no paywall).',
        'Write a 1-sentence description for each explaining the impact.',
      ],
      completionCriteria: [
        '3-5 pieces of content selected',
        'All links are accessible and working',
        'Description written for each piece',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Include a mix: projects, articles, presentations, media features.',
        'If you have a popular post or article, feature it prominently.',
        'Update featured content quarterly as you create new work.',
      ],
      expectedOutcome: 'A curated Featured section that showcases your best professional work.',
    },
    {
      id: 'fc-organize',
      title: 'Organize Featured Content Strategically',
      objective: 'Arrange your featured content for maximum impact.',
      instructions: [
        'Open your LinkedIn profile and navigate to the Featured section.',
        'Add your selected content in order of relevance to your target role.',
        'Lead with your strongest, most relevant piece.',
        'Verify all items display correctly on both desktop and mobile.',
      ],
      completionCriteria: [
        'Featured content added and ordered strategically',
        'First item is the most impactful for target audience',
        'Content displays correctly on mobile and desktop',
      ],
      estimatedMinutes: 5,
      difficulty: 1,
      tips: [
        'Your first featured item is what visitors see without scrolling.',
        'Feature content that tells a story about your career progression.',
        'Remove outdated or low-quality content that no longer represents your best work.',
      ],
      expectedOutcome: 'A well-organized Featured section that immediately communicates your value.',
    },
  ],
  recommendations: [
    {
      id: 'rec-request-two',
      title: 'Request 2 Recommendations Strategically',
      objective: 'Build social proof on your profile through colleague endorsements.',
      instructions: [
        'Identify 2 former managers or colleagues who can speak to your strengths.',
        'Write personalized recommendation request messages mentioning specific projects.',
        'Suggest skills or qualities you hope they will highlight.',
        'Send requests and follow up after 1 week if no response.',
      ],
      completionCriteria: [
        '2 recommendation requests sent',
        'Each request references specific work together',
        'Skill suggestions included in each request',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Former managers carry more weight than peer recommendations.',
        'Make it easy: offer bullet points of what you worked on together.',
        'Write recommendations for others — they will often reciprocate.',
      ],
      expectedOutcome: '2 new LinkedIn recommendations boosting your profile credibility.',
    },
    {
      id: 'rec-write-others',
      title: 'Write Recommendations for 2 Colleagues',
      objective: 'Strengthen your professional relationships through meaningful endorsements.',
      instructions: [
        'Select 2 colleagues whose work you can genuinely vouch for.',
        'Write a specific recommendation: how you worked together, their strengths, results.',
        'Include specific examples of their impact or skills.',
        'Publish the recommendations on their profiles.',
      ],
      completionCriteria: [
        '2 recommendations written and published',
        'Each includes specific examples and outcomes',
        'Recommendations are 3-5 sentences each',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Being generous with recommendations encourages reciprocity.',
        'Write recommendations promptly when asked — it builds goodwill.',
        'Quality recommendations mention specific results, not just traits.',
      ],
      expectedOutcome: 'Strengthened professional relationships and increased likelihood of receiving recommendations back.',
    },
  ],
};
