import type { TaskContent } from '@/core/task_content';

export const OFFER_TASKS: Record<string, TaskContent[]> = {
  'offer-evaluation': [
    {
      id: 'oe-list-components',
      title: 'List All Offer Components',
      objective: 'Document every element of your offer for a complete view.',
      instructions: [
        'Write down the base salary offered.',
        'Document all other components: bonus, equity, benefits, PTO, perks, signing bonus.',
        'Note any components with missing or unclear information.',
        'Create a total compensation estimate including all cash and non-cash items.',
      ],
      completionCriteria: [
        'Base salary documented',
        'All additional components listed',
        'Missing information flagged for follow-up',
        'Total compensation estimated',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Equity can be confusing — ask for the dollar value or number of shares.',
        'Benefits like health insurance, 401k match, and education stipends have real value.',
        'Consider all components, not just salary.',
      ],
      expectedOutcome: 'A complete breakdown of your offer with total estimated compensation.',
    },
    {
      id: 'oe-market-compare',
      title: 'Compare Offer Against Market Data',
      objective: 'Validate your offer is competitive in the current market.',
      instructions: [
        'Research market rates for your role, level, and location using 3 sources.',
        'Compare each component of your offer against market benchmarks.',
        'Identify which components are above, at, or below market.',
        'Calculate the gap between your offer and top-of-market for each component.',
      ],
      completionCriteria: [
        'Market data collected from 3 sources',
        'Offer compared to market for each component',
        'Gaps identified for negotiation targets',
      ],
      estimatedMinutes: 20,
      difficulty: 2,
      tips: [
        'Use Levels.fyi, Glassdoor, and Blind for compensation data.',
        'Adjust for location — remote roles may have location-based pay.',
        'Data from the last 6 months is most relevant.',
      ],
      expectedOutcome: 'A market-validated assessment of your offer with clear negotiation targets.',
    },
    {
      id: 'oe-fit-scorecard',
      title: 'Score Offer Against Personal Priorities',
      objective: 'Evaluate how well the offer aligns with your career and life goals.',
      instructions: [
        'Define your top 5 priorities in a new role (e.g., compensation, growth, culture, location, mission).',
        'Weight each priority by importance (total = 100%).',
        'Score the offer on each priority (1-10).',
        'Calculate a weighted total score to guide your decision.',
      ],
      completionCriteria: [
        '5 priorities defined and weighted',
        'Offer scored against each priority',
        'Weighted total score calculated',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Be honest about what matters — not what you think should matter.',
        'Consider your stage of life and career.',
        'A score below 7/10 warrants careful consideration before accepting.',
      ],
      expectedOutcome: 'A quantitative scorecard that objectively measures offer fit against your personal priorities.',
    },
  ],
  'salary-negotiation': [
    {
      id: 'sn-prepare-numbers',
      title: 'Prepare Your Numbers',
      objective: 'Define your target, walk-away, and stretch numbers.',
      instructions: [
        'Based on market research, set your target total compensation.',
        'Define your walk-away number — the minimum you will accept.',
        'Set a stretch goal — the number you would be thrilled with.',
        'Document the justification for each number using market data.',
      ],
      completionCriteria: [
        'Target number defined with market justification',
        'Walk-away number defined',
        'Stretch goal defined',
        'All numbers supported by market data',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Your target should be in the top 25% of market range.',
        'Your walk-away should be realistic, not emotional.',
        'Have confidence in your numbers — you did the research.',
      ],
      expectedOutcome: 'Clear negotiation numbers with market-based justification ready for the conversation.',
    },
    {
      id: 'sn-write-script',
      title: 'Write Negotiation Script',
      objective: 'Prepare your talking points for the negotiation conversation.',
      instructions: [
        'Write an opening statement expressing enthusiasm and your ask.',
        'Include your key justification points backed by market data.',
        'Prepare responses to common pushbacks: budget constraints, team equity, etc.',
        'Write a closing statement that keeps the conversation positive.',
      ],
      completionCriteria: [
        'Opening statement with enthusiasm and ask',
        'Justification points with market data references',
        'Responses to 3 common pushbacks prepared',
        'Positive closing statement written',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Start with enthusiasm — "I am very excited about this role..."',
        'Use market data, not personal need, as justification.',
        'Keep the tone collaborative, not adversarial.',
      ],
      expectedOutcome: 'A complete negotiation script ready for practice and execution.',
    },
    {
      id: 'sn-roleplay',
      title: 'Record Negotiation Roleplay',
      objective: 'Practice the negotiation conversation to build confidence.',
      instructions: [
        'Find a friend to play the recruiter role, or record both sides yourself.',
        'Deliver your opening statement and ask.',
        'Handle their pushbacks using your prepared responses.',
        'Listen to the recording and refine your delivery.',
      ],
      completionCriteria: [
        'Roleplay recorded with both sides',
        'Opening statement delivered clearly',
        'Pushbacks handled with prepared responses',
        'Delivery refined after review',
      ],
      estimatedMinutes: 15,
      difficulty: 3,
      tips: [
        'Practice saying your numbers out loud — it feels different than writing them.',
        'Work on a calm, confident tone.',
        'The more you practice, the less intimidating the real conversation.',
      ],
      expectedOutcome: 'A practiced, confident delivery of your negotiation points after roleplay feedback.',
    },
  ],
  'decision-framework': [
    {
      id: 'df-create-scorecard',
      title: 'Create Weighted Decision Scorecard',
      objective: 'Build an objective system for comparing multiple offers.',
      instructions: [
        'Define 6-8 decision factors: compensation, growth, culture, impact, location, benefits, mission, team.',
        'Assign weight to each factor (total 100%).',
        'Create a scoring template with columns for each offer.',
        'Test the scorecard with a hypothetical scenario.',
      ],
      completionCriteria: [
        '6-8 decision factors defined and weighted',
        'Scoring template created with offer columns',
        'Scorecard tested with sample scenario',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Use the same scorecard for all offers for fair comparison.',
        'Involve a partner or mentor in choosing weights — external perspective helps.',
        'Revisit weights if your priorities shift during the process.',
      ],
      expectedOutcome: 'A reusable decision scorecard for objective offer comparison.',
    },
    {
      id: 'df-pro-con-list',
      title: 'Write Comprehensive Pros and Cons',
      objective: 'Surface all considerations for an informed decision.',
      instructions: [
        'For each offer, write a pros list with at least 5 items.',
        'Write a cons list with at least 5 items.',
        'Include both professional and personal factors.',
        'Review the lists after 24 hours — do they change?',
      ],
      completionCriteria: [
        '5+ pros documented per offer',
        '5+ cons documented per offer',
        'Professional and personal factors included',
        'Lists reviewed after 24-hour reflection',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Sleep on it — decisions made after a good night are usually better.',
        'Share with a trusted advisor for external perspective.',
        'Listen to your gut after analyzing the facts.',
      ],
      expectedOutcome: 'A thorough pros and cons analysis for each offer with time for reflection.',
    },
    {
      id: 'df-consult-advisors',
      title: 'Consult 2 Trusted Advisors',
      objective: 'Get external perspective before making your final decision.',
      instructions: [
        'Identify 2 people whose career advice you trust.',
        'Share your offers, scorecard, and pros/cons with each.',
        'Ask specific questions: "What am I not considering?" "Which aligns better with my long-term goals?"',
        'Document their advice and incorporate into your decision.',
      ],
      completionCriteria: [
        '2 advisors consulted with offers and analysis',
        'Specific questions asked to each',
        'Advisor input documented and considered',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Choose advisors with different perspectives (e.g., mentor + peer).',
        'Be open to feedback that challenges your assumptions.',
        'The final decision is yours — advisors inform, not decide.',
      ],
      expectedOutcome: 'External perspectives that challenge assumptions and strengthen your decision process.',
    },
  ],
  'offer-acceptance': [
    {
      id: 'oa-draft-letter',
      title: 'Draft Acceptance or Decline Letter',
      objective: 'Prepare professional communication for your decision.',
      instructions: [
        'Write an acceptance letter/email with: enthusiasm, offer acceptance, start date confirmation.',
        'Alternatively, write a decline letter that maintains a positive relationship.',
        'Include any next steps: background check, paperwork, onboarding.',
        'Proofread carefully — this is your final impression.',
      ],
      completionCriteria: [
        'Acceptance or decline letter drafted',
        'Key details included: date, terms, next steps',
        'Letter proofread and saved',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'An acceptance letter should express genuine enthusiasm.',
        'A decline letter should be gracious — you may cross paths again.',
        'Keep a copy for your records.',
      ],
      expectedOutcome: 'A professional acceptance or decline letter ready for delivery.',
    },
    {
      id: 'oa-pre-boarding',
      title: 'Complete Pre-Boarding Checklist',
      objective: 'Ensure nothing is missed between acceptance and start date.',
      instructions: [
        'Complete all new hire paperwork: tax forms, direct deposit, contracts.',
        'Confirm start date, time, location, and point of contact.',
        'Set up any required accounts or tools in advance.',
        'Plan your first week: who to meet, what to learn, goals to set.',
      ],
      completionCriteria: [
        'All paperwork completed and submitted',
        'Start date logistics confirmed',
        'First week plan created',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Ask about equipment setup — IT may need to ship you a laptop.',
        'Reach out to your manager about the first week agenda.',
        'Prepare questions for your first day to show initiative.',
      ],
      expectedOutcome: 'Complete readiness for a smooth start at your new role.',
    },
    {
      id: 'oa-transition-plan',
      title: 'Create Transition Plan',
      objective: 'Leave your current role professionally and set yourself up for success.',
      instructions: [
        'Write a resignation letter if employed, giving appropriate notice.',
        'Create a knowledge transfer document for your current responsibilities.',
        'Plan your last week: handoffs, farewells, final deliverables.',
        'Set personal onboarding goals for the first 30 days in the new role.',
      ],
      completionCriteria: [
        'Resignation letter written',
        'Knowledge transfer document created',
        'Last week plan completed',
        '30-day onboarding goals defined',
      ],
      estimatedMinutes: 20,
      difficulty: 2,
      tips: [
        'Give at least 2 weeks notice — 3-4 weeks is better for senior roles.',
        'Leave on good terms — you never know when paths will cross again.',
        'The first 30 days are about learning, not proving.',
      ],
      expectedOutcome: 'A professional transition plan that ensures a graceful exit and strong start.',
    },
  ],
  'equity-evaluation': [
    {
      id: 'ee-understand-terms',
      title: 'Understand Your Equity Terms',
      objective: 'Learn how to evaluate stock options, RSUs, and other equity components.',
      instructions: [
        'Identify the type of equity offered: ISO, NSO, RSU, or ESPP.',
        'Learn key terms: vesting schedule, cliff, exercise price, strike price, FMV.',
        'Calculate the potential value at different exit scenarios.',
        'Document any questions to ask the recruiter or HR.',
      ],
      completionCriteria: [
        'Equity type identified',
        'Key terms understood and documented',
        'Potential value calculated for 3 scenarios',
        'Questions prepared for follow-up',
      ],
      estimatedMinutes: 20,
      difficulty: 4,
      tips: [
        'Equity at startups is speculative — value it at 0 in your baseline calculation.',
        'Understand the difference between strike price and fair market value.',
        'The vesting start date matters more than the grant date.',
      ],
      expectedOutcome: 'A clear understanding of your equity package and its potential value.',
    },
    {
      id: 'ee-compare-packages',
      title: 'Compare Equity Across Offers',
      objective: 'Evaluate equity components side by side for informed decision-making.',
      instructions: [
        'For each offer, calculate equity value at expected, optimistic, and conservative scenarios.',
        'Adjust for company stage: startup, growth, public.',
        'Consider dilution risk for early-stage companies.',
        'Create a comparison table for easy reference.',
      ],
      completionCriteria: [
        'Equity valued at 3 scenarios per offer',
        'Company stage considered in valuation',
        'Dilution risk assessed for startups',
        'Comparison table created',
      ],
      estimatedMinutes: 15,
      difficulty: 3,
      tips: [
        'Public company equity is more predictable than startup equity.',
        'Ask about the company\'s 409A valuation for early-stage offers.',
        'Total compensation matters more than any single component.',
      ],
      expectedOutcome: 'An apples-to-apples equity comparison across all offers.',
    },
  ],
  'start-transition': [
    {
      id: 'st-first-week-plan',
      title: 'Plan Your First Week',
      objective: 'Make a strong impression from day one.',
      instructions: [
        'Identify key people to meet in your first week: manager, team, cross-functional partners.',
        'Set up 1:1s with each person to learn about their role and your collaboration.',
        'Learn the tech stack, tools, and workflows your team uses.',
        'Define 3 goals for your first 30 days.',
      ],
      completionCriteria: [
        'List of key people to meet created',
        '1:1 meetings scheduled',
        'Tech stack and tools documented',
        '3 first-month goals defined',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Your first week is about relationships and learning, not deliverables.',
        'Ask questions — it shows engagement and speeds up ramp-up.',
        'Document everything: processes, passwords, important contacts.',
      ],
      expectedOutcome: 'A structured plan for a productive first week that builds momentum.',
    },
    {
      id: 'st-30-60-90',
      title: 'Create 30-60-90 Day Plan',
      objective: 'Set a structured ramp-up plan for your first 3 months.',
      instructions: [
        'Month 1 (Learn): List knowledge areas to master, people to meet, systems to learn.',
        'Month 2 (Contribute): Define small projects or improvements to deliver.',
        'Month 3 (Own): Identify areas where you will take full ownership.',
        'Share this plan with your manager for alignment.',
      ],
      completionCriteria: [
        '30-day learning goals defined',
        '60-day contribution goals defined',
        '90-day ownership goals defined',
        'Plan shared with manager for feedback',
      ],
      estimatedMinutes: 20,
      difficulty: 2,
      tips: [
        'A 30-60-90 plan shows initiative and strategic thinking.',
        'Review and adjust the plan with your manager monthly.',
        'Include both technical and cultural integration goals.',
      ],
      expectedOutcome: 'A comprehensive 30-60-90 day ramp-up plan aligned with your manager.',
    },
    {
      id: 'st-exit-graceful',
      title: 'Exit Current Role Gracefully',
      objective: 'Leave your current position professionally and preserve relationships.',
      instructions: [
        'Notify your manager in person or via video call before sending formal resignation.',
        'Write a formal resignation letter with appropriate notice period.',
        'Complete a knowledge transfer document for your responsibilities.',
        'Plan farewell messages and handoffs for key relationships.',
      ],
      completionCriteria: [
        'Manager notified in person',
        'Formal resignation letter submitted',
        'Knowledge transfer document completed',
        'Farewell plan created for key relationships',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Never burn bridges — your reputation follows you.',
        'Offer to help with the transition even after your last day.',
        'Connect with colleagues on LinkedIn before you leave.',
      ],
      expectedOutcome: 'A professional exit process that preserves relationships and reputation.',
    },
  ],
};
