import type { TaskContent } from '@/core/task_content';

export const RESUME_TASKS: Record<string, TaskContent[]> = {
  'positioning-clarity': [
    {
      id: 'pc-write-target',
      title: 'Write Your Target Role Statement',
      objective: 'Define your exact career target with specific role title and industry.',
      instructions: [
        'Open a blank document or your resume header section.',
        'Write your target job title (e.g., "Senior Frontend Engineer at a Series B tech company").',
        'List 3 dream companies where you would love to work.',
        'Write 2-3 sentences explaining why this role fits your background.',
      ],
      completionCriteria: [
        'Target job title is specific (not just "Software Engineer")',
        '3 dream companies are named',
        'Role-fit explanation references your past experience',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Use job boards to find titles that match your experience level.',
        'Look at LinkedIn profiles of people in roles you want.',
        'Be specific — generic targets lead to generic applications.',
      ],
      expectedOutcome: 'A clear positioning statement that guides your resume, LinkedIn, and interview preparation.',
    },
    {
      id: 'pc-research-market',
      title: 'Research Market Positioning',
      objective: 'Understand how your target role is positioned in the current job market.',
      instructions: [
        'Search for your target job title on 2 job boards.',
        'Save 5 job postings that match your experience level.',
        'Note common keywords, required skills, and responsibilities across postings.',
        'Compare your current experience against these requirements.',
      ],
      completionCriteria: [
        '5 job postings saved or bookmarked',
        'Common keywords extracted from postings',
        'Skills gap analysis completed',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Pay attention to required vs. preferred qualifications.',
        'Note salary ranges to validate your expectations.',
        'Look at posting dates to understand market demand.',
      ],
      expectedOutcome: 'A market-aligned understanding of your target role with clear skill requirements.',
    },
    {
      id: 'pc-record-pitch',
      title: 'Record Your Positioning Pitch',
      objective: 'Practice articulating your positioning verbally for networking and interviews.',
      instructions: [
        'Write a 30-second pitch: who you are, what you do, and what role you are seeking.',
        'Record yourself delivering this pitch using your phone or computer.',
        'Listen to the recording and note areas for improvement.',
        'Re-record with improvements until you are satisfied.',
      ],
      completionCriteria: [
        '30-second pitch script written',
        'Recording made and reviewed',
        'Final recording saved for reference',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Keep it conversational, not scripted.',
        'Practice maintaining eye contact with the camera.',
        'Ask a friend to listen and give feedback.',
      ],
      expectedOutcome: 'A polished verbal pitch that clearly communicates your professional positioning.',
    },
  ],
  'achievement-framing': [
    {
      id: 'af-list-achievements',
      title: 'List 5 Key Career Achievements',
      objective: 'Identify your most impactful accomplishments with measurable results.',
      instructions: [
        'Review your performance reviews, project summaries, and accolades.',
        'Select 5 achievements that had the most business impact.',
        'For each achievement, write: what you did, how you did it, and the measurable outcome.',
        'Quantify results with percentages, dollars, time saved, or other metrics.',
      ],
      completionCriteria: [
        '5 achievements documented',
        'Each achievement includes a specific metric or outcome',
        'Achievements are relevant to your target role',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Use the CAR format: Challenge → Action → Result.',
        'If you do not have exact numbers, estimate conservatively.',
        'Ask former colleagues for achievements you may have forgotten.',
      ],
      expectedOutcome: 'A bank of 5 quantified achievements ready for resume bullets and interview stories.',
    },
    {
      id: 'af-rewrite-responsibilities',
      title: 'Rewrite Responsibilities as Results',
      objective: 'Transform job descriptions into impact-focused bullet points.',
      instructions: [
        'Select 3 current or past job responsibilities from your resume.',
        'For each, rewrite using the format: "Action verb + what you did + measurable outcome."',
        'Remove any phrasing that describes duties rather than accomplishments.',
        'Ensure each bullet can stand alone and prove your value.',
      ],
      completionCriteria: [
        '3 responsibilities transformed into achievements',
        'Each bullet starts with a strong action verb',
        'Each bullet includes a quantified result',
      ],
      estimatedMinutes: 20,
      difficulty: 3,
      tips: [
        'Replace "Responsible for" with verbs like "Led," "Built," "Optimized."',
        'Add context: instead of "Improved performance" say "Reduced load time by 40%."',
        'Use present tense for current roles, past tense for past roles.',
      ],
      expectedOutcome: '3 powerful achievement statements that demonstrate impact, not just activity.',
    },
    {
      id: 'af-format-review',
      title: 'Review and Refine Achievement Format',
      objective: 'Polish your achievement statements for maximum recruiter impact.',
      instructions: [
        'Read each achievement statement out loud.',
        'Check that each is under 2 lines (approximately 25 words).',
        'Remove weak words: "very," "helped," "involved," "participated."',
        'Confirm each statement would make sense to someone outside your company.',
      ],
      completionCriteria: [
        'All achievement statements under 25 words',
        'Weak words removed from all bullets',
        'Outsider-readable — no internal jargon remains',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Use the "so what?" test — if the reader asks this, add more impact.',
        'Avoid acronyms that only your current company uses.',
        'Ask someone outside your field to read and confirm clarity.',
      ],
      expectedOutcome: 'Clean, punchy, achievement-focused resume bullets optimized for recruiter skimming.',
    },
  ],
  'resume-structure': [
    {
      id: 'rs-pick-template',
      title: 'Select an ATS-Friendly Template',
      objective: 'Choose a resume format that passes automated screening systems.',
      instructions: [
        'Research ATS-compatible resume templates online.',
        'Select a template with clean formatting, no columns, and standard fonts.',
        'Download or set up the template in your document editor.',
        'Verify the template preserves formatting when converted to PDF.',
      ],
      completionCriteria: [
        'ATS-compatible template selected',
        'Template tested with PDF conversion',
        'Sections ordered correctly for your target industry',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Avoid tables, text boxes, and graphics — ATS cannot read them.',
        'Use standard section headers: "Experience," "Education," "Skills."',
        'Save in .docx format as well as PDF for applicant portals.',
      ],
      expectedOutcome: 'A clean, parseable resume template that passes ATS screening.',
    },
    {
      id: 'rs-populate-sections',
      title: 'Populate All Resume Sections',
      objective: 'Complete every section of your resume with quality content.',
      instructions: [
        'Fill in your contact information: name, phone, email, LinkedIn URL, portfolio.',
        'Write a 2-3 sentence professional summary.',
        'Add your experience section with achievement bullets from the previous task.',
        'Complete skills section, education, and any optional sections (certifications, projects).',
      ],
      completionCriteria: [
        'Contact section complete with all fields',
        'Professional summary written',
        'Experience section has 3-5 bullet points per role',
        'Skills and education sections populated',
      ],
      estimatedMinutes: 25,
      difficulty: 2,
      tips: [
        'Use reverse chronological order for experience.',
        'Customize your skills section for each application.',
        'Include links to GitHub, portfolio, or personal website if relevant.',
      ],
      expectedOutcome: 'A fully populated resume ready for review and customization.',
    },
    {
      id: 'rs-format-consistency',
      title: 'Audit Formatting Consistency',
      objective: 'Ensure uniform formatting across your entire resume.',
      instructions: [
        'Check that all fonts are the same type and size throughout.',
        'Verify bullet styles are consistent (same indent, same symbol).',
        'Ensure date formatting is uniform (e.g., "Jan 2020 - Mar 2022").',
        'Confirm spacing between sections is equal.',
      ],
      completionCriteria: [
        'Font is consistent across all sections',
        'Bullet points use same style throughout',
        'Dates follow a single format',
        'Spacing is uniform',
      ],
      estimatedMinutes: 5,
      difficulty: 1,
      tips: [
        'Use the "reveal formatting" feature in Word or Google Docs.',
        'Print a PDF version to check alignment and spacing.',
        'Small inconsistencies signal lack of attention to detail.',
      ],
      expectedOutcome: 'A visually consistent, professional resume with no formatting errors.',
    },
  ],
  'resume-review': [
    {
      id: 'rr-self-score',
      title: 'Score Your Resume Across 5 Dimensions',
      objective: 'Systematically evaluate your resume quality.',
      instructions: [
        'Create a scoring rubric: Content (1-5), Structure (1-5), Formatting (1-5), Impact (1-5), Relevance (1-5).',
        'Score your resume honestly on each dimension.',
        'Write 2 specific improvements for your lowest-scoring dimension.',
        'Set a target score for each dimension after improvements.',
      ],
      completionCriteria: [
        'All 5 dimensions scored numerically',
        'Lowest dimension identified with 2 improvement actions',
        'Target scores set for next iteration',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Be honest — an inflated self-assessment delays real improvement.',
        'Use the scoring to track progress across multiple resume revisions.',
        'Compare your scores against job posting requirements.',
      ],
      expectedOutcome: 'A clear picture of resume strengths and weaknesses with an improvement plan.',
    },
    {
      id: 'rr-walkthrough-record',
      title: 'Record Resume Walkthrough',
      objective: 'Hear how your resume sounds when presented verbally.',
      instructions: [
        'Open your resume and start a screen recording.',
        'Walk through each section explaining your choices and content.',
        'Share why you included each bullet point and what it communicates.',
        'Listen to the recording and note any sections that sound weak.',
      ],
      completionCriteria: [
        'Screen recording completed (3-5 minutes)',
        'Each section verbally explained',
        'Weak areas identified from self-review',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'If you struggle to explain a bullet point, it is not clear enough.',
        'Use this recording as practice for interview questions about your resume.',
        'Note filler words ("um," "like") to eliminate from interview speech.',
      ],
      expectedOutcome: 'Identified weak spots in your resume and improved verbal fluency about your background.',
    },
    {
      id: 'rr-peer-submit',
      title: 'Get Peer Review Using Checklist',
      objective: 'Collect structured feedback from a trusted reviewer.',
      instructions: [
        'Find 2 peers or mentors in your target industry.',
        'Send them your resume along with a 5-point review checklist.',
        'Ask them to score each point and provide specific comments.',
        'Thank them and compile feedback into an action list.',
      ],
      completionCriteria: [
        '2 reviewers received resume and checklist',
        'Both reviews returned with scores and comments',
        'Action list created from all feedback',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Give reviewers 48 hours — do not rush them.',
        'Provide specific questions: "Is my summary compelling?" rather than "Is it good?"',
        'Return the favor — offer to review their resume in exchange.',
      ],
      expectedOutcome: 'Objective external feedback with actionable improvements from 2 reviewers.',
    },
  ],
  'resume-ats': [
    {
      id: 'ats-keyword-optimize',
      title: 'Optimize Resume for ATS Keywords',
      objective: 'Increase your resume pass rate through automated screening.',
      instructions: [
        'Copy 5 target job descriptions into a keyword analysis tool or document.',
        'Extract the top 20 recurring keywords and phrases.',
        'Incorporate these keywords naturally into your resume content.',
        'Verify keywords appear in context, not in a dense list.',
      ],
      completionCriteria: [
        '20 keywords extracted from job postings',
        'Keywords integrated into resume sections',
        'No keyword stuffing — each appears naturally',
      ],
      estimatedMinutes: 20,
      difficulty: 3,
      tips: [
        'Focus on hard skills and specific tools (e.g., "React," "AWS," "Agile").',
        'Include both acronyms and full terms (e.g., "CI/CD" and "Continuous Integration").',
        'Match the exact phrasing from job descriptions — ATS looks for exact matches.',
      ],
      expectedOutcome: 'An ATS-optimized resume with relevant keywords that match target job descriptions.',
    },
    {
      id: 'ats-test-parse',
      title: 'Test Resume ATS Parsing',
      objective: 'Verify your resume is correctly parsed by automated systems.',
      instructions: [
        'Upload your resume to a free ATS parser testing tool.',
        'Review the parsed output: name, contact, experience, education, skills.',
        'Fix any parsing errors: adjust formatting where data is misread.',
        'Re-test until the parser extracts all information correctly.',
      ],
      completionCriteria: [
        'ATS parser correctly extracts name and contact info',
        'Experience section parsed with correct dates and companies',
        'Skills section recognized and extracted',
        'No data loss or misattribution in parsing',
      ],
      estimatedMinutes: 15,
      difficulty: 2,
      tips: [
        'Many ATS cannot read headers/footers — put contact info in the main body.',
        'Use standard date formats like "Jan 2022" or "2022-01."',
        'Avoid images, icons, or graphics in contact info sections.',
      ],
      expectedOutcome: 'A resume that passes automated parsing checks with no data loss.',
    },
    {
      id: 'ats-tailor-before-submit',
      title: 'Tailor Resume for One Target Job',
      objective: 'Practice customizing your resume for a specific job posting.',
      instructions: [
        'Select one job posting you plan to apply for.',
        'Map the top 5 requirements from the posting to your experience.',
        'Reorder your bullet points to emphasize matching experience.',
        'Add any missing relevant keywords from the posting.',
      ],
      completionCriteria: [
        '5 job requirements mapped to resume content',
        'Bullet points reordered by relevance',
        'Job-specific keywords added',
      ],
      estimatedMinutes: 15,
      difficulty: 3,
      tips: [
        'Keep a "master resume" with all content and create copies for tailoring.',
        'Do not lie — rephrase existing experience to highlight relevant aspects.',
        'Save tailored versions with the job title in the filename.',
      ],
      expectedOutcome: 'A job-specific version of your resume ready for a targeted application.',
    },
  ],
  'resume-summary': [
    {
      id: 'rs-write-summary',
      title: 'Write a Compelling Professional Summary',
      objective: 'Craft a 2-3 sentence summary that hooks the reader.',
      instructions: [
        'Write your current title and years of experience.',
        'Add your primary expertise and key differentiator.',
        'State your career goal and what you bring to a new role.',
        'Ensure the summary is specific — avoid generic phrases.',
      ],
      completionCriteria: [
        'Summary includes title, experience, and expertise',
        'No clichés ("results-oriented," "team player")',
        'Summary is 2-3 sentences and under 50 words',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Lead with your strongest qualification.',
        'Tailor the summary for each target role.',
        'Read it as a recruiter — does it make you want to read more?',
      ],
      expectedOutcome: 'A powerful professional summary that opens your resume with impact.',
    },
    {
      id: 'rs-review-examples',
      title: 'Review Strong Professional Summaries',
      objective: 'Learn from well-crafted summaries in your industry.',
      instructions: [
        'Find 5 LinkedIn profiles of professionals in your target role.',
        'Copy their summary sections into a document.',
        'Identify patterns: how do they open? What keywords do they use?',
        'Rewrite your summary incorporating the best patterns you observed.',
      ],
      completionCriteria: [
        '5 professional summaries reviewed',
        'Patterns and keywords documented',
        'Personal summary rewritten with insights',
      ],
      estimatedMinutes: 10,
      difficulty: 2,
      tips: [
        'Look at profiles with "Open to Work" and recent job changes.',
        'Note how they quantify experience ("10+ years," "led teams of 5").',
        'Pay attention to tone — confident without being arrogant.',
      ],
      expectedOutcome: 'A refined professional summary that incorporates industry best practices.',
    },
  ],
  'resume-skills': [
    {
      id: 'sk-inventory',
      title: 'Create a Complete Skills Inventory',
      objective: 'Document all your technical and professional skills.',
      instructions: [
        'List all technical skills: programming languages, frameworks, tools, platforms.',
        'List all professional skills: leadership, communication, project management.',
        'Rate your proficiency for each skill: beginner, intermediate, advanced, expert.',
        'Highlight skills most relevant to your target role.',
      ],
      completionCriteria: [
        '15+ technical and professional skills documented',
        'Each skill has a proficiency rating',
        'Top 5 skills highlighted for target role',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Include skills from all sources: work, education, side projects, volunteering.',
        'Be honest about proficiency — exaggerating leads to interview discomfort.',
        'Group skills by category for better resume organization.',
      ],
      expectedOutcome: 'A complete skills inventory ready for resume, LinkedIn, and interview preparation.',
    },
    {
      id: 'sk-categorize',
      title: 'Categorize and Prioritize Skills',
      objective: 'Organize your skills for maximum resume impact.',
      instructions: [
        'Group your skills into categories: Technical, Tools, Language, Soft Skills.',
        'Within each category, order by relevance to your target role.',
        'Select the top 10-15 skills to feature on your resume.',
        'Remove outdated or irrelevant skills from your active resume.',
      ],
      completionCriteria: [
        'Skills grouped into 3-5 categories',
        'Top 10-15 skills selected for resume',
        'Outdated skills removed from main resume',
      ],
      estimatedMinutes: 10,
      difficulty: 1,
      tips: [
        'Frontend, Backend, Database, DevOps are good technical categories.',
        'Keep a full list in your master resume — only show relevant ones.',
        'If a skill is outdated for your level, remove it (e.g., jQuery for a senior role).',
      ],
      expectedOutcome: 'A curated skills section optimized for your target role and industry.',
    },
  ],
};
