import type { PlaybookEntry } from '@/core/playbook/playbook_model';

export const CYBERSECURITY_PLAYBOOK: PlaybookEntry[] = [
  {
    id: 'cyber-pb-linux-commands',
    title: 'Linux Forensics Commands',
    category: 'technical',
    content: [
      'ps aux | grep suspicious_process',
      'netstat -tulpn | grep LISTEN',
      'lsof -i :port',
      'find / -perm -4000 -type f 2>/dev/null (SUID binaries)',
      'cat /var/log/auth.log | grep "Failed password"',
      'last -f /var/log/wtmp',
      'crontab -l && cat /etc/crontab',
      'ss -tulpn (modern replacement for netstat)',
    ],
    tags: ['linux', 'forensics', 'interview'],
  },
  {
    id: 'cyber-pb-siem-queries',
    title: 'SIEM Detection Queries',
    category: 'technical',
    content: [
      'Brute force: index=windows EventCode=4625 | stats count by src_ip | where count > 5',
      'Malware beacon: index=proxy | stats dc(dest_ip) by src_ip | where dc(dest_ip) < 5',
      'Privilege escalation: index=windows EventCode=4673 OR EventCode=4674',
      'Lateral movement: index=windows EventCode=4624 LogonType=3 | stats count by src_ip, dest_computer',
      'Data exfiltration: index=firewall dest_port=443 | stats sum(bytes_out) by src_ip | where sum > 1GB',
      'PowerShell execution: index=windows EventCode=4104 | stats count by script_block_id',
    ],
    tags: ['siem', 'splunk', 'detection', 'interview'],
  },
  {
    id: 'cyber-pb-ir-checklist',
    title: 'Incident Response Checklist',
    category: 'technical',
    content: [
      '1. Preparation: IR plan, contact list, tools ready',
      '2. Detection: alert triage, scope assessment',
      '3. Containment: short-term (isolate) and long-term (segment)',
      '4. Eradication: remove malware, close vulnerabilities',
      '5. Recovery: restore from backups, monitor for reinfection',
      '6. Lessons Learned: document, update playbooks, train team',
    ],
    tags: ['incident-response', 'ir', 'checklist'],
  },
  {
    id: 'cyber-pb-mitre-attack',
    title: 'MITRE ATT&CK Quick Reference',
    category: 'technical',
    content: [
      'Initial Access: T1566 (Phishing), T1190 (Exploit Public-Facing App)',
      'Execution: T1059 (Command and Scripting Interpreter)',
      'Persistence: T1053 (Scheduled Task), T1547 (Registry Run Keys)',
      'Privilege Escalation: T1078 (Valid Accounts), T1055 (Process Injection)',
      'Defense Evasion: T1070 (Indicator Removal), T1055 (Process Injection)',
      'Credential Access: T1003 (OS Credential Dumping), T1558 (Steal Kerberos Ticket)',
      'Lateral Movement: T1021 (Remote Services), T1077 (Windows Admin Shares)',
      'Exfiltration: T1041 (Exfiltration Over C2), T1567 (Exfiltration Over Web Service)',
    ],
    tags: ['mitre', 'att&ck', 'threat-intel'],
  },
  {
    id: 'cyber-pb-clearance-guide',
    title: 'Security Clearance Guide',
    category: 'career',
    content: [
      'Levels: Secret, Top Secret (TS), TS/SCI, TS/SCI with polygraph',
      'Process: SF-86 → investigation → adjudication → issuance',
      'Timeline: Secret 3-6 months, TS 6-18 months, TS/SCI 12-24 months',
      'Adjudication criteria: foreign influence, financial responsibility, criminal conduct, personal conduct, psychological conditions, drug involvement, alcohol consumption, outside activities',
      'Tips: be honest, disclose everything, maintain good credit, limit foreign travel',
    ],
    tags: ['clearance', 'career', 'government'],
  },
  {
    id: 'cyber-pb-ctf-resources',
    title: 'CTF & Lab Resources',
    category: 'technical',
    content: [
      'TryHackMe: beginner-friendly, guided rooms',
      'HackTheBox: realistic machines, retired boxes with writeups',
      'VulnHub: downloadable vulnerable machines',
      'Blue Team Labs Online: defensive challenges',
      'PentesterLab: web application security',
      'OverTheWire: Linux and security wargames',
    ],
    tags: ['ctf', 'lab', 'practice', 'learning'],
  },
];