import type { TaskContent } from '@/core/task_content';

export const LINKEDIN_TASKS: Record<string, TaskContent[]> = {
  'headline-authority': [
    {
      id: 'da-ha-headlines',
      title: 'Write 3 Data Analyst Headlines',
      objective: 'Create keyword-rich headlines that appear in recruiter searches.',
      instructions: [
        'Search "Data Analyst" on LinkedIn. Note the top 10 headlines.',
        'Write 3 headlines combining: role + tools + value proposition.',
        'Option 1: Role-focused: "Data Analyst | SQL & Tableau | E-commerce"',
        'Option 2: Problem-focused: "Turning raw data into revenue insights"',
        'Option 3: Hybrid: "Data Analyst | SQL, Python, Power BI | 3 years driving growth"',
      ],
      completionCriteria: [
        '3 headlines written',
        'Each includes "Data Analyst" and at least 2 tools',
        'Each is under 220 characters',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Recruiters search by keywords. "SQL" and "Tableau" must appear.',
        'Avoid buzzwords: guru, ninja, rockstar, passionate.',
        'Test by searching yourself: does your profile appear?',
      ],
      expectedOutcome: '3 headline options ready for A/B testing and final selection.',
    },
    {
      id: 'da-ha-optimize',
      title: 'Optimize Your Headline for Search',
      objective: 'Ensure recruiters find you when searching for data analysts.',
      instructions: [
        'Use LinkedIn Recruiter Lite (free trial) or ask a recruiter friend to search for you.',
        'Search: "Data Analyst SQL [your city]". Do you appear in top 20?',
        'If not, add missing keywords to your headline.',
        'Update headline and wait 24 hours. Search again.',
      ],
      completionCriteria: [
        'Search performed with specific keywords',
        'Profile appears in top 20 results',
        'Headline updated with missing keywords',
      ],
      estimatedMinutes: 20,
      difficulty: 2,
      tips: [
        'Location matters. Add your city if targeting local roles.',
        'Tool names are the most searched keywords.',
        'Refresh your headline monthly to stay in search results.',
      ],
      expectedOutcome: 'A headline that puts you in recruiter search results daily.',
    },
  ],
  'about-section': [
    {
      id: 'da-as-story',
      title: 'Write Your Data Story',
      objective: 'Create a compelling About section that shows your analyst journey.',
      instructions: [
        'Write 200 words in 3 paragraphs: Who I am, What I do, What I want.',
        'Paragraph 1: Your background and what led you to data analytics.',
        'Paragraph 2: Your tools, specialties, and one standout project with metric.',
        'Paragraph 3: What role you are seeking and what value you bring.',
      ],
      completionCriteria: [
        '200 words, 3 paragraphs',
        'One standout project with metric',
        'Clear statement of target role',
      ],
      estimatedMinutes: 25,
      difficulty: 2,
      tips: [
        'Start with a hook: "I discovered the power of data when..."',
        'Include specific tools: SQL, Excel, Tableau, Python.',
        'End with a call to action: "Open to Data Analyst roles in fintech."',
      ],
      expectedOutcome: 'An About section that turns profile views into connection requests.',
    },
    {
      id: 'da-as-keywords',
      title: 'Keyword-Optimize Your About',
      objective: 'Ensure your About section contains searchable data analyst keywords.',
      instructions: [
        'List 15 keywords from 5 data analyst job postings.',
        'Check if each keyword appears in your About section.',
        'Add missing keywords naturally into your narrative.',
        'Ensure "Data Analyst", "SQL", and one BI tool appear in first 2 lines.',
      ],
      completionCriteria: [
        '15 keywords identified from job postings',
        'All 15 appear in About section',
        'Top 3 keywords in first 2 lines',
      ],
      estimatedMinutes: 20,
      difficulty: 1,
      tips: [
        'Keywords in the first 2 lines carry more weight in search.',
        'Do not keyword-stuff. Integrate naturally into sentences.',
        'Update monthly as job market trends change.',
      ],
      expectedOutcome: 'An About section that ranks in LinkedIn recruiter searches.',
    },
  ],
  'network-connections': [
    {
      id: 'da-nc-connect',
      title: 'Build Your Data Network',
      objective: 'Connect with 15 data professionals this week.',
      instructions: [
        'Search "Data Analyst" on LinkedIn. Filter by 2nd degree connections.',
        'Send 5 personalized connection requests to data analysts.',
        'Send 5 to data hiring managers.',
        'Send 5 to recruiters specializing in data roles.',
      ],
      completionCriteria: [
        '15 personalized connection requests sent',
        '5 to analysts, 5 to managers, 5 to recruiters',
        'Each request mentions a specific reason for connecting',
      ],
      estimatedMinutes: 30,
      difficulty: 1,
      tips: [
        'Personalize every request: "I enjoyed your post on SQL optimization."',
        'Do not use the default "I would like to add you to my network."',
        'Follow up with a thank-you message when accepted.',
      ],
      expectedOutcome: 'A growing network of data professionals who can refer and advise you.',
    },
    {
      id: 'da-nc-engage',
      title: 'Engage With Data Content',
      objective: 'Increase visibility by engaging with data community posts.',
      instructions: [
        'Follow 5 data influencers: analysts, hiring managers, data science leaders.',
        'Comment thoughtfully on 3 posts this week.',
        'Share one data insight or project update.',
        'Tag relevant people when appropriate.',
      ],
      completionCriteria: [
        '5 data influencers followed',
        '3 meaningful comments posted',
        '1 original post or project share',
      ],
      estimatedMinutes: 20,
      difficulty: 1,
      tips: [
        'Comments should add value, not just "Great post!"',
        'Share your project learnings: "I learned this SQL trick while building X..."',
        'Consistency beats intensity. 10 minutes daily > 2 hours once.',
      ],
      expectedOutcome: 'Visible engagement that puts you on recruiters radar.',
    },
  ],
  'linkedin-optimization': [
    {
      id: 'da-lo-complete',
      title: 'Complete Your LinkedIn Profile',
      objective: 'Achieve 90%+ profile completeness for better search ranking.',
      instructions: [
        'Check your profile completeness score on LinkedIn.',
        'Fill missing sections: Headline, About, Experience, Education, Skills, Photo.',
        'Add 5 relevant skills: SQL, Excel, Tableau, Data Analysis, Python.',
        'Request endorsements for your top 3 skills.',
      ],
      completionCriteria: [
        'Profile completeness 90%+',
        'All required sections filled',
        '5 relevant skills added',
        '3 endorsements requested',
      ],
      estimatedMinutes: 25,
      difficulty: 1,
      tips: [
        'A complete profile ranks higher in search results.',
        'Endorsements from colleagues carry more weight than from strangers.',
        'Update your status weekly to stay active in feeds.',
      ],
      expectedOutcome: 'A complete, search-optimized LinkedIn profile.',
    },
    {
      id: 'da-lo-featured',
      title: 'Add Featured Content',
      objective: 'Showcase your best data work in the Featured section.',
      instructions: [
        'Select your best project: dashboard, SQL query, or analysis write-up.',
        'Create a post or article highlighting the problem, approach, and insight.',
        'Add the project link to your Featured section.',
        'Include a screenshot of your best visualization.',
      ],
      completionCriteria: [
        '1 project featured with link',
        'Screenshot of visualization included',
        'Clear title and description for each featured item',
      ],
      estimatedMinutes: 20,
      difficulty: 2,
      tips: [
        'Featured content is prime real estate. Update quarterly.',
        'Use Tableau Public, GitHub, or Medium for hosting.',
        'Ensure links work and load fast on mobile.',
      ],
      expectedOutcome: 'Featured content that proves your skills in one click.',
    },
  ],
  'profile-photo': [
    {
      id: 'da-pp-photo',
      title: 'Take a Professional Headshot',
      objective: 'Create a trustworthy first impression with your LinkedIn photo.',
      instructions: [
        'Find a plain wall or neutral background.',
        'Dress business casual: collared shirt or blouse.',
        'Use portrait mode on your phone. Face should be 60% of frame.',
        'Smile naturally. Look at camera. No sunglasses or hats.',
      ],
      completionCriteria: [
        'Photo taken against neutral background',
        'Face is 60% of frame',
        'Business casual attire',
        'Natural smile, eye contact',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Natural light near a window works better than artificial light.',
        'Ask a friend to take it. Selfies rarely look professional.',
        'Your photo should look like you on interview day.',
      ],
      expectedOutcome: 'A professional photo that builds trust before anyone reads your SQL skills.',
    },
    {
      id: 'da-pp-banner',
      title: 'Design a LinkedIn Banner',
      objective: 'Create a banner that reinforces your data analyst brand.',
      instructions: [
        'Use Canva or similar tool. Size: 1584 x 396 pixels.',
        'Include: your role ("Data Analyst"), top tools (SQL, Tableau), and a visual element.',
        'Keep text minimal and readable on mobile.',
        'Ensure colors match your personal brand.',
      ],
      completionCriteria: [
        'Banner created at correct dimensions',
        'Role and tools visible',
        'Mobile-readable text',
        'Consistent with personal brand colors',
      ],
      estimatedMinutes: 20,
      difficulty: 1,
      tips: [
        'A banner makes your profile look complete and intentional.',
        'Avoid cluttered designs. Less is more.',
        'Update banner when you learn new tools or change focus.',
      ],
      expectedOutcome: 'A banner that reinforces your data analyst identity at a glance.',
    },
  ],
  'featured-content': [
    {
      id: 'da-fc-dashboard',
      title: 'Feature a Dashboard',
      objective: 'Showcase your visualization skills in the Featured section.',
      instructions: [
        'Pick your best Tableau, Power BI, or Excel dashboard.',
        'Take a high-resolution screenshot.',
        'Write a 2-sentence description: problem, tools, insight.',
        'Link to the live dashboard or GitHub repository.',
      ],
      completionCriteria: [
        'Dashboard screenshot uploaded',
        '2-sentence description written',
        'Public link provided and tested',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Interactive dashboards beat static images. Use Tableau Public.',
        'Describe the business question, not just the chart type.',
        'Update Featured quarterly with new projects.',
      ],
      expectedOutcome: 'A featured dashboard that proves your visualization skills instantly.',
    },
    {
      id: 'da-fc-article',
      title: 'Write a Data Article',
      objective: 'Establish thought leadership with a short data analysis article.',
      instructions: [
        'Pick a topic you analyzed recently: customer churn, sales trends, etc.',
        'Write 500 words: Problem, Data, Method, Insight, Recommendation.',
        'Include 1-2 visualizations.',
        'Publish on LinkedIn Articles or Medium.',
      ],
      completionCriteria: [
        '500-word article written',
        '1-2 visualizations included',
        'Published on LinkedIn or Medium',
        'Link added to Featured section',
      ],
      estimatedMinutes: 45,
      difficulty: 3,
      tips: [
        'Articles show you can communicate insights, not just crunch numbers.',
        'Pick a topic relevant to your target industry.',
        'Share the article in data groups for extra visibility.',
      ],
      expectedOutcome: 'A published article that positions you as a thinking analyst, not just a tool user.',
    },
  ],
  'recommendations': [
    {
      id: 'da-rec-request',
      title: 'Request Recommendations',
      objective: 'Get 3 specific recommendations that mention your data skills.',
      instructions: [
        'List 5 people who have seen your data work: managers, colleagues, clients.',
        'Draft a template request mentioning specific projects.',
        'Send personalized requests to 3 people.',
        'Offer to write a reciprocal recommendation.',
      ],
      completionCriteria: [
        '3 personalized requests sent',
        'Each mentions a specific project or skill',
        'Reciprocal offer included',
      ],
      estimatedMinutes: 20,
      difficulty: 1,
      tips: [
        'Give before you ask. Write recommendations for others first.',
        'Provide a draft: "Would you feel comfortable saying X about my SQL work?"',
        'Specific recommendations beat generic praise.',
      ],
      expectedOutcome: 'Social proof that validates your data analyst capabilities.',
    },
    {
      id: 'da-rec-specific',
      title: 'Make Recommendations Specific',
      objective: 'Ensure your recommendations contain data-specific details.',
      instructions: [
        'Review existing recommendations. Are they generic?',
        'Ask recommenders to mention: specific tools, projects, outcomes.',
        'Example: "Her SQL queries reduced our reporting time by 5 hours weekly."',
        'Update recommendations that lack specificity.',
      ],
      completionCriteria: [
        'All recommendations mention specific tools or projects',
        'At least one includes a metric or outcome',
        'Recommendations updated if needed',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'A recommendation with metrics is worth 5 generic ones.',
        'Help your recommender by providing bullet points they can use.',
        'Recommendations from data managers carry more weight than peers.',
      ],
      expectedOutcome: 'Recommendations that reduce hiring manager risk perception.',
    },
  ],
};
