import type { TaskContent } from '@/core/task_content';

export const RESUME_TASKS: Record<string, TaskContent[]> = {
  'positioning-clarity': [
    {
      id: 'da-pc-write-target',
      title: 'Define Your Data Analyst Positioning',
      objective: 'Create a clear positioning statement for your data analyst job search.',
      instructions: [
        'Open 5 current Data Analyst job postings on LinkedIn or Indeed.',
        'Identify common requirements: SQL, Excel, Tableau, Python, statistics.',
        'Write one sentence: "Data Analyst specializing in [tools] for [industry]."',
        'List 3 dream companies that hire data analysts in your target industry.',
      ],
      completionCriteria: [
        'Positioning statement is under 20 words',
        'At least 3 tools mentioned (SQL required)',
        '3 target companies identified',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Avoid generic titles like "Data Professional" — be specific.',
        'Check LinkedIn profiles of data analysts at your target companies.',
        'Industry matters: healthcare analytics differs from fintech analytics.',
      ],
      expectedOutcome: 'A clear positioning statement that guides your resume, LinkedIn, and interview prep.',
    },
    {
      id: 'da-pc-research-market',
      title: 'Research Data Analyst Market',
      objective: 'Understand the current data analyst job market in your region.',
      instructions: [
        'Search "Data Analyst" on 3 job boards: LinkedIn, Indeed, Glassdoor.',
        'Filter by your location and experience level (Junior/Mid).',
        'Note the top 5 required skills across postings.',
        'Identify salary ranges for your level using Glassdoor or Levels.fyi.',
      ],
      completionCriteria: [
        '5 job postings analyzed',
        'Top 5 skills documented',
        'Salary range identified for your level',
      ],
      estimatedMinutes: 20,
      difficulty: 1,
      tips: [
        'Look for SQL, Excel, and visualization tools in every posting.',
        'Note which companies mention "Python" vs "R" — this signals tech stack.',
        'Save postings that match your positioning for later tailoring.',
      ],
      expectedOutcome: 'Market intelligence that shapes your skill development and application strategy.',
    },
  ],
  'data-storytelling': [
    {
      id: 'da-ds-metrics-bullets',
      title: 'Add Metrics to Your Resume',
      objective: 'Transform tool-focused bullets into impact-focused bullets.',
      instructions: [
        'Open your current resume and find 5 bullets that list tools.',
        'Rewrite each bullet to include a metric: percentage, dollar amount, or time saved.',
        'Example: "Used SQL" → "Used SQL to reduce reporting time by 40%".',
        'Ensure every project has at least one quantified outcome.',
      ],
      completionCriteria: [
        '5 bullets rewritten with metrics',
        'Each bullet follows Action-Metric-Outcome format',
        'At least one dollar amount or percentage in each',
      ],
      estimatedMinutes: 25,
      difficulty: 2,
      tips: [
        'If you lack real metrics, estimate conservatively: "Improved efficiency by ~20%".',
        'Use strong verbs: reduced, increased, optimized, streamlined, automated.',
        'Metrics make abstract skills concrete for recruiters.',
      ],
      expectedOutcome: 'A resume that proves business impact, not just tool familiarity.',
    },
    {
      id: 'da-ds-impact-framework',
      title: 'Build an Impact Framework',
      objective: 'Create a reusable framework for describing any data project with impact.',
      instructions: [
        'Write down the formula: Problem → Data → Analysis → Insight → Action → Result.',
        'Pick one past project. Map it to the framework.',
        'Write a 2-sentence version for your resume.',
        'Write a 2-minute version for interviews.',
      ],
      completionCriteria: [
        'Framework documented on paper or digital',
        'One project mapped to all 6 steps',
        'Resume version under 2 sentences',
        'Interview version under 2 minutes spoken',
      ],
      estimatedMinutes: 20,
      difficulty: 2,
      tips: [
        'Practice the 2-minute version aloud. Time yourself.',
        'The result should be a number whenever possible.',
        'This framework works for interviews, resumes, and LinkedIn posts.',
      ],
      expectedOutcome: 'A storytelling system that turns any project into a compelling narrative.',
    },
  ],
  'resume-structure': [
    {
      id: 'da-rs-sections-order',
      title: 'Optimize Resume Sections',
      objective: 'Reorder and structure your resume for maximum recruiter impact.',
      instructions: [
        'List all sections: Header, Summary, Skills, Experience, Projects, Education, Certifications.',
        'If you have < 2 years experience: put Projects before Experience.',
        'If you have 2+ years: put Experience first, then Projects.',
        'Ensure each section has a clear heading and consistent formatting.',
      ],
      completionCriteria: [
        'Section order optimized for experience level',
        'Consistent formatting across all sections',
        'Most relevant information in top third of page',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Recruiters scan top third first. Put your strongest content there.',
        'Use the same date format everywhere: Jan 2024 – Mar 2025.',
        'One page for junior, two pages max for senior.',
      ],
      expectedOutcome: 'A resume structure that guides recruiters to your best content in 6 seconds.',
    },
    {
      id: 'da-rs-formatting',
      title: 'Fix Formatting Consistency',
      objective: 'Eliminate formatting inconsistencies that signal carelessness.',
      instructions: [
        'Check font: same family and size throughout (10-12pt).',
        'Check spacing: equal margins, consistent line spacing.',
        'Check bullets: all start with verbs, same tense (past or present).',
        'Check alignment: dates aligned right, everything else left.',
      ],
      completionCriteria: [
        'Single font family used throughout',
        'Consistent margins and spacing',
        'All bullets start with action verbs',
        'Dates aligned uniformly',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Paste into a plain text editor. If it looks broken, ATS will struggle.',
        'Bold section headers. Use italics sparingly.',
        'PDF format only. Never send .docx unless requested.',
      ],
      expectedOutcome: 'A polished resume that signals professionalism before anyone reads a word.',
    },
  ],
  'resume-ats': [
    {
      id: 'da-ats-keywords',
      title: 'ATS Keyword Optimization',
      objective: 'Ensure your resume passes automated screening for data analyst roles.',
      instructions: [
        'Paste your resume and a job posting into a word cloud tool.',
        'Identify missing keywords from the posting.',
        'Add missing keywords naturally into your Skills and Experience sections.',
        'Replace creative headings with standard ones: Skills, Experience, Education.',
      ],
      completionCriteria: [
        'Top 10 keywords from job posting appear in resume',
        'Standard section headings used',
        'No tables, images, or unusual fonts',
      ],
      estimatedMinutes: 20,
      difficulty: 2,
      tips: [
        'Use exact phrases: "data visualization" not "making charts".',
        'Include tool names: SQL, Excel, Tableau, Power BI, Python, R.',
        'Avoid headers in images or text boxes — ATS cannot read them.',
      ],
      expectedOutcome: 'An ATS-optimized resume that reaches human recruiters consistently.',
    },
    {
      id: 'da-ats-test',
      title: 'Test Your Resume in ATS',
      objective: 'Verify your resume parses correctly in applicant tracking systems.',
      instructions: [
        'Copy your resume text and paste it into a plain text editor.',
        'Check if all content appears in correct order.',
        'Use a free ATS scanner (Jobscan, Resume Worded) to get a match score.',
        'Fix any sections that appear out of order or missing.',
      ],
      completionCriteria: [
        'Resume renders correctly in plain text',
        'ATS match score above 75%',
        'All sections appear in logical order',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'If plain text is garbled, simplify formatting.',
        'Some ATS cannot parse columns. Use single-column layout.',
        'Test with multiple scanners for best results.',
      ],
      expectedOutcome: 'Confidence that your resume will not be rejected by a machine.',
    },
  ],
  'technical-skills': [
    {
      id: 'da-ts-categorize',
      title: 'Categorize Your Technical Skills',
      objective: 'Organize your skills into clear categories for recruiters.',
      instructions: [
        'List every tool you know: SQL, Excel, Tableau, Python, R, Power BI, etc.',
        'Group into categories: Query, Visualization, Analysis, Database, Other.',
        'Rate each skill: Beginner, Intermediate, Advanced.',
        'Remove outdated or irrelevant tools.',
      ],
      completionCriteria: [
        'Skills grouped into 3-5 categories',
        'Each skill has a proficiency level',
        'Outdated tools removed',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'Be honest about proficiency. "Advanced SQL" means window functions and CTEs.',
        'Include versions if relevant: Excel 2019, PostgreSQL 14.',
        'Do not list tools you only watched a tutorial on.',
      ],
      expectedOutcome: 'A skills section that instantly communicates your data analyst toolkit.',
    },
    {
      id: 'da-ts-evidence',
      title: 'Add Evidence to Skills',
      objective: 'Prove your skills with projects, not just labels.',
      instructions: [
        'Pick your top 3 skills (e.g., SQL, Tableau, Excel).',
        'For each, write one bullet from a project that demonstrates it.',
        'Example: "Advanced SQL" → "Built a 5-table JOIN query reducing report time by 3 hours".',
        'Add these bullets under Projects or Experience.',
      ],
      completionCriteria: [
        'Top 3 skills have evidence bullets',
        'Each bullet includes a specific project and outcome',
        'Evidence appears in resume body, not just skills list',
      ],
      estimatedMinutes: 20,
      difficulty: 2,
      tips: [
        'Evidence beats claims every time.',
        'If you lack work experience, use academic or personal projects.',
        'GitHub links add credibility to technical skills.',
      ],
      expectedOutcome: 'A resume where every skill claim is backed by proof.',
    },
  ],
  'projects-portfolio': [
    {
      id: 'da-pp-select-project',
      title: 'Select Your Best Data Project',
      objective: 'Choose one project that showcases your full data analyst skill set.',
      instructions: [
        'List 3 projects you have worked on (work, academic, or personal).',
        'Score each on: SQL complexity, visualization quality, business impact, storytelling.',
        'Pick the highest-scoring project.',
        'Ensure you have access to the data and can explain every step.',
      ],
      completionCriteria: [
        '3 projects scored and ranked',
        'Top project selected with justification',
        'Access to data and code confirmed',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'A simple project you fully understand beats a complex one you barely remember.',
        'Real business data is better than Kaggle datasets.',
        'If using Kaggle, add unique analysis beyond the baseline.',
      ],
      expectedOutcome: 'One flagship project that represents your best work.',
    },
    {
      id: 'da-pp-document',
      title: 'Document Your Project',
      objective: 'Create a professional project write-up for your portfolio.',
      instructions: [
        'Write 300 words: Problem, Dataset, Tools, Analysis, Insights, Impact.',
        'Include 2-3 screenshots of visualizations.',
        'Add a link to your code (GitHub) or dashboard (Tableau Public).',
        'Ensure everything loads fast and works on mobile.',
      ],
      completionCriteria: [
        '300-word write-up complete',
        '2-3 visualization screenshots included',
        'Public link to code or dashboard provided',
        'Mobile-friendly and fast-loading',
      ],
      estimatedMinutes: 30,
      difficulty: 2,
      tips: [
        'Host on GitHub with a detailed README.',
        'Tableau Public is free and impressive for dashboards.',
        'Test your link on a phone before sharing.',
      ],
      expectedOutcome: 'A portfolio piece that proves your end-to-end data analyst capabilities.',
    },
  ],
  'resume-summary': [
    {
      id: 'da-rs-write-summary',
      title: 'Write Your Data Analyst Summary',
      objective: 'Craft a 2-3 line summary that hooks recruiters instantly.',
      instructions: [
        'Study 5 data analyst LinkedIn summaries for inspiration.',
        'Write: "Data Analyst with [X] years using [tools] to drive [business outcome]."',
        'Include one metric or achievement.',
        'Remove filler words: passionate, hardworking, motivated, driven.',
      ],
      completionCriteria: [
        'Summary is 2-3 lines (under 50 words)',
        'Contains role, tools, and business outcome',
        'One metric included',
        'No filler words',
      ],
      estimatedMinutes: 15,
      difficulty: 1,
      tips: [
        'The first 6 words matter most. Lead with impact.',
        '"SQL and Tableau expert who reduced churn by 12%" beats "Passionate data analyst".',
        'Tailor the summary to each job posting by swapping keywords.',
      ],
      expectedOutcome: 'A summary that answers "Why hire this analyst?" in 3 seconds.',
    },
    {
      id: 'da-rs-test-summary',
      title: 'Test Your Summary',
      objective: 'Validate your summary with real feedback.',
      instructions: [
        'Show your summary to 3 people: a recruiter, a data analyst, and a non-technical friend.',
        'Ask: "What role am I applying for?" and "What is my top skill?"',
        'If anyone is unsure, rewrite for clarity.',
        'Time how long it takes them to answer — should be under 3 seconds.',
      ],
      completionCriteria: [
        '3 people reviewed the summary',
        'All correctly identified role and top skill',
        'Feedback incorporated into final version',
      ],
      estimatedMinutes: 20,
      difficulty: 1,
      tips: [
        'Non-technical friends are great clarity testers.',
        'If they do not understand, a recruiter will not either.',
        'Iterate until the message is unmistakable.',
      ],
      expectedOutcome: 'A recruiter-tested summary that communicates value instantly.',
    },
  ],
};
