import type { Chapter } from '@/core/chapter_model';

export const PRODUCT_MANAGER_CHAPTERS: Chapter[] = [
  {
    id: 'resume',
    title: 'Resume',
    description: 'Build a PM resume that proves product thinking, ownership, and measurable impact.',
    nodeIds: [
      'positioning-clarity',
      'pm-impact-bullets',
      'resume-structure',
      'resume-ats',
      'product-portfolio',
      'metrics-ownership',
      'resume-summary',
    ],
    artFilename: 'island-resume.png',
  },
  {
    id: 'linkedin',
    title: 'LinkedIn',
    description: 'Create a profile that attracts PM recruiters and product hiring managers.',
    nodeIds: [
      'headline-authority',
      'about-section',
      'network-connections',
      'linkedin-optimization',
      'profile-photo',
      'featured-content',
      'recommendations',
    ],
    artFilename: 'island-linkedin.png',
  },
  {
    id: 'applications',
    title: 'Applications',
    description: 'Apply strategically to PM roles that match your product domain and experience.',
    nodeIds: [
      'application-tracking',
      'cover-letter',
      'follow-up-strategy',
      'application-volume',
      'company-research',
      'application-tailoring',
      'portfolio-submission',
      'referral-strategy',
    ],
    artFilename: 'island-applications.png',
  },
  {
    id: 'interviews',
    title: 'Interviews',
    description: 'Ace product sense, estimation, behavioral, and technical PM interview rounds.',
    nodeIds: [
      'interview-prep',
      'product-sense',
      'estimation-prep',
      'technical-fluency',
      'interview-mindset',
      'behavioral-prep',
      'metrics-interview',
      'on-site-prep',
      'phone-screen',
      'interview-followup',
    ],
    artFilename: 'island-interview.png',
  },
  {
    id: 'offer_preparation',
    title: 'Offer Preparation',
    description: 'Prepare for PM compensation conversations and evaluate total package.',
    nodeIds: ['salary-research', 'offer-review', 'resignation-letter'],
    artFilename: 'island-offer-preparation.png',
  },
  {
    id: 'offer',
    title: 'Offer',
    description: 'Negotiate and evaluate offers to maximize your PM career trajectory.',
    nodeIds: [
      'offer-evaluation',
      'salary-negotiation',
      'decision-framework',
      'offer-acceptance',
      'benefits-evaluation',
      'start-transition',
    ],
    artFilename: 'island-offer.png',
  },
];
