import type { SkillNode } from '@/core/skill_state';
import { RESUME_TASKS } from './tasks/resume';
import { LINKEDIN_TASKS } from './tasks/linkedin';
import { APPLICATION_TASKS } from './tasks/applications';
import { INTERVIEW_TASKS } from './tasks/interviews';
import { OFFER_TASKS } from './tasks/offer';

export const RESUME_SKILL_NODES: SkillNode[] = [
  {
    id: 'positioning-clarity',
    skill: 'Positioning Clarity',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 35,
    difficulty: 1,
    signals: [
      'You can describe your target PM role in one clear sentence',
      'Your positioning names product domain: B2B SaaS, consumer, platform, or growth',
      'You know whether you target large company, startup, or scale-up',
    ],
    advice: {
      awareness: 'A vague PM resume forces recruiters to guess your product domain and level.',
      understanding: 'PM roles differ radically: growth PM, platform PM, B2B PM require different signals.',
      application: 'Analyze 5 PM job postings. Identify the common domain, metrics, and stage.',
      readiness: 'You can state your target role, domain, and level in one sentence.',
      execution: 'Every resume section reinforces the same PM positioning.',
      confidence: 'Focused positioning answers "Can this person own our product area?" immediately.',
    },
    tasks: RESUME_TASKS['positioning-clarity'] || [],
  },
  {
    id: 'pm-impact-bullets',
    skill: 'Impact Bullets',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 2,
    signals: [
      'Every bullet shows ownership, action, and measurable outcome',
      'Metrics include DAU, retention, revenue, NPS, conversion, or time-to-market',
      'Bullets follow "Led X that resulted in Y" format',
    ],
    advice: {
      awareness: 'Listing responsibilities is not impact. Recruiters want outcomes you drove.',
      understanding: 'Strong PM bullets prove you can move product metrics, not just manage tasks.',
      application: 'Rewrite 5 resume bullets: add one metric and one business outcome each.',
      readiness: 'Every bullet on your resume has a number that proves product impact.',
      execution: 'Use: "Led [initiative] → achieved [metric] → enabling [business outcome]".',
      confidence: 'Impact bullets separate product owners from task coordinators.',
    },
    tasks: RESUME_TASKS['pm-impact-bullets'] || [],
  },
  {
    id: 'resume-structure',
    skill: 'Resume Structure',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'Your resume has clear sections: Summary, Experience, Skills, Education',
      'Product wins appear in the top third of the page',
      'Each role shows progression: scope, complexity, or ownership level',
    ],
    advice: {
      awareness: 'A poorly structured PM resume buries your biggest wins at the bottom.',
      understanding: 'Recruiters spend 6 seconds scanning. Structure controls what they see first.',
      application: 'Move your most impactful product metric to the first bullet of each role.',
      readiness: 'A recruiter can identify your product domain and top metric in 6 seconds.',
      execution: 'Use consistent formatting: same date format, same bullet style, same tense.',
      confidence: 'Clean structure signals organizational thinking before anyone reads a word.',
    },
    tasks: RESUME_TASKS['resume-structure'] || [],
  },
  {
    id: 'resume-ats',
    skill: 'ATS Optimization',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 35,
    difficulty: 2,
    signals: [
      'Your resume uses standard section headings ATS can parse',
      'PM keywords from job postings appear naturally in your text',
      'No tables, text boxes, or unusual fonts that confuse parsers',
    ],
    advice: {
      awareness: '70% of resumes are rejected by ATS before a human sees them.',
      understanding: 'PM ATS parsers look for: roadmap, stakeholders, OKRs, A/B testing, launch.',
      application: 'Paste your resume into plain text. If it looks broken, ATS will struggle.',
      readiness: 'Your resume passes ATS for "product roadmap", "OKR", "cross-functional", "launch".',
      execution: 'Use exact keywords from postings: "go-to-market strategy" not just "GTM".',
      confidence: 'An ATS-friendly resume reaches human PM recruiters consistently.',
    },
    tasks: RESUME_TASKS['resume-ats'] || [],
  },
  {
    id: 'product-portfolio',
    skill: 'Product Portfolio',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 60,
    difficulty: 3,
    signals: [
      'You have 2-3 case studies showing end-to-end product ownership',
      'Each case study has: problem, insight, decision, metric, and lesson',
      'Case studies are publicly shareable (Notion, portfolio site, or PDF)',
    ],
    advice: {
      awareness: 'Without case studies, PM candidates are indistinguishable from each other.',
      understanding: 'A case study proves you can discover, define, build, and measure product work.',
      application: 'Pick one product decision you made. Document: why, how, what happened, what you learned.',
      readiness: 'You can walk through a case study in 5 minutes: problem → decision → outcome.',
      execution: 'Structure each case: context, problem, options, decision rationale, result, retrospective.',
      confidence: 'A strong portfolio turns "tell me about yourself" into a structured product story.',
    },
    tasks: RESUME_TASKS['product-portfolio'] || [],
  },
  {
    id: 'metrics-ownership',
    skill: 'Metrics Ownership',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 40,
    difficulty: 2,
    signals: [
      'You can name the north star metric for each product you owned',
      'Your resume shows which metrics you owned vs influenced',
      'You understand funnel, engagement, retention, and revenue metrics',
    ],
    advice: {
      awareness: 'PMs who cannot name their metrics are not yet product owners.',
      understanding: 'Interviewers test metric fluency heavily. Every resume claim needs a number.',
      application: 'For each role, list the 3 metrics you were responsible for moving.',
      readiness: 'You can explain your metric choices and why they mattered to the business.',
      execution: 'Distinguish owned metrics (DAU, NPS) from influenced metrics (revenue, LTV).',
      confidence: 'Metric ownership signals PM maturity and accountability.',
    },
    tasks: RESUME_TASKS['metrics-ownership'] || [],
  },
  {
    id: 'resume-summary',
    skill: 'Resume Summary',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'Your summary names PM domain, one key metric, and your product philosophy',
      'It does not use buzzwords like "passionate" or "visionary"',
      'A recruiter understands your value in one glance',
    ],
    advice: {
      awareness: 'A generic PM summary wastes the most valuable space on your resume.',
      understanding: 'The summary is your positioning statement. It must answer "Why hire this PM?"',
      application: 'Write: "PM with X years growing [product type] by [metric] for [audience]."',
      readiness: 'Your summary contains role, domain, metric, and target — no filler words.',
      execution: 'Tailor the summary to each job posting by matching domain keywords.',
      confidence: 'A strong summary hooks recruiters in the first 3 seconds.',
    },
    tasks: RESUME_TASKS['resume-summary'] || [],
  },
];

export const LINKEDIN_SKILL_NODES: SkillNode[] = [
  {
    id: 'headline-authority',
    skill: 'Headline Authority',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'Your headline says "Product Manager" plus domain or company type',
      'It includes a product signal: growth, platform, B2B, consumer, or mobile',
      'It fits within LinkedIn 220 character limit',
    ],
    advice: {
      awareness: 'A vague headline makes you invisible to PM recruiters searching for "B2B SaaS PM".',
      understanding: 'Recruiters filter by keywords. Your headline is the top search field.',
      application: 'Write 3 headlines: role + domain + differentiator.',
      readiness: 'Your headline contains "Product Manager" and one domain keyword.',
      execution: 'Test: search yourself on LinkedIn. Do you appear for your target PM role?',
      confidence: 'A keyword-rich headline puts you in recruiter search results daily.',
    },
    tasks: LINKEDIN_TASKS['headline-authority'] || [],
  },
  {
    id: 'about-section',
    skill: 'About Section',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 2,
    signals: [
      'Your About tells a product story, not just lists roles',
      'It includes one specific product bet you made and why',
      'It ends with a clear signal of what you are looking for',
    ],
    advice: {
      awareness: 'An empty About section looks like a ghost profile to PM hiring managers.',
      understanding: 'The About section is your PM narrative. It connects decisions to outcomes.',
      application: 'Write 200 words: who you are, what type of product problems you solve, where next.',
      readiness: 'A stranger understands your PM specialty after reading your About.',
      execution: 'Hook the first 2 lines — they show before "see more".',
      confidence: 'A compelling About turns profile views into recruiter DMs.',
    },
    tasks: LINKEDIN_TASKS['about-section'] || [],
  },
  {
    id: 'network-connections',
    skill: 'Network Connections',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 50,
    difficulty: 1,
    signals: [
      'You have 100+ connections in product management',
      'You engage weekly with posts from PMs and product leaders',
      'You send personalized connection requests with context',
    ],
    advice: {
      awareness: 'A small network limits your visibility to PM opportunities.',
      understanding: 'The PM community is tight. Referrals come from weak connections.',
      application: 'Connect with 5 PMs, 3 CPOs, 2 PM recruiters this week.',
      readiness: 'Your network includes PMs who could refer you to product roles.',
      execution: 'Comment thoughtfully on product posts. Visibility beats silence.',
      confidence: 'An active network surfaces PM jobs before they are posted publicly.',
    },
    tasks: LINKEDIN_TASKS['network-connections'] || [],
  },
  {
    id: 'linkedin-optimization',
    skill: 'Profile Optimization',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 2,
    signals: [
      'Your profile is 90%+ complete',
      'Skills section has Product Management, Roadmap, A/B Testing endorsed',
      'Featured section shows your best case study or product write-up',
    ],
    advice: {
      awareness: 'An incomplete profile ranks lower in LinkedIn recruiter search.',
      understanding: 'LinkedIn algorithm favors complete profiles with recent activity.',
      application: 'Fill every section. Add PM skills. Request endorsements. Publish a case study.',
      readiness: 'Your profile appears in recruiter searches for "Product Manager [your domain]".',
      execution: 'Update your activity weekly. Even a short product insight post keeps you visible.',
      confidence: 'A complete, active profile generates inbound PM recruiter interest.',
    },
    tasks: LINKEDIN_TASKS['linkedin-optimization'] || [],
  },
  {
    id: 'profile-photo',
    skill: 'Profile Photo',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You have a professional headshot',
      'Your face takes up 60% of the frame',
      'The background is neutral or office-like',
    ],
    advice: {
      awareness: 'Profiles with photos get 21x more views than those without.',
      understanding: 'A photo builds trust before anyone reads your product experience.',
      application: 'Use a phone portrait mode against a plain wall. Dress business casual.',
      readiness: 'Your photo looks professional at thumbnail size (how recruiters see it).',
      execution: 'Smile naturally. Eye contact with camera. No sunglasses or group shots.',
      confidence: 'A good photo makes you memorable in a sea of generic PM profiles.',
    },
    tasks: LINKEDIN_TASKS['profile-photo'] || [],
  },
  {
    id: 'featured-content',
    skill: 'Featured Content',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 60,
    difficulty: 3,
    signals: [
      'Your Featured section shows a case study, PRD, or product essay',
      'Each item has a clear title and description',
      'Links are public and load correctly',
    ],
    advice: {
      awareness: 'The Featured section is prime real estate for proof of product thinking.',
      understanding: 'Hiring managers click Featured before scrolling to Experience.',
      application: 'Add your best case study, a product teardown, or a published product essay.',
      readiness: 'A hiring manager can see your product thinking in 1 click from your profile.',
      execution: 'Update Featured quarterly. Remove outdated or irrelevant work.',
      confidence: 'Featured content turns a static profile into a living product portfolio.',
    },
    tasks: LINKEDIN_TASKS['featured-content'] || [],
  },
  {
    id: 'recommendations',
    skill: 'Recommendations',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 35,
    difficulty: 1,
    signals: [
      'You have 2+ recommendations mentioning product ownership and impact',
      'Recommendations are from engineers, designers, or managers you worked with',
      'Each recommendation is specific, not generic',
    ],
    advice: {
      awareness: 'Recommendations are social proof that you can ship product with a team.',
      understanding: 'A specific recommendation ("She shipped the feature that doubled retention") beats "Great PM".',
      application: 'Ask 3 former colleagues for recommendations. Provide a specific focus area.',
      readiness: 'Your recommendations mention specific products, decisions, and outcomes.',
      execution: 'Give recommendations first. Reciprocity increases response rate significantly.',
      confidence: 'Strong recommendations reduce hiring manager risk perception.',
    },
    tasks: LINKEDIN_TASKS['recommendations'] || [],
  },
];

export const APPLICATION_SKILL_NODES: SkillNode[] = [
  {
    id: 'application-tracking',
    skill: 'Application Tracking',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You track every application in a spreadsheet or Notion',
      'You record company, role, date, status, and follow-up date',
      'You review your pipeline weekly and spot patterns',
    ],
    advice: {
      awareness: 'Without tracking, applications fall through cracks and follow-ups are missed.',
      understanding: 'Good PMs analyze their own job search like a product funnel.',
      application: 'Create a tracker: Company, Role, Stage, Product Domain, Notes, Next Step.',
      readiness: 'You know your application-to-phone-screen conversion rate.',
      execution: 'Set a weekly review. Identify bottlenecks: low callbacks? Fix resume or targeting.',
      confidence: 'A tracked pipeline turns a stressful search into a measurable process.',
    },
    tasks: APPLICATION_TASKS['application-tracking'] || [],
  },
  {
    id: 'cover-letter',
    skill: 'Cover Letter',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'Your cover letter references a specific product challenge of the company',
      'It connects your PM experience to their product stage and domain',
      'It is under 300 words and scannable',
    ],
    advice: {
      awareness: 'Generic cover letters signal generic product thinking.',
      understanding: 'A product-focused cover letter shows you understand their user and their bets.',
      application: 'Read the product page and job posting. Find one user problem. Explain your take.',
      readiness: 'Each cover letter is unique and mentions the product by name.',
      execution: 'Use: Hook (their user problem) + Proof (your product solution) + Ask (interview).',
      confidence: 'A targeted cover letter doubles interview invitation rates for PM roles.',
    },
    tasks: APPLICATION_TASKS['cover-letter'] || [],
  },
  {
    id: 'follow-up-strategy',
    skill: 'Follow-Up Strategy',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You follow up 5-7 days after applying',
      'Your follow-up adds product value (new insight, case study)',
      'You track responses and adjust timing',
    ],
    advice: {
      awareness: '80% of candidates never follow up. Those who do stand out.',
      understanding: 'A follow-up reminds hiring managers you exist without being pushy.',
      application: 'Draft 3 follow-up templates: after applying, after interview, after silence.',
      readiness: 'You have a follow-up schedule and stick to it across all applications.',
      execution: 'Add value: "I wrote a quick teardown of your onboarding flow after applying."',
      confidence: 'Persistent but polite follow-up shows the communication skills PMs need.',
    },
    tasks: APPLICATION_TASKS['follow-up-strategy'] || [],
  },
  {
    id: 'application-volume',
    skill: 'Application Volume',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'You apply to 5-10 relevant PM roles per week',
      'Quality and quantity are balanced: each application is tailored',
      'You track conversion rates and optimize',
    ],
    advice: {
      awareness: 'Applying to 100 random PM jobs is less effective than 10 targeted ones.',
      understanding: 'PM roles are competitive. Tailoring is the primary filter that helps you pass.',
      application: 'Set weekly goal: 5 quality applications with customized cover letters.',
      readiness: 'Your application-to-phone-screen rate is trackable and improving.',
      execution: 'Batch research on Sundays. Apply Tuesday-Thursday (peak recruiter activity).',
      confidence: 'Consistent quality volume builds momentum without burning out.',
    },
    tasks: APPLICATION_TASKS['application-volume'] || [],
  },
  {
    id: 'company-research',
    skill: 'Company Research',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 2,
    signals: [
      'You know the company product strategy and stage before applying',
      'You understand their business model, users, and main competitors',
      'You can name one product opportunity they have not yet addressed',
    ],
    advice: {
      awareness: 'Applying to a PM role without knowing the product shows you are not curious.',
      understanding: 'Companies hire PMs who understand their users and competitive position.',
      application: 'Research: product roadmap signals, pricing model, user reviews, recent launches.',
      readiness: 'You can explain why this company needs a PM with your exact background right now.',
      execution: 'Use: product blog, App Store reviews, G2/Capterra, LinkedIn, Crunchbase.',
      confidence: 'Deep research makes your application and interview answers sharply specific.',
    },
    tasks: APPLICATION_TASKS['company-research'] || [],
  },
  {
    id: 'application-tailoring',
    skill: 'Application Tailoring',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'Your resume keywords mirror each job posting',
      'Your cover letter references a specific product or feature',
      'You highlight the most relevant product experience for each role',
    ],
    advice: {
      awareness: 'One-size-fits-all PM applications get one-size-fits-all rejections.',
      understanding: 'ATS and hiring managers scan for keyword matches. Tailoring beats volume.',
      application: 'Mirror language from the posting: "0-to-1 product experience" not just "new products".',
      readiness: 'Each application feels written specifically for that product and company.',
      execution: 'Create 3 resume versions: growth PM, platform PM, 0-to-1 PM.',
      confidence: 'Tailored applications convert 3x better than generic PM submissions.',
    },
    tasks: APPLICATION_TASKS['application-tailoring'] || [],
  },
  {
    id: 'portfolio-submission',
    skill: 'Portfolio Submission',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'Your portfolio link is in every PM application',
      'It loads fast and is mobile-friendly',
      'It showcases case studies with problem, decision, and metric',
    ],
    advice: {
      awareness: 'A missing or broken PM portfolio kills credibility instantly.',
      understanding: 'Case studies prove product thinking better than any resume bullet.',
      application: 'Host on Notion, a personal site, or PDF. Test on mobile before every application.',
      readiness: 'A hiring manager can read your best case study in under 5 minutes.',
      execution: 'Include: user problem, data used, decision made, outcome, lessons learned.',
      confidence: 'A strong portfolio makes PM interviews easier — they trust your thinking already.',
    },
    tasks: APPLICATION_TASKS['portfolio-submission'] || [],
  },
  {
    id: 'referral-strategy',
    skill: 'Referral Strategy',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have asked 3+ people for PM referrals this month',
      'Your referral requests are specific and personalized',
      'You offer value before asking (coffee chat, product feedback)',
    ],
    advice: {
      awareness: 'Referred PM candidates are 15x more likely to be hired.',
      understanding: 'A warm introduction bypasses ATS and gets you a real product conversation.',
      application: 'Identify 10 target companies. Find 1st or 2nd degree PM connections.',
      readiness: 'You have a referral request template and use it every week.',
      execution: 'Build relationships first. Ask for product advice, not jobs. Referrals follow.',
      confidence: 'A strong network generates PM referrals without cold applications.',
    },
    tasks: APPLICATION_TASKS['referral-strategy'] || [],
  },
];

export const INTERVIEW_SKILL_NODES: SkillNode[] = [
  {
    id: 'interview-prep',
    skill: 'Interview Prep',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have a structured prep plan covering all PM interview types',
      'You know the company interview format (product sense, estimation, technical, behavioral)',
      'You have practiced answering product questions aloud',
    ],
    advice: {
      awareness: 'Winging a PM interview guarantees failure at any serious product company.',
      understanding: 'PM interviews have 4 parts: product sense, estimation, metrics, behavioral.',
      application: 'Create a 2-week plan: 1 product sense daily, 1 estimation weekly, stories ready.',
      readiness: 'You can structure a product sense answer in 2 minutes without preparation time.',
      execution: 'Practice with a partner. Record yourself. Listen for filler words and vague answers.',
      confidence: 'Structured prep turns PM interview anxiety into predictable performance.',
    },
    tasks: INTERVIEW_TASKS['interview-prep'] || [],
  },
  {
    id: 'product-sense',
    skill: 'Product Sense',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 60,
    difficulty: 3,
    signals: [
      'You can design a product feature end-to-end in 20 minutes',
      'You always start with user segmentation and pain points, not solutions',
      'You define success metrics before pitching features',
    ],
    advice: {
      awareness: 'Jumping to solutions before defining users is the #1 PM interview mistake.',
      understanding: 'Interviewers test: can you think like a product owner, not a feature factory?',
      application: 'Practice 10 product design questions. Use: Users → Pain → Solutions → Metrics.',
      readiness: 'You can walk through a product design question with clear structure and trade-offs.',
      execution: 'Always ask clarifying questions first. State your framework. Prioritize ruthlessly.',
      confidence: 'Strong product sense signals you will make good decisions with real users.',
    },
    tasks: INTERVIEW_TASKS['product-sense'] || [],
  },
  {
    id: 'estimation-prep',
    skill: 'Estimation',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 2,
    signals: [
      'You can estimate market size, DAU, or revenue in 5 minutes',
      'You break problems into components and state assumptions clearly',
      'You sense-check your answer at the end',
    ],
    advice: {
      awareness: 'Estimation questions test structured thinking under uncertainty.',
      understanding: 'Interviewers care about your process, not your final number.',
      application: 'Practice 5 classic estimates: Google searches/day, Uber rides/week in NYC, Spotify MAU.',
      readiness: 'You can estimate any market or metric with a clear breakdown and stated assumptions.',
      execution: 'Structure: define scope → break into parts → estimate each → sum → sanity check.',
      confidence: 'Calm, structured estimation signals PM readiness for ambiguous product decisions.',
    },
    tasks: INTERVIEW_TASKS['estimation-prep'] || [],
  },
  {
    id: 'technical-fluency',
    skill: 'Technical Fluency',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 2,
    signals: [
      'You can explain APIs, databases, and system trade-offs without coding',
      'You understand how engineers estimate effort and technical debt',
      'You can write a basic technical spec that engineers respect',
    ],
    advice: {
      awareness: 'PMs who cannot talk to engineers get ignored or overruled.',
      understanding: 'Technical fluency is not about coding — it is about informed trade-off conversations.',
      application: 'Learn: REST vs GraphQL, SQL basics, latency vs throughput, caching, CDNs.',
      readiness: 'You can discuss technical constraints with an engineer without needing a translator.',
      execution: 'Ask engineers to explain one technical concept per week. Take notes.',
      confidence: 'Technical fluency earns respect and makes your PRDs executable.',
    },
    tasks: INTERVIEW_TASKS['technical-fluency'] || [],
  },
  {
    id: 'interview-mindset',
    skill: 'Interview Mindset',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'You view PM interviews as collaborative product conversations',
      'You pause and think before answering ambiguous questions',
      'You recover gracefully from tough follow-up questions',
    ],
    advice: {
      awareness: 'Anxiety kills PM interview performance. Mindset is a skill you can train.',
      understanding: 'Interviewers want to see how you think, not just the answer you land on.',
      application: 'Practice mock PM interviews. Record yourself. Review structure and clarity.',
      readiness: 'You enter interviews calm, structured, and comfortable with ambiguity.',
      execution: 'Think aloud. It is okay to say "Let me take a moment to structure this."',
      confidence: 'Calm product thinkers make better decisions in interviews and on the job.',
    },
    tasks: INTERVIEW_TASKS['interview-mindset'] || [],
  },
  {
    id: 'behavioral-prep',
    skill: 'Behavioral Prep',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 2,
    signals: [
      'You have 5 STAR stories covering: influence, conflict, failure, prioritization, launch',
      'Each story includes a product metric and a lesson learned',
      'You can adapt any story to multiple question types',
    ],
    advice: {
      awareness: 'Behavioral questions filter PMs who cannot influence without authority.',
      understanding: 'PMs lead cross-functional teams. Soft skills and stories prove leadership.',
      application: 'Prepare stories for: disagreement with engineering, missed launch, strategy pivot.',
      readiness: 'Each story has a clear metric, a decision you owned, and a lesson.',
      execution: 'Use STAR format. Keep stories under 2 minutes. Practice aloud.',
      confidence: 'Strong behavioral answers prove you can operate in real product environments.',
    },
    tasks: INTERVIEW_TASKS['behavioral-prep'] || [],
  },
  {
    id: 'metrics-interview',
    skill: 'Metrics Interviews',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 3,
    signals: [
      'You can define success metrics for any feature in 2 minutes',
      'You know the difference between north star, guardrail, and diagnostic metrics',
      'You can investigate a metric drop systematically',
    ],
    advice: {
      awareness: 'Metric questions are in every PM interview. Failing them signals inexperience.',
      understanding: 'Interviewers want to know: can you measure what matters, not just what is easy?',
      application: 'Practice: "How would you measure success for X feature?" for 10 different products.',
      readiness: 'You can answer a metric question with a north star, counter-metric, and diagnostic.',
      execution: 'Structure: goal → primary metric → guardrail metrics → diagnostic breakdown.',
      confidence: 'Metric fluency shows you will make data-driven product decisions on the job.',
    },
    tasks: INTERVIEW_TASKS['metrics-interview'] || [],
  },
  {
    id: 'on-site-prep',
    skill: 'On-Site Prep',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'You know the interview schedule and who you will meet',
      'You have tailored questions for each interviewer (PM, engineer, designer)',
      'You have your case studies and metrics memorized, not just on paper',
    ],
    advice: {
      awareness: 'PM on-site loops are 4-6 hours. Energy and consistency matter across rounds.',
      understanding: 'Each interviewer evaluates a different PM dimension. Prep for all.',
      application: 'Research each interviewer on LinkedIn. Prepare 1 product question per person.',
      readiness: 'You have schedule, questions, case studies, and outfit ready the night before.',
      execution: 'Bring a notebook. Take notes during interviews. Ask about team product process.',
      confidence: 'Preparation turns a stressful on-site into a series of good product conversations.',
    },
    tasks: INTERVIEW_TASKS['on-site-prep'] || [],
  },
  {
    id: 'phone-screen',
    skill: 'Phone Screen',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You have a quiet space with good connection',
      'You can explain your PM background in 2 minutes',
      'You ask about the product, team structure, and biggest challenge',
    ],
    advice: {
      awareness: 'Phone screens filter mismatches early. Do not treat them as formalities.',
      understanding: 'Recruiters check: communication, motivation, salary alignment, availability.',
      application: 'Prepare a 2-minute pitch: what you built, metrics you moved, what you want next.',
      readiness: 'You sound structured and confident without slides or visual aids.',
      execution: 'Stand up during the call. It improves energy and voice projection.',
      confidence: 'A strong phone screen gets you the product sense or case study round.',
    },
    tasks: INTERVIEW_TASKS['phone-screen'] || [],
  },
  {
    id: 'interview-followup',
    skill: 'Interview Follow-Up',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You send thank-you emails within 24 hours of each round',
      'Each email references a specific product topic from the conversation',
      'You reiterate your product thesis for why you want this role',
    ],
    advice: {
      awareness: 'Thank-you emails are not optional for PM roles. They signal follow-through.',
      understanding: 'A thoughtful PM follow-up can tip a borderline hiring decision in your favor.',
      application: 'Draft templates now. Personalize each with a specific product detail discussed.',
      readiness: 'You send follow-ups within 24 hours, every time, without exception.',
      execution: 'Reference something specific: "I kept thinking about your north star metric discussion."',
      confidence: 'Professional follow-up signals PM maturity and genuine product interest.',
    },
    tasks: INTERVIEW_TASKS['interview-followup'] || [],
  },
];

export const OFFER_PREPARATION_SKILL_NODES: SkillNode[] = [
  {
    id: 'salary-research',
    skill: 'Salary Research',
    domain: 'Offer Preparation',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 2,
    signals: [
      'You know the PM salary range for your level, domain, and location',
      'You have data from 3+ sources: Levels.fyi, Glassdoor, Blind, LinkedIn Salary',
      'You understand total PM compensation: base, bonus, equity, signing bonus',
    ],
    advice: {
      awareness: 'Negotiating without data is guessing. Guessing leaves PM compensation on the table.',
      understanding: 'PM salaries vary by stage (startup vs FAANG), domain, and level (APM/PM/Sr).',
      application: 'Research base, bonus target, equity refresh, signing bonus for your target role.',
      readiness: 'You have a specific target range backed by at least 3 market data points.',
      execution: 'Use Levels.fyi for tech, Glassdoor for general, Blind for anonymous comp data.',
      confidence: 'Data-backed PM negotiation requests are hard to refuse.',
    },
    tasks: OFFER_TASKS['salary-research'] || [],
  },
  {
    id: 'offer-review',
    skill: 'Offer Review',
    domain: 'Offer Preparation',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'You read every line of the PM offer letter',
      'You note verbal promises not in writing',
      'You understand vesting cliff, refresh schedule, and performance review cycle',
    ],
    advice: {
      awareness: 'PM offer letters contain traps. Read them like you read a product spec.',
      understanding: 'Verbal promises mean nothing. Only written terms are enforceable.',
      application: 'Checklist: base, bonus structure, equity grant and cliff, title, start date, PTO.',
      readiness: 'You can explain every component of your PM offer to a friend.',
      execution: 'Ask for clarification on anything vague. Get all promises in writing.',
      confidence: 'A thorough review prevents costly surprises on day one.',
    },
    tasks: OFFER_TASKS['offer-review'] || [],
  },
  {
    id: 'resignation-letter',
    skill: 'Resignation Letter',
    domain: 'Offer Preparation',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You have a professional resignation letter template ready',
      'It is concise, positive, and gives proper notice',
      'You are prepared for a counter-offer and know your answer in advance',
    ],
    advice: {
      awareness: 'Burning bridges is expensive. The PM world is smaller than it looks.',
      understanding: 'A graceful exit preserves references and relationships for years.',
      application: 'Draft a resignation letter. Keep it under 150 words. Stay professional.',
      readiness: 'You can resign without drama, regardless of how you feel about the job.',
      execution: 'Resign in person first. Follow up with the written letter immediately after.',
      confidence: 'Professional exits open PM doors. Dramatic exits close them permanently.',
    },
    tasks: OFFER_TASKS['resignation-letter'] || [],
  },
];

export const OFFER_SKILL_NODES: SkillNode[] = [
  {
    id: 'offer-evaluation',
    skill: 'Offer Evaluation',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You score PM offers on multiple dimensions, not just salary',
      'You consider product quality, team caliber, domain fit, and growth trajectory',
      'You have a weighted decision framework, not just gut feeling',
    ],
    advice: {
      awareness: 'The highest PM salary is not always the best career move.',
      understanding: 'Early PM career growth compounds. Domain fit beats a $15K salary bump.',
      application: 'Score each offer: compensation, product scope, team quality, growth, autonomy.',
      readiness: 'You can justify your choice with specific criteria, not emotion.',
      execution: 'Sleep on it. Talk to a PM mentor. Do not decide under pressure or deadline.',
      confidence: 'A structured PM evaluation prevents regret six months into a new role.',
    },
    tasks: OFFER_TASKS['offer-evaluation'] || [],
  },
  {
    id: 'salary-negotiation',
    skill: 'Salary Negotiation',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 3,
    signals: [
      'You always negotiate PM offers, even when they seem fair',
      'You anchor high but reasonable based on Levels.fyi data',
      'You negotiate total compensation: base, equity, signing, PTO',
    ],
    advice: {
      awareness: 'Not negotiating PM offers costs hundreds of thousands over a career.',
      understanding: 'Companies expect negotiation. Asking does not make you difficult.',
      application: 'Script your negotiation: gratitude + market data + specific ask + flexibility.',
      readiness: 'You can request more without anxiety or apology.',
      execution: 'Negotiate base, equity refresh, signing bonus, title, remote policy, start date.',
      confidence: 'Every dollar negotiated now compounds across your entire PM career.',
    },
    tasks: OFFER_TASKS['salary-negotiation'] || [],
  },
  {
    id: 'decision-framework',
    skill: 'Decision Framework',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 15,
    difficulty: 1,
    signals: [
      'You have a written list of PM priorities before comparing offers',
      'You weight short-term comp against long-term product scope',
      'You involve a PM mentor or trusted peer in the decision',
    ],
    advice: {
      awareness: 'Deciding between PM offers is stressful. A framework removes emotion.',
      understanding: 'Your priorities shift across career stages. A framework adapts with them.',
      application: 'List your top 5 priorities. Rank them. Score each offer against each priority.',
      readiness: 'You can explain why offer A beats offer B with specific, ranked reasons.',
      execution: 'Set a decision deadline. Gather mentor input. Commit. Do not second-guess.',
      confidence: 'A clear PM decision framework makes you decisive, not impulsive.',
    },
    tasks: OFFER_TASKS['decision-framework'] || [],
  },
  {
    id: 'offer-acceptance',
    skill: 'Offer Acceptance',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'You confirm the PM offer in writing before giving notice',
      'You understand start date, onboarding, and first 30 days expectations',
      'You prepare a clean handoff plan for your current role',
    ],
    advice: {
      awareness: 'Verbal PM acceptance is not binding. Written confirmation protects both sides.',
      understanding: 'A smooth start sets the tone for your entire PM tenure at the company.',
      application: 'Send written acceptance. Confirm start date. Ask about onboarding expectations.',
      readiness: 'You have a plan for your first week: team intros, product deep-dive, quick wins.',
      execution: 'Give notice professionally. Document your roadmap. Wrap up key decisions.',
      confidence: 'A professional transition builds PM reputation before day one.',
    },
    tasks: OFFER_TASKS['offer-acceptance'] || [],
  },
  {
    id: 'benefits-evaluation',
    skill: 'Benefits Evaluation',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You calculate total PM compensation value, not just base salary',
      'You compare equity, bonus structure, health insurance, PTO, learning budget',
      'You understand vesting schedule and cliff before accepting',
    ],
    advice: {
      awareness: 'PM benefits can be worth 40-60% of base salary. Ignoring them is expensive.',
      understanding: 'Equity at a Series B is worth more in upside than the same grant at a public co.',
      application: 'Calculate total compensation including all benefits over 1 year and 4 years.',
      readiness: 'You can compare two PM offers on total value, not just base salary.',
      execution: 'Ask HR for detailed benefits docs. Model the equity scenarios. Ask questions.',
      confidence: 'A complete benefits analysis prevents costly PM compensation surprises.',
    },
    tasks: OFFER_TASKS['benefits-evaluation'] || [],
  },
  {
    id: 'start-transition',
    skill: 'Start Transition',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 2,
    signals: [
      'You have a 30-60-90 day PM plan for your new role',
      'You identified quick wins to build credibility with the team fast',
      'You are researching the product, users, and data before day one',
    ],
    advice: {
      awareness: 'The first 90 days as a PM determine your trajectory at the company.',
      understanding: 'PM credibility is built quickly. Early wins create lasting momentum.',
      application: 'Research the product, read user reviews, study the data, talk to customers.',
      readiness: 'You can articulate your first-month PM priorities in the final interview round.',
      execution: 'Listen more than you speak in week 1. Ask "why" more than you say "we should".',
      confidence: 'A strong PM start turns a new job into a career accelerator.',
    },
    tasks: OFFER_TASKS['start-transition'] || [],
  },
];

export const ALL_SKILL_NODES: SkillNode[] = [
  ...RESUME_SKILL_NODES,
  ...LINKEDIN_SKILL_NODES,
  ...APPLICATION_SKILL_NODES,
  ...INTERVIEW_SKILL_NODES,
  ...OFFER_PREPARATION_SKILL_NODES,
  ...OFFER_SKILL_NODES,
];
