import type { SkillNode } from '@/core/skill_state';
import { RESUME_TASKS } from './tasks/resume';
import { LINKEDIN_TASKS } from './tasks/linkedin';

// ─── CHAPTER 1: RESUME (6 nodes) ──────────────────────────────────
export const RESUME_SKILL_NODES: SkillNode[] = [
  {
    id: 'positioning-clarity',
    skill: 'Positioning Clarity',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You can describe your target cybersecurity role in one clear sentence',
      'Your resume headline matches "Security Analyst", "SOC Analyst", or "Penetration Tester"',
      'Your tech stack includes SIEM, firewalls, and at least one scripting language',
    ],
    advice: {
      awareness: 'A cybersecurity resume without clear positioning looks like a generic IT helpdesk candidate. Define your defensive or offensive niche.',
      understanding: 'Recruiters scan for: SIEM experience, incident response, certifications, and tool proficiency. Not just "interested in security".',
      application: 'Analyze 5 cybersecurity job postings. Extract common tools: Splunk, Wireshark, Metasploit, Nessus, etc.',
      readiness: 'You can state your target role, primary tools, and domain: blue team, red team, GRC, or cloud security.',
      execution: 'Every resume section reinforces the same security positioning.',
      confidence: 'A focused security resume answers "Can this person protect our assets?" immediately.',
    },
    tasks: RESUME_TASKS['positioning-clarity'] || [],
  },
  {
    id: 'cyber-skills-matrix',
    skill: 'Skills Matrix',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have rated your SIEM proficiency on a 1-5 scale',
      'You can list 3 offensive and 3 defensive tools you have used',
      'You have quantified at least one security incident you handled',
    ],
    advice: {
      awareness: 'Listing "firewalls, IDS, Kali" is not enough. Recruiters want depth: configured, monitored, or exploited?',
      understanding: 'A skills matrix shows progression: watched alerts → tuned rules → wrote detection logic → led incident response.',
      application: 'Create a table: Tool | Type (Off/Def) | Level | Last Used | Incident/Project Example.',
      readiness: 'You can defend every skill rating with a specific incident or lab scenario.',
      execution: 'Place the matrix prominently. Security hiring managers scan for tool names first.',
      confidence: 'A honest skills matrix builds trust faster than inflated claims.',
    },
    tasks: RESUME_TASKS['cyber-skills-matrix'] || [],
  },
  {
    id: 'resume-structure',
    skill: 'Resume Structure',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 25,
    difficulty: 1,
    signals: [
      'Your resume has a clear header with contact info, LinkedIn, and GitHub',
      'Experience bullets follow STAR method with security metrics',
      'Certifications section includes Security+, CEH, or equivalent',
    ],
    advice: {
      awareness: 'A poorly structured security resume hides your incident response experience behind formatting noise.',
      understanding: 'Security recruiters scan for: certs, SIEM tools, incident count, vulnerability findings, in that order.',
      application: 'Reformat one bullet: "Detected and contained 3 phishing campaigns using Splunk, reducing dwell time by 60%."',
      readiness: 'Every bullet has a security metric: incidents handled, vulnerabilities found, time reduced.',
      execution: 'Use a clean, single-column format that ATS parses correctly. Security roles often use government ATS.',
      confidence: 'A structured resume tells a security story about your career.',
    },
    tasks: RESUME_TASKS['resume-structure'] || [],
  },
  {
    id: 'home-lab-showcase',
    skill: 'Home Lab Showcase',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 3,
    signals: [
      'You have a documented home lab with network diagram',
      'Lab includes: SIEM (Splunk/ELK), firewall (pfSense), vulnerable machines (VulnHub)',
      'You have 2+ writeups of attacks you performed and defended against',
    ],
    advice: {
      awareness: 'Cybersecurity resumes without a home lab look theoretical. Show you have hands-on experience.',
      understanding: 'A home lab proves you can configure, attack, and defend real systems. Not just watch videos.',
      application: 'Set up a virtual network: 1 SIEM, 1 firewall, 2 vulnerable machines. Document with screenshots.',
      readiness: 'You can walk through your lab in 3 minutes: topology, tools, attack scenario, defense applied.',
      execution: 'Link to GitHub with network diagram, configuration files, and attack writeups.',
      confidence: 'A home lab turns "I am interested in security" into "Here is my security playground."',
    },
    tasks: RESUME_TASKS['home-lab-showcase'] || [],
  },
  {
    id: 'incident-response-stories',
    skill: 'Incident Response Stories',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 35,
    difficulty: 2,
    signals: [
      'Every experience bullet describes a security incident you handled',
      'Stories follow: Alert → Investigation → Containment → Lessons Learned',
      'You have quantified impact: time saved, breaches prevented, cost avoided',
    ],
    advice: {
      awareness: '"Monitored SIEM alerts" is weak. "Contained ransomware outbreak in 45 minutes, preventing $200K loss" is strong.',
      understanding: 'Incident response stories show: detection speed, decision quality, and business impact.',
      application: 'Rewrite 3 bullets as incident stories: what was the alert, what did you do, what was the outcome.',
      readiness: 'You can tell each story in 2 minutes with technical depth and business context.',
      execution: 'Use action verbs: detected, contained, eradicated, recovered, hardened.',
      confidence: 'Incident stories prove you can handle pressure and protect assets.',
    },
    tasks: RESUME_TASKS['incident-response-stories'] || [],
  },
  {
    id: 'resume-ats',
    skill: 'ATS Optimization',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'Your resume has no tables, columns, or graphics that confuse ATS',
      'Keywords from security job postings appear naturally: SIEM, IDS, IPS, NIST, MITRE ATT&CK',
      'File format is PDF with selectable text',
    ],
    advice: {
      awareness: 'A beautiful resume that ATS rejects is useless. Government and defense contractors use strict ATS.',
      understanding: 'ATS scans for: clearance level, certifications, security frameworks, and standard section headings.',
      application: 'Paste your resume into a plain text editor. Check for garbled text and correct order.',
      readiness: 'Your resume parses cleanly with all security keywords intact.',
      execution: 'Use standard headings: Clearance, Certifications, Experience, Skills. No icons, no text boxes.',
      confidence: 'An ATS-optimized resume reaches security recruiters and government hiring systems.',
    },
    tasks: RESUME_TASKS['resume-ats'] || [],
  },
];

// ─── CHAPTER 2: LINKEDIN (6 nodes) ──────────────────────────────────
export const LINKEDIN_SKILL_NODES: SkillNode[] = [
  {
    id: 'headline-authority',
    skill: 'Headline Authority',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 15,
    difficulty: 1,
    signals: [
      'Your headline says "Security Analyst" or "SOC Analyst" not "IT Professional"',
      'Headline includes a specific domain: Cloud Security, GRC, Threat Intelligence',
      'You have a clear value proposition in 120 characters',
    ],
    advice: {
      awareness: 'A weak headline makes you invisible to security recruiters searching for "SOC Analyst" or "Penetration Tester".',
      understanding: 'LinkedIn search weights headline heavily. Security keywords matter more than creativity.',
      application: 'Write 5 headline variants. Test them with a security recruiter or career coach.',
      readiness: 'Your headline contains: role, domain, and one tool or certification.',
      execution: 'Update headline. Remove "seeking", "open to work", and emojis. Add "CISSP" or "Security+" if held.',
      confidence: 'A strong headline attracts inbound recruiter messages for security roles.',
    },
    tasks: LINKEDIN_TASKS['headline-authority'] || [],
  },
  {
    id: 'about-section',
    skill: 'About Section',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 25,
    difficulty: 2,
    signals: [
      'Your About section tells a security career story, not just lists skills',
      'It includes a specific incident or vulnerability you discovered',
      'It ends with a clear call to action and clearance status',
    ],
    advice: {
      awareness: 'A blank About section wastes prime LinkedIn real estate. Security recruiters read it for culture fit.',
      understanding: 'The About section is your elevator pitch: who you are, what you defend, what you want.',
      application: 'Write 3 paragraphs: background, key incident or discovery, what you are looking for.',
      readiness: 'You can read your About section aloud in under 30 seconds.',
      execution: 'Use first person. Include one security metric. End with "TS/SCI eligible" or clearance level.',
      confidence: 'A compelling About section turns profile views into connection requests from CISOs.',
    },
    tasks: LINKEDIN_TASKS['about-section'] || [],
  },
  {
    id: 'network-connections',
    skill: 'Network Connections',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have 50+ connections in cybersecurity: analysts, engineers, CISOs',
      'You engage with posts from security leaders weekly',
      'You have requested informational interviews with 3+ SOC managers',
    ],
    advice: {
      awareness: 'A small network limits your security job pipeline. Most cleared roles are filled through referrals.',
      understanding: 'Quality connections > quantity. Target SOC managers, threat hunters, and security recruiters.',
      application: 'Send 5 personalized connection requests this week. Mention a shared CTF or conference.',
      readiness: 'You have a warm connection at 3 target companies or agencies.',
      execution: 'Comment thoughtfully on breach analyses. Share your own home lab discoveries.',
      confidence: 'A strong network surfaces hidden cleared opportunities before they are posted.',
    },
    tasks: LINKEDIN_TASKS['network-connections'] || [],
  },
  {
    id: 'ctf-writeups',
    skill: 'CTF Writeups',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 40,
    difficulty: 3,
    signals: [
      'You have published 3+ CTF writeups on LinkedIn or Medium',
      'Each writeup includes: challenge, approach, flag, and lessons learned',
      'Writeups demonstrate both offensive and defensive techniques',
    ],
    advice: {
      awareness: 'CTF writeups are a security portfolio that lives where recruiters already are.',
      understanding: 'A well-written writeup proves technical depth, persistence, and knowledge sharing.',
      application: 'Write your first writeup: "How I solved [CTF challenge] using [technique]."',
      readiness: 'You have 3 writeups that you can reference in interviews.',
      execution: 'Include screenshots, code snippets, and mitigation advice. Tag #CTF #Cybersecurity.',
      confidence: 'Writeups turn your profile into a content hub that attracts security recruiters.',
    },
    tasks: LINKEDIN_TASKS['ctf-writeups'] || [],
  },
  {
    id: 'security-blog',
    skill: 'Security Blog',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 3,
    signals: [
      'You have published 2+ articles on security topics: malware analysis, threat intel, tool reviews',
      'Each article includes technical depth and business relevance',
      'Articles have engagement from security professionals',
    ],
    advice: {
      awareness: 'A security blog proves you can communicate complex threats to non-technical stakeholders.',
      understanding: 'CISOs value analysts who can write clear incident reports and threat briefings.',
      application: 'Write your first article: "Analysis of [recent breach]: what went wrong and how to prevent it."',
      readiness: 'You have 2 articles that demonstrate technical and communication skills.',
      execution: 'Include IOCs, MITRE ATT&CK mappings, and remediation steps. Keep it under 800 words.',
      confidence: 'A security blog turns your profile into a thought leadership platform.',
    },
    tasks: LINKEDIN_TASKS['security-blog'] || [],
  },
  {
    id: 'certifications-display',
    skill: 'Certifications Display',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'Security+, CEH, CISSP, or equivalent is listed in Licenses & Certifications',
      'Certifications include credential IDs and verification URLs',
      'You have completed LinkedIn Skills Assessments for Cybersecurity and Python',
    ],
    advice: {
      awareness: 'Security certifications are often required, not preferred. They gate interviews at many organizations.',
      understanding: 'CISSP requires 5 years experience. Security+ is entry-level. CEH is offensive-focused.',
      application: 'Add all certifications with dates. Schedule your next exam to show progression.',
      readiness: 'Your top 3 certifications are visible and verifiable.',
      execution: 'Add credential URLs. Request endorsements for SIEM, Incident Response, and Vulnerability Assessment.',
      confidence: 'Certifications + endorsements = social proof of your security competency.',
    },
    tasks: LINKEDIN_TASKS['certifications-display'] || [],
  },
];

// ─── EXPORTS ───────────────────────────────────────────────────────
export {
  APPLICATION_SKILL_NODES,
  INTERVIEW_SKILL_NODES,
  OFFER_PREPARATION_SKILL_NODES,
  OFFER_SKILL_NODES,
} from './skill_nodes_extended';

import {
  APPLICATION_SKILL_NODES,
  INTERVIEW_SKILL_NODES,
  OFFER_PREPARATION_SKILL_NODES,
  OFFER_SKILL_NODES,
} from './skill_nodes_extended';

export const ALL_SKILL_NODES: SkillNode[] = [
  ...RESUME_SKILL_NODES,
  ...LINKEDIN_SKILL_NODES,
  ...APPLICATION_SKILL_NODES,
  ...INTERVIEW_SKILL_NODES,
  ...OFFER_PREPARATION_SKILL_NODES,
  ...OFFER_SKILL_NODES,
];
