import type { SkillNode } from '@/core/skill_state';
import { APPLICATION_TASKS } from './tasks/applications';
import { INTERVIEW_TASKS } from './tasks/interviews';
import { OFFER_TASKS } from './tasks/offer';

// ─── CHAPTER 3: APPLICATIONS (7 nodes) ──────────────────────────────
export const APPLICATION_SKILL_NODES: SkillNode[] = [
  {
    id: 'application-tracking',
    skill: 'Application Tracking',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 25,
    difficulty: 1,
    signals: [
      'You lose track of applications',
      'You miss follow-up deadlines',
    ],
    advice: {
      awareness: 'You cannot manage what you cannot see. When applications are scattered, you lose control of your pipeline.',
      understanding: 'Every application is an object in a pipeline with stages: sent, viewed, interview, rejected, offer.',
      application: 'Build a tracker: company, role, date applied, clearance required, status, next action.',
      readiness: 'You have a single source of truth for all applications.',
      execution: 'Update it every day after any responses or status changes.',
      confidence: 'You begin to see patterns: which companies react to your level.',
    },
    tasks: APPLICATION_TASKS['application-tracking'] || [],
  },
  {
    id: 'portfolio-home-lab',
    skill: 'Portfolio Home Lab',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 60,
    difficulty: 3,
    signals: [
      'Your home lab is not documented',
      'You cannot show practical work',
    ],
    advice: {
      awareness: 'A documented home lab is the security equivalent of a software portfolio.',
      understanding: 'Recruiters want proof of hands-on skills, not just certifications.',
      application: 'Document your lab with architecture diagrams, scenarios, and findings.',
      readiness: 'You can share a link to your lab documentation.',
      execution: 'Update your portfolio with new lab scenarios monthly.',
      confidence: 'A strong portfolio makes interviews easier because you have proof of skills.',
    },
    tasks: APPLICATION_TASKS['portfolio-home-lab'] || [],
  },
  {
    id: 'ctf-scores',
    skill: 'CTF Scores',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'Your CTF performance is not documented',
      'You cannot prove competitive skills',
    ],
    advice: {
      awareness: 'CTF rankings are objective proof of security problem-solving ability.',
      understanding: 'Top CTF performers are immediately noticed by security teams.',
      application: 'Document your CTF scores, rankings, and write-ups.',
      readiness: 'You can link to your CTF profile from any application.',
      execution: 'Compete in at least one CTF per quarter.',
      confidence: 'Strong CTF performance opens doors to security roles.',
    },
    tasks: APPLICATION_TASKS['ctf-scores'] || [],
  },
  {
    id: 'clearance-prep',
    skill: 'Clearance Prep',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'You do not understand clearance requirements',
      'You are not clearance-ready',
    ],
    advice: {
      awareness: 'Many security roles require security clearance. Understanding the process gives you an advantage.',
      understanding: 'Clearance levels: Confidential, Secret, Top Secret. Higher clearance = higher salary.',
      application: 'Research clearance requirements for your target roles.',
      readiness: 'You can explain the clearance process and timeline.',
      execution: 'Start the clearance process early if targeting government roles.',
      confidence: 'Being clearance-ready or clearance-eligible gives you an edge.',
    },
    tasks: APPLICATION_TASKS['clearance-prep'] || [],
  },
  {
    id: 'company-research',
    skill: 'Company Research',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 40,
    difficulty: 2,
    signals: [
      'You apply without researching the company',
      'You cannot answer "Why this company?"',
    ],
    advice: {
      awareness: 'Without understanding the company you send blind applications that ignore their security needs.',
      understanding: 'Security teams differ dramatically between startups and enterprises.',
      application: 'For every company capture: security stack, team size, recent breaches, compliance.',
      readiness: 'You can explain why this company needs a security professional right now.',
      execution: 'Research their security team, tools, and recent security news.',
      confidence: 'Deep research makes your application and interview answers specific.',
    },
    tasks: APPLICATION_TASKS['company-research'] || [],
  },
  {
    id: 'application-tailoring',
    skill: 'Application Tailoring',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 3,
    signals: [
      'You send the same application to every role',
      'Your match rate is low',
    ],
    advice: {
      awareness: 'The same resume for every opening almost always lowers your chances.',
      understanding: 'Recruiters scan keyword matches in seconds through ATS.',
      application: 'Use the 80% match rule: apply only where you cover most requirements.',
      readiness: 'You have several resume versions for different security roles.',
      execution: 'Before sending, copy relevant keywords from the opening into your resume.',
      confidence: 'Tailored applications convert 3x better than generic ones.',
    },
    tasks: APPLICATION_TASKS['application-tailoring'] || [],
  },
  {
    id: 'referral-strategy',
    skill: 'Referral Strategy',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 40,
    difficulty: 2,
    signals: [
      'You never get referrals',
      'You do not ask for introductions',
    ],
    advice: {
      awareness: 'At any level, referrals multiply your chances of getting an interview.',
      understanding: 'A referral is not asking for a job. It is entering through trust.',
      application: 'Find contacts at target companies through LinkedIn, conferences, or local groups.',
      readiness: 'You have a list of companies and potential entry points for each.',
      execution: 'Write a short message about who you are and what you have built.',
      confidence: 'You begin gaining access to the hidden job market.',
    },
    tasks: APPLICATION_TASKS['referral-strategy'] || [],
  },
];

// ─── CHAPTER 4: INTERVIEWS (10 nodes) ────────────────────────────────
export const INTERVIEW_SKILL_NODES: SkillNode[] = [
  {
    id: 'interview-prep',
    skill: 'Interview Preparation',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 60,
    difficulty: 3,
    signals: [
      'You do not have security stories ready',
      'You ramble in interviews',
    ],
    advice: {
      awareness: 'Most candidates walk into interviews without structured stories.',
      understanding: 'Interviewers expect clear narratives about your security experience.',
      application: 'Build 6-8 reusable stories from your projects and labs.',
      readiness: 'You can answer "Tell me about a security incident" without thinking from scratch.',
      execution: 'Spend 30-45 minutes daily rehearsing stories out loud.',
      confidence: 'You stop freezing during open-ended questions.',
    },
    tasks: INTERVIEW_TASKS['interview-prep'] || [],
  },
  {
    id: 'networking-deep-dive',
    skill: 'Networking Deep Dive',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 2,
    signals: [
      'You struggle with networking questions',
      'You cannot explain TCP/IP clearly',
    ],
    advice: {
      awareness: 'Networking fundamentals are tested in almost every security interview.',
      understanding: 'You must understand OSI model, TCP/IP, DNS, HTTP, and common attack vectors.',
      application: 'Review networking concepts and practice explaining them simply.',
      readiness: 'You can diagram a network packet flow from client to server.',
      execution: 'Practice explaining networking concepts to non-technical people.',
      confidence: 'Strong networking knowledge is the foundation of security.',
    },
    tasks: INTERVIEW_TASKS['networking-deep-dive'] || [],
  },
  {
    id: 'linux-administration',
    skill: 'Linux Administration',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 60,
    difficulty: 2,
    signals: [
      'You are not comfortable with Linux command line',
      'You cannot navigate logs or permissions',
    ],
    advice: {
      awareness: 'Most security tools run on Linux. Comfort with the command line is non-negotiable.',
      understanding: 'Interviewers test: file permissions, process management, log analysis, networking commands.',
      application: 'Practice daily Linux tasks: grep, awk, sed, systemctl, journalctl.',
      readiness: 'You can perform common tasks without documentation.',
      execution: 'Set up a Linux VM and use it as your primary environment.',
      confidence: 'Linux proficiency is a baseline requirement for most security roles.',
    },
    tasks: INTERVIEW_TASKS['linux-administration'] || [],
  },
  {
    id: 'python-security',
    skill: 'Python Security',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 90,
    difficulty: 3,
    signals: [
      'You cannot write security scripts',
      'You struggle with Python automation',
    ],
    advice: {
      awareness: 'Python is the most used language in security for scripting and automation.',
      understanding: 'Security roles require: log parsing, API interaction, automation, exploit development.',
      application: 'Practice writing Python scripts for common security tasks.',
      readiness: 'You can write a script to parse logs, scan ports, or interact with an API.',
      execution: 'Build a small security tool in Python for your portfolio.',
      confidence: 'Python skills significantly increase your market value.',
    },
    tasks: INTERVIEW_TASKS['python-security'] || [],
  },
  {
    id: 'siem-analysis',
    skill: 'SIEM Analysis',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 120,
    difficulty: 3,
    signals: [
      'You have never used a SIEM',
      'You cannot write detection rules',
    ],
    advice: {
      awareness: 'SIEM platforms are the core of SOC operations. Splunk, ELK, or Sentinel experience is essential.',
      understanding: 'SIEM analysts must understand log sources, correlation rules, and alert triage.',
      application: 'Set up a SIEM in your home lab and create detection rules.',
      readiness: 'You can explain how SIEM works and write basic queries.',
      execution: 'Practice with Splunk free tier or ELK stack.',
      confidence: 'SIEM experience is the most sought-after skill in SOC roles.',
    },
    tasks: INTERVIEW_TASKS['siem-analysis'] || [],
  },
  {
    id: 'incident-response-scenario',
    skill: 'Incident Response Scenario',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 75,
    difficulty: 3,
    signals: [
      'You have never walked through an IR scenario',
      'You cannot structure an IR response',
    ],
    advice: {
      awareness: 'IR scenarios are the most common interview format for security roles.',
      understanding: 'Interviewers evaluate: triage skills, communication, technical depth, and decision-making.',
      application: 'Practice walking through IR scenarios step by step.',
      readiness: 'You can handle "A user reports phishing" or "We see unusual traffic" confidently.',
      execution: 'Practice with a friend and get feedback on your process.',
      confidence: 'IR scenario mastery is the fastest path to a security job.',
    },
    tasks: INTERVIEW_TASKS['incident-response-scenario'] || [],
  },
  {
    id: 'threat-hunting-basics',
    skill: 'Threat Hunting Basics',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 60,
    difficulty: 3,
    signals: [
      'You do not know what threat hunting is',
      'You cannot explain MITRE ATT&CK',
    ],
    advice: {
      awareness: 'Threat hunting is proactive security monitoring. It is increasingly required in security roles.',
      understanding: 'Hunters use MITRE ATT&CK framework, threat intelligence, and hypothesis-driven search.',
      application: 'Learn MITRE ATT&CK and practice hypothesis-driven searches.',
      readiness: 'You can explain a threat hunt and describe your methodology.',
      execution: 'Practice with real datasets from BZAR or Security Onion.',
      confidence: 'Threat hunting skills distinguish senior from junior candidates.',
    },
    tasks: INTERVIEW_TASKS['threat-hunting-basics'] || [],
  },
  {
    id: 'on-site-prep',
    skill: 'On-Site Prep',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 1,
    signals: [
      'You do not know what to expect on-site',
      'You have not prepared questions',
    ],
    advice: {
      awareness: 'On-site interviews are marathons. Energy management and preparation are key.',
      understanding: 'You will meet multiple people evaluating different skills.',
      application: 'Research each interviewer and prepare personalized questions.',
      readiness: 'You have a schedule, materials, and questions ready.',
      execution: 'Bring a notebook and take notes during interviews.',
      confidence: 'Preparation turns a stressful day into a series of good conversations.',
    },
    tasks: INTERVIEW_TASKS['on-site-prep'] || [],
  },
  {
    id: 'red-team-blue-team',
    skill: 'Red Team vs Blue Team',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'You do not understand Red vs Blue team roles',
      'You cannot explain your preference',
    ],
    advice: {
      awareness: 'Understanding the difference between offensive and defensive security helps you position yourself.',
      understanding: 'Red Team: penetration testing, vulnerability research, exploit development.',
      application: 'Decide which direction interests you more and prepare accordingly.',
      readiness: 'You can clearly explain why you prefer Red or Blue team.',
      execution: 'Tailor your interview answers to emphasize your chosen direction.',
      confidence: 'Clear positioning shows self-awareness and focus.',
    },
    tasks: INTERVIEW_TASKS['red-team-blue-team'] || [],
  },
  {
    id: 'interview-followup',
    skill: 'Interview Follow-Up',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You never follow up after interviews',
      'You miss opportunities due to silence',
    ],
    advice: {
      awareness: 'Follow-up emails are not optional. They are your last impression.',
      understanding: 'A thoughtful follow-up can tip a borderline decision in your favor.',
      application: 'Send thank-you emails within 24 hours, referencing specific conversation topics.',
      readiness: 'You send follow-ups within 24 hours, every time.',
      execution: 'Mention something specific from the interview.',
      confidence: 'Professional follow-up signals maturity and genuine interest.',
    },
    tasks: INTERVIEW_TASKS['interview-followup'] || [],
  },
];

// ─── CHAPTER 5: OFFER PREPARATION (3 nodes) ──────────────────────────
export const OFFER_PREPARATION_SKILL_NODES: SkillNode[] = [
  {
    id: 'certification-prep',
    skill: 'Certification Prep',
    domain: 'Offer Preparation',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'You do not have relevant certifications',
      'Your certs are outdated',
    ],
    advice: {
      awareness: 'Certifications are the entry ticket for many security roles.',
      understanding: 'CompTIA Security+, CEH, and OSCP are immediately recognized.',
      application: 'Choose certifications that align with your target role.',
      readiness: 'You have a certification study plan and timeline.',
      execution: 'Study consistently and schedule exams in advance.',
      confidence: 'Certifications increase your market value immediately.',
    },
    tasks: OFFER_TASKS['certification-prep'] || [],
  },
  {
    id: 'clearance-process',
    skill: 'Clearance Process',
    domain: 'Offer Preparation',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 60,
    difficulty: 2,
    signals: [
      'You do not understand the clearance process',
      'You are not prepared for background checks',
    ],
    advice: {
      awareness: 'Security clearance investigations are thorough and take time.',
      understanding: 'The process includes: SF-86 form, background investigation, interview, polygraph (for TS).',
      application: 'Start gathering documents early.',
      readiness: 'You understand the timeline and requirements.',
      execution: 'Be honest and thorough in all documentation.',
      confidence: 'Being clearance-ready gives you access to government and contractor roles.',
    },
    tasks: OFFER_TASKS['clearance-process'] || [],
  },
  {
    id: 'resignation-letter',
    skill: 'Resignation Letter',
    domain: 'Offer Preparation',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You have no resignation letter template',
      'You are not prepared for resignation',
    ],
    advice: {
      awareness: 'Burning bridges is expensive. The security world is smaller than it looks.',
      understanding: 'A graceful exit preserves relationships and references for years.',
      application: 'Draft a professional resignation letter.',
      readiness: 'You can resign without drama.',
      execution: 'Give notice in person first, then follow up with written letter.',
      confidence: 'Professional exits open doors.',
    },
    tasks: OFFER_TASKS['resignation-letter'] || [],
  },
];

// ─── CHAPTER 6: OFFER (6 nodes) ──────────────────────────────────────
export const OFFER_SKILL_NODES: SkillNode[] = [
  {
    id: 'offer-evaluation',
    skill: 'Offer Evaluation',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You compare offers only on salary',
      'You have no evaluation framework',
    ],
    advice: {
      awareness: 'The highest salary is not always the best career move.',
      understanding: 'Security roles vary in: learning opportunities, tool exposure, team quality, clearance potential.',
      application: 'Create a weighted scorecard with multiple criteria.',
      readiness: 'You can justify your choice with specific criteria.',
      execution: 'Sleep on it and discuss with a mentor.',
      confidence: 'A structured evaluation prevents regret six months later.',
    },
    tasks: OFFER_TASKS['offer-evaluation'] || [],
  },
  {
    id: 'salary-negotiation',
    skill: 'Salary Negotiation',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You never negotiate',
      'You do not know market rates',
    ],
    advice: {
      awareness: 'Not negotiating costs you hundreds of thousands over a career.',
      understanding: 'Companies expect negotiation. Asking does not make you difficult.',
      application: 'Research market rates and script your negotiation.',
      readiness: 'You can ask for more without anxiety.',
      execution: 'Negotiate base, bonus, equity, signing bonus, and benefits.',
      confidence: 'Every dollar negotiated compounds over your career.',
    },
    tasks: OFFER_TASKS['salary-negotiation'] || [],
  },
  {
    id: 'decision-framework',
    skill: 'Decision Framework',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You decide on gut feeling',
      'You have no written priorities',
    ],
    advice: {
      awareness: 'Deciding between offers is stressful. A framework removes emotion.',
      understanding: 'Your priorities change over time. A framework adapts with you.',
      application: 'List your top 5 priorities and score each offer.',
      readiness: 'You can explain why one offer beats another.',
      execution: 'Set a deadline, gather input, decide, commit.',
      confidence: 'A clear framework makes you decisive, not impulsive.',
    },
    tasks: OFFER_TASKS['decision-framework'] || [],
  },
  {
    id: 'offer-acceptance',
    skill: 'Offer Acceptance',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 15,
    difficulty: 1,
    signals: [
      'You have not confirmed the offer in writing',
      'You do not understand start date requirements',
    ],
    advice: {
      awareness: 'Verbal acceptance is not binding. Written confirmation protects both sides.',
      understanding: 'A smooth start sets the tone for your entire tenure.',
      application: 'Send written acceptance and confirm all details.',
      readiness: 'You have a plan for your first week.',
      execution: 'Give notice professionally and wrap up current projects.',
      confidence: 'A professional transition builds reputation before day one.',
    },
    tasks: OFFER_TASKS['offer-acceptance'] || [],
  },
  {
    id: 'toolkit-setup',
    skill: 'Security Toolkit Setup',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 60,
    difficulty: 2,
    signals: [
      'You have not prepared your security tools',
      'Your lab is not ready for day one',
    ],
    advice: {
      awareness: 'A prepared toolkit shows initiative and readiness.',
      understanding: 'Different roles require different toolsets.',
      application: 'Research the company security stack and prepare accordingly.',
      readiness: 'Your tools are ready and configured before day one.',
      execution: 'Install, configure, and test your primary security tools.',
      confidence: 'A prepared toolkit accelerates your onboarding.',
    },
    tasks: OFFER_TASKS['toolkit-setup'] || [],
  },
  {
    id: 'start-transition',
    skill: 'Start Transition',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'You have no plan for your first 90 days',
      'You do not know what to expect',
    ],
    advice: {
      awareness: 'The first 90 days determine your trajectory at a new company.',
      understanding: 'Managers form opinions quickly. Early wins create momentum.',
      application: 'Create a 30-60-90 day plan.',
      readiness: 'You can articulate your first-month priorities on day one.',
      execution: 'Listen more than you speak in week 1.',
      confidence: 'A strong start turns a new job into a career accelerator.',
    },
    tasks: OFFER_TASKS['start-transition'] || [],
  },
];
