import type { SkillNode } from '@/core/skill_state';
import { RESUME_TASKS } from './tasks/resume';
import { LINKEDIN_TASKS } from './tasks/linkedin';
import { APPLICATION_TASKS } from './tasks/applications';
import { INTERVIEW_TASKS } from './tasks/interviews';
import { OFFER_TASKS } from './tasks/offer';

// ─── CHAPTER 1: RESUME (6 nodes) ──────────────────────────────────
export const RESUME_SKILL_NODES: SkillNode[] = [
  {
    id: 'positioning-clarity',
    skill: 'Positioning Clarity',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You can describe your target AI/ML role in one clear sentence',
      'Your resume headline matches "ML Engineer", "AI Engineer", or "Research Scientist"',
      'Your stack includes Python, PyTorch/TensorFlow, and cloud ML platforms',
    ],
    advice: {
      awareness: 'An AI/ML resume without clear positioning looks like a generic software engineer. Define your niche: NLP, CV, MLOps, or Generative AI.',
      understanding: 'Recruiters scan for: framework expertise, model types deployed, dataset sizes handled, and business metrics improved.',
      application: 'Analyze 5 AI/ML job postings. Extract common requirements: PyTorch, LLMs, vector DBs, model serving, A/B testing.',
      readiness: 'You can state your target role, primary framework, and domain specialization in one sentence.',
      execution: 'Every resume section reinforces the same AI/ML positioning.',
      confidence: 'A focused AI/ML resume answers "Can this person ship models to production?" immediately.',
    },
    tasks: RESUME_TASKS['positioning-clarity'] || [],
  },
  {
    id: 'ml-skills-matrix',
    skill: 'ML Skills Matrix',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have rated your PyTorch/TensorFlow proficiency on a 1-5 scale',
      'You can list 3 model architectures you have implemented',
      'You have quantified at least one model performance metric you achieved',
    ],
    advice: {
      awareness: 'Listing "Python, ML, DL" is not enough. Recruiters want depth: which models, which datasets, which metrics?',
      understanding: 'A skills matrix shows progression: implemented → trained → optimized → deployed → monitored.',
      application: 'Create a table: Skill | Level | Last Used | Model/Dataset | Metric Achieved.',
      readiness: 'You can defend every skill rating with a specific model, dataset, and evaluation metric.',
      execution: 'Place the matrix prominently. AI hiring managers scan for framework names and model types first.',
      confidence: 'An honest skills matrix builds trust faster than inflated claims.',
    },
    tasks: RESUME_TASKS['ml-skills-matrix'] || [],
  },
  {
    id: 'resume-structure',
    skill: 'Resume Structure',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 25,
    difficulty: 1,
    signals: [
      'Your resume has a clear header with contact info, LinkedIn, GitHub, and Kaggle',
      'Experience bullets follow STAR method with ML metrics: accuracy, latency, throughput',
      'Projects section includes model cards and dataset descriptions',
    ],
    advice: {
      awareness: 'A poorly structured AI resume hides your Transformer experience behind irrelevant formatting.',
      understanding: 'AI recruiters scan for: frameworks, model architectures, dataset sizes, and deployment platforms.',
      application: 'Reformat one bullet: "Trained ResNet-50 on 100K images achieving 94% accuracy, deployed to AWS SageMaker with 200ms latency."',
      readiness: 'A recruiter can find your top framework and best model metric within 6 seconds.',
      execution: 'Use clean, single-column format. AI roles often use startup ATS and manual review.',
      confidence: 'Clean structure signals you can organize experiments and present results clearly.',
    },
    tasks: RESUME_TASKS['resume-structure'] || [],
  },
  {
    id: 'projects-portfolio',
    skill: 'Projects Portfolio',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 3,
    signals: [
      'You have 2-3 ML projects with public GitHub repos and READMEs',
      'Each project includes: problem statement, dataset, model architecture, results, deployment',
      'Projects use real or realistic datasets, not just MNIST or Iris',
    ],
    advice: {
      awareness: 'Without projects, junior AI/ML engineers have no proof they can train and deploy models.',
      understanding: 'A portfolio project is worth more than a certificate. It shows end-to-end ML thinking.',
      application: 'Pick one dataset you care about. EDA, feature engineering, model selection, hyperparameter tuning, deployment.',
      readiness: 'You can walk through your project in 3 minutes: problem, approach, model choice, metric, deployment.',
      execution: 'Host on GitHub with README. Include Colab/Kaggle links, model card, and live demo if possible.',
      confidence: 'Projects turn "I learned PyTorch" into "Here is the LLM fine-tuning pipeline I built."',
    },
    tasks: RESUME_TASKS['projects-portfolio'] || [],
  },
  {
    id: 'model-deployment-stories',
    skill: 'Model Deployment Stories',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 35,
    difficulty: 2,
    signals: [
      'Every experience bullet describes a model you deployed to production',
      'Stories follow: Problem → Model → Metric → Deployment → Business Impact',
      'You have quantified impact: latency reduction, cost savings, accuracy improvement',
    ],
    advice: {
      awareness: '"Built a model" is weak. "Deployed a BERT-based classifier reducing ticket routing time by 40%" is strong.',
      understanding: 'Deployment stories show: model selection, optimization, serving infrastructure, and business value.',
      application: 'Rewrite 3 bullets as deployment stories: what was the problem, what model, what metric, where deployed, what impact.',
      readiness: 'You can tell each story in 2 minutes with technical depth and business context.',
      execution: 'Use action verbs: trained, optimized, deployed, monitored, A/B tested.',
      confidence: 'Deployment stories prove you can bridge research and production.',
    },
    tasks: RESUME_TASKS['model-deployment-stories'] || [],
  },
  {
    id: 'resume-ats',
    skill: 'ATS Optimization',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'Your resume has no tables, columns, or graphics that confuse ATS',
      'Keywords from AI/ML job postings appear naturally: PyTorch, TensorFlow, LLM, MLOps, vector DB',
      'File format is PDF with selectable text',
    ],
    advice: {
      awareness: 'A beautiful resume that ATS rejects is useless. Big tech and startups both use ATS.',
      understanding: 'ATS scans for: frameworks, model types, cloud platforms, and standard section headings.',
      application: 'Paste your resume into a plain text editor. Check for garbled text and correct order.',
      readiness: 'Your resume parses cleanly with all AI/ML keywords intact.',
      execution: 'Use standard headings: Skills, Experience, Projects, Education. No icons, no text boxes.',
      confidence: 'An ATS-optimized resume reaches AI recruiters and hiring managers consistently.',
    },
    tasks: RESUME_TASKS['resume-ats'] || [],
  },
];

// ─── CHAPTER 2: LINKEDIN (6 nodes) ──────────────────────────────────
export const LINKEDIN_SKILL_NODES: SkillNode[] = [
  {
    id: 'headline-authority',
    skill: 'Headline Authority',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 15,
    difficulty: 1,
    signals: [
      'Your headline says "ML Engineer" or "AI Engineer" not "Data Scientist" or "Software Developer"',
      'Headline includes a specific domain: NLP, Computer Vision, Generative AI, MLOps',
      'You have a clear value proposition in 120 characters',
    ],
    advice: {
      awareness: 'A weak headline makes you invisible to AI recruiters searching for "LLM Engineer" or "PyTorch Developer".',
      understanding: 'LinkedIn search weights headline heavily. AI keywords matter more than creativity.',
      application: 'Write 5 headline variants. Test them with an AI recruiter or career coach.',
      readiness: 'Your headline contains: role, domain, and one framework or model type.',
      execution: 'Update headline. Remove "seeking", "open to work". Add "PyTorch" or "LLMs" if applicable.',
      confidence: 'A strong headline attracts inbound recruiter messages for AI roles.',
    },
    tasks: LINKEDIN_TASKS['headline-authority'] || [],
  },
  {
    id: 'about-section',
    skill: 'About Section',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 25,
    difficulty: 2,
    signals: [
      'Your About tells an AI career story, not just lists frameworks',
      'It includes a specific model you built and the business problem it solved',
      'It ends with a clear call to action and research interests',
    ],
    advice: {
      awareness: 'A blank About section wastes prime LinkedIn real estate. AI recruiters read it for research depth.',
      understanding: 'The About section is your narrative: who you are, what models you build, what problems you solve.',
      application: 'Write 200 words: background, key model/deployment, research interests, what you are looking for.',
      readiness: 'A stranger understands your AI specialty after reading your About.',
      execution: 'Use first person. Include one model metric. End with "Open to ML Engineer roles in NLP/GenAI".',
      confidence: 'A compelling About turns profile views into connection requests from AI leads.',
    },
    tasks: LINKEDIN_TASKS['about-section'] || [],
  },
  {
    id: 'network-connections',
    skill: 'Network Connections',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'You have 500+ connections including AI researchers, ML engineers, and hiring managers',
      'You engage weekly with AI content: papers, model releases, conference talks',
      'You have joined 3+ AI/ML LinkedIn groups or communities',
    ],
    advice: {
      awareness: 'A small network limits your visibility to AI opportunities. Most AI roles are filled through referrals.',
      understanding: 'AI hiring is relationship-driven. Conference connections, paper co-authors, and open-source collaborators matter.',
      application: 'Connect with 10 AI professionals weekly. Comment thoughtfully on their posts about models and papers.',
      readiness: 'Your network includes people at your target companies who know your work.',
      execution: 'Share your Kaggle solutions, paper summaries, or model fine-tuning experiments weekly.',
      confidence: 'An active AI network brings opportunities before they are posted publicly.',
    },
    tasks: LINKEDIN_TASKS['network-connections'] || [],
  },
  {
    id: 'kaggle-showcase',
    skill: 'Kaggle Showcase',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 40,
    difficulty: 2,
    signals: [
      'Your Featured section includes 2+ Kaggle competitions with rankings',
      'Each competition has a write-up explaining your approach and model choice',
      'You have linked your Kaggle profile and top notebooks',
    ],
    advice: {
      awareness: 'Kaggle medals are credible proof of ML skill. They validate you can compete with top practitioners.',
      understanding: 'Recruiters value Kaggle because it shows: feature engineering, model tuning, and leaderboard pressure.',
      application: 'Add 2 competitions to Featured. Write 100 words on approach, model, and lesson learned for each.',
      readiness: 'Your Kaggle profile is public and includes notebooks with clear explanations.',
      execution: 'Pin your best competition and most-downloaded dataset or notebook.',
      confidence: 'Kaggle showcase proves you can build models that perform under competitive evaluation.',
    },
    tasks: LINKEDIN_TASKS['kaggle-showcase'] || [],
  },
  {
    id: 'research-publications',
    skill: 'Research Publications',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 35,
    difficulty: 3,
    signals: [
      'Your Featured section includes papers, preprints, or technical blog posts',
      'Each publication has a 2-sentence summary for non-experts',
      'You have linked arXiv, Medium, or company engineering blog',
    ],
    advice: {
      awareness: 'Publications signal research depth. Even blog posts about model implementations show expertise.',
      understanding: 'AI recruiters look for: paper quality, reproducibility, and ability to communicate complex ideas.',
      application: 'Add 1 paper or 2 blog posts to Featured. Write layman summaries for each.',
      readiness: 'A non-technical recruiter can understand your contribution from the summary.',
      execution: 'Link to GitHub repos that reproduce paper results. Show code, not just claims.',
      confidence: 'Research publications differentiate you from engineers who only use APIs.',
    },
    tasks: LINKEDIN_TASKS['research-publications'] || [],
  },
  {
    id: 'certifications-display',
    skill: 'Certifications Display',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'Your Licenses section includes AWS ML Specialty, TensorFlow Developer, or equivalent',
      'Each certification is linked to the verifying organization',
      'You have added skill badges for PyTorch, Keras, and cloud ML platforms',
    ],
    advice: {
      awareness: 'Certifications validate structured learning. They help non-technical recruiters assess your stack.',
      understanding: 'AWS ML Specialty and TensorFlow Developer are most recognized in industry AI roles.',
      application: 'Add all relevant certifications. Link to credential IDs. Add skill assessments for frameworks.',
      readiness: 'Your certifications match the requirements in your target job postings.',
      execution: 'Prioritize cloud ML and framework certs over generic "Data Science" certificates.',
      confidence: 'Certifications provide credibility when you lack years of production ML experience.',
    },
    tasks: LINKEDIN_TASKS['certifications-display'] || [],
  },
];

// ─── CHAPTER 3: APPLICATIONS (7 nodes) ──────────────────────────────
export const APPLICATION_SKILL_NODES: SkillNode[] = [
  {
    id: 'application-tracking',
    skill: 'Application Tracking',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have a spreadsheet tracking 20+ AI/ML job applications',
      'Each entry includes: company, team, model type, date, status',
      'You follow up on 50% of applications within 1 week',
    ],
    advice: {
      awareness: 'Applying blindly to AI roles is inefficient. Tracking reveals which companies value your specialty.',
      understanding: 'A tracker shows patterns: which teams respond, which model types are in demand, which channels work.',
      application: 'Create a tracker with columns: Company, Team, Role, Model Type, Date Applied, Status, Follow-up, Notes.',
      readiness: 'You can see your pipeline: applied, phone screen, ML take-home, onsite, offer.',
      execution: 'Set weekly review. Archive rejected roles. Prioritize teams building models you know.',
      confidence: 'A tracked pipeline turns chaos into an AI job search strategy.',
    },
    tasks: APPLICATION_TASKS['application-tracking'] || [],
  },
  {
    id: 'portfolio-github',
    skill: 'GitHub Portfolio',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 2,
    signals: [
      'Your GitHub has 3+ pinned ML repos with clear READMEs',
      'Each repo includes: problem, dataset, model, metric, deployment',
      'You have 100+ commits showing consistent coding activity',
    ],
    advice: {
      awareness: 'A sparse GitHub profile hurts AI applications. Recruiters check your code quality and project depth.',
      understanding: 'GitHub is your portfolio. It shows: code style, documentation habits, and project complexity.',
      application: 'Pin 3 best repos. Add README with architecture diagram, model card, and running instructions.',
      readiness: 'A stranger can clone, run, and understand your project in 10 minutes.',
      execution: 'Include requirements.txt, Dockerfile, and demo notebook. Show you think about reproducibility.',
      confidence: 'A strong GitHub turns "I know PyTorch" into "Here is my production-ready model repo."',
    },
    tasks: APPLICATION_TASKS['portfolio-github'] || [],
  },
  {
    id: 'ml-competition-scores',
    skill: 'ML Competition Scores',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have Kaggle, DrivenData, or AI Challenge rankings in top 20%',
      'Each competition has a write-up on your approach and model architecture',
      'You can explain your solution in an interview with technical depth',
    ],
    advice: {
      awareness: 'Competition rankings prove you can optimize models under pressure. They are credible interview talking points.',
      understanding: 'Recruiters value competitions because they show: feature creativity, ensemble strategies, and metric focus.',
      application: 'Document 2 competitions with: problem, EDA, model, ensemble, final rank, lesson learned.',
      readiness: 'You can explain your solution in 5 minutes with code snippets and visualizations.',
      execution: 'Include competition write-ups in your application. Link to repos with full code.',
      confidence: 'Competition scores validate your ability to beat baseline models systematically.',
    },
    tasks: APPLICATION_TASKS['ml-competition-scores'] || [],
  },
  {
    id: 'company-research',
    skill: 'Company Research',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 35,
    difficulty: 1,
    signals: [
      'You know the AI team structure at your target companies',
      'You can name their models, papers, or products using ML',
      'You have identified 2-3 teams that match your specialty',
    ],
    advice: {
      awareness: 'Generic AI applications fail. Teams want candidates who understand their model challenges.',
      understanding: 'Research reveals: model types, infrastructure, team size, and research vs product balance.',
      application: 'Read company engineering blogs. Find their ML papers. Check LinkedIn for team members.',
      readiness: 'You can ask informed questions about their model serving infrastructure or training pipelines.',
      execution: 'Tailor your cover letter to their specific ML challenges, not generic "AI is exciting".',
      confidence: 'Informed applications show you can research and adapt, key skills for ML roles.',
    },
    tasks: APPLICATION_TASKS['company-research'] || [],
  },
  {
    id: 'application-tailoring',
    skill: 'Application Tailoring',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 25,
    difficulty: 2,
    signals: [
      'Every resume you send highlights skills matching the job description',
      'Your cover letter mentions their models, infrastructure, or papers',
      'You have customized your project portfolio for the role type',
    ],
    advice: {
      awareness: 'A generic AI application is a rejection. Teams receive hundreds of "I love AI" resumes.',
      understanding: 'Tailoring shows: you read the job post, you understand their stack, you have relevant experience.',
      application: 'Match 3 skills from the job description to your projects. Rewrite bullets to use their keywords.',
      readiness: 'Every application has a clear link between their requirements and your proven skills.',
      execution: 'Spend 15 minutes per application. It is better than 50 generic applications.',
      confidence: 'Tailored applications get 3x more responses in competitive AI hiring.',
    },
    tasks: APPLICATION_TASKS['application-tailoring'] || [],
  },
  {
    id: 'referral-strategy',
    skill: 'Referral Strategy',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 40,
    difficulty: 2,
    signals: [
      'You have identified 2-3 potential referrers at each target company',
      'Your outreach message is specific about their work and your interest',
      'You have offered value first: feedback, code review, or paper summary',
    ],
    advice: {
      awareness: 'Referrals bypass ATS and get priority review. In AI, they often come from paper co-authors or open-source.',
      understanding: 'Good referrers are: former colleagues, conference connections, open-source collaborators, Kaggle teammates.',
      application: 'Find team members on LinkedIn. Engage with their posts. Ask for a 15-minute chat about their models.',
      readiness: 'Your referrer knows your work and can speak to your ML abilities specifically.',
      execution: 'Do not ask for a referral in the first message. Build relationship first, ask after 2-3 interactions.',
      confidence: 'A warm referral from an ML engineer is the strongest signal to hiring managers.',
    },
    tasks: APPLICATION_TASKS['referral-strategy'] || [],
  },
  {
    id: 'open-source-contributions',
    skill: 'Open Source Contributions',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 50,
    difficulty: 3,
    signals: [
      'You have 3+ merged PRs in ML libraries: HuggingFace, scikit-learn, PyTorch',
      'Each PR has a clear issue description and test coverage',
      'You can explain the technical problem and your solution in an interview',
    ],
    advice: {
      awareness: 'Open-source contributions prove you can read complex ML code and collaborate with researchers.',
      understanding: 'Recruiters value OSS because it shows: code review skills, testing habits, and community engagement.',
      application: 'Find 3 good-first-issues in HuggingFace or PyTorch. Submit PRs with tests and documentation.',
      readiness: 'You can explain your PR in 3 minutes: problem, approach, trade-offs, and review feedback.',
      execution: 'Document contributions on your resume and LinkedIn. Link to PRs with line counts.',
      confidence: 'OSS contributions signal you are part of the ML community, not just a consumer of APIs.',
    },
    tasks: APPLICATION_TASKS['open-source-contributions'] || [],
  },
];

// ─── CHAPTER 4: INTERVIEWS (10 nodes) ─────────────────────────────
export const INTERVIEW_SKILL_NODES: SkillNode[] = [
  // ─── CHAPTER 4: INTERVIEWS (continued) ─────────────────────────────
  {
    id: 'on-site-prep',
    skill: 'On-Site Preparation',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have a checklist for on-site logistics: travel, attire, materials',
      'You have prepared a portfolio of projects to present live',
      'You have rehearsed whiteboard coding and system design on a physical board',
    ],
    advice: {
      awareness: 'On-site interviews test more than coding: communication, culture fit, and presentation skills.',
      understanding: 'ML on-sites often include: coding, system design, research presentation, and team lunch.',
      application: 'Prepare a 10-minute research presentation on a project you led.',
      readiness: 'You can whiteboard an ML pipeline end-to-end in 30 minutes.',
      execution: 'Bring a laptop with demo-ready notebooks. Test the projector beforehand.',
      confidence: 'On-site preparation turns anxiety into structured performance.',
    },
    tasks: [],
  },
  {
    id: 'research-presentation',
    skill: 'Research Presentation',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 3,
    signals: [
      'You have a 10-minute slide deck explaining one ML project',
      'You can answer deep technical questions about model choice and evaluation',
      'You have practiced presenting to a non-technical audience',
    ],
    advice: {
      awareness: 'Research roles require you to defend your work like a thesis defense.',
      understanding: 'Presentation structure: Problem → Data → Model → Results → Lessons → Next Steps.',
      application: 'Build a deck with 8-10 slides. Include architecture diagrams and training curves.',
      readiness: 'You can present without reading slides and handle interruptions gracefully.',
      execution: 'Time yourself: 10 minutes strict. Anticipate 5 hard questions per slide.',
      confidence: 'A polished presentation signals you can communicate complex ideas clearly.',
    },
    tasks: [],
  },
  {
    id: 'interview-followup',
    skill: 'Interview Follow-Up',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 15,
    difficulty: 1,
    signals: [
      'You send personalized thank-you emails within 24 hours',
      'You reference specific conversation topics from the interview',
      'You reiterate your interest and fit for the role',
    ],
    advice: {
      awareness: 'Silence after an interview does not mean rejection. Follow-up shows professionalism.',
      understanding: 'A good follow-up email: thanks, specific reference, reiteration of interest, next steps.',
      application: 'Draft a template. Customize for each interviewer within 24 hours.',
      readiness: 'You have a tracking system for all sent follow-ups and responses.',
      execution: 'Send within 24h. Keep it under 150 words. One specific detail per interviewer.',
      confidence: 'Follow-up separates candidates who want the job from those who just interviewed.',
    },
    tasks: [],
  },

// ─── CHAPTER 5: OFFER PREPARATION ──────────────────────────────────
  {
    id: 'salary-research-ml',
    skill: 'ML Salary Research',
    domain: 'Offer Preparation',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 25,
    difficulty: 2,
    signals: [
      'You know salary ranges for your role, level, and location from Levels.fyi and Glassdoor',
      'You understand equity components: RSUs, options, refreshers',
      'You have researched ML-specific premiums: PhD bonus, research lab rates',
    ],
    advice: {
      awareness: 'ML engineers command 20-40% premiums over standard software engineers. Know your market value.',
      understanding: 'Compensation = Base + Equity + Bonus + Benefits. ML roles often have higher equity.',
      application: 'Research 10 comparable roles on Levels.fyi. Document base, equity, and total comp.',
      readiness: 'You can state your target range with data-backed justification.',
      execution: 'Create a spreadsheet: Company | Level | Base | Equity | Total | Source.',
      confidence: 'Data-driven negotiation starts with knowing what others at your level earn.',
    },
    tasks: [],
  },
  {
    id: 'equity-negotiation',
    skill: 'Equity Negotiation',
    domain: 'Offer Preparation',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 3,
    signals: [
      'You understand the difference between ISOs, NSOs, and RSUs',
      'You can calculate the value of an equity package at current and future valuations',
      'You know the tax implications of exercising options',
    ],
    advice: {
      awareness: 'Equity can be worth more than salary in startups. Understand what you are signing.',
      understanding: 'Key terms: strike price, vesting schedule, cliff, acceleration, 83(b) election.',
      application: 'Model 3 scenarios: company fails, exits at 2x, exits at 10x. What is your equity worth?',
      readiness: 'You can explain equity terms to a non-technical friend in 2 minutes.',
      execution: 'Negotiate for refreshers, acceleration on change of control, and early exercise.',
      confidence: 'Equity literacy turns you from an employee into a potential owner.',
    },
    tasks: [],
  },
  {
    id: 'resignation-letter',
    skill: 'Resignation Letter',
    domain: 'Offer Preparation',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You have a professional resignation letter template ready',
      'You know your notice period and transition plan',
      'You have prepared answers for counter-offer conversations',
    ],
    advice: {
      awareness: 'How you leave matters as much as how you arrive. Burn no bridges.',
      understanding: 'A good resignation: gratitude, clear date, brief reason, offer to help transition.',
      application: 'Draft your letter. Schedule a private meeting with your manager before sending.',
      readiness: 'You can handle a counter-offer without emotional decision-making.',
      execution: 'Give standard notice. Document your work. Train your replacement if possible.',
      confidence: 'A graceful exit preserves relationships and references for decades.',
    },
    tasks: [],
  },

// ─── CHAPTER 6: OFFER ──────────────────────────────────────────────
  {
    id: 'offer-evaluation',
    skill: 'Offer Evaluation',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have a weighted scoring system for offer components',
      'You compare offers on total compensation, growth, team, and research freedom',
      'You have consulted mentors or peers on your top 2 offers',
    ],
    advice: {
      awareness: 'The highest salary is not always the best offer. Consider trajectory, team, and research budget.',
      understanding: 'ML offer factors: GPU access, publication policy, conference budget, data availability, team seniority.',
      application: 'Create a scorecard: Compensation | Team | Tech | Growth | Research | Culture | Location.',
      readiness: 'You can explain your choice to yourself, your family, and a mentor.',
      execution: 'Sleep on it. Negotiate the weak points of your preferred offer before accepting.',
      confidence: 'A structured evaluation prevents regret six months later.',
    },
    tasks: [],
  },
  {
    id: 'salary-negotiation',
    skill: 'Salary Negotiation',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 25,
    difficulty: 2,
    signals: [
      'You have a target range and a walk-away number',
      'You can justify your ask with market data and your unique skills',
      'You practice negotiation scripts with a friend or mentor',
    ],
    advice: {
      awareness: 'Negotiation is expected. Not negotiating leaves 10-20% of lifetime earnings on the table.',
      understanding: 'Anchor high, justify with data, be silent after stating your number, and negotiate total comp not just base.',
      application: 'Practice the script: "Based on my research and experience, I am targeting X-Y total comp."',
      readiness: 'You can handle objections without emotional reaction or immediate concession.',
      execution: 'Negotiate base, equity, and signing bonus separately. Get the best package, not the best single number.',
      confidence: 'Every dollar negotiated now compounds over your career.',
    },
    tasks: [],
  },
  {
    id: 'decision-framework',
    skill: 'Decision Framework',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You have a written framework for career decisions',
      'You weight short-term gain against long-term growth',
      'You have a \"no regrets\" threshold for walking away',
    ],
    advice: {
      awareness: 'Career decisions are irreversible. A framework prevents emotional choices.',
      understanding: 'Good framework: 1-year impact, 3-year impact, 10-year impact, regret minimization.',
      application: 'Write your decision criteria before receiving offers. Stick to them.',
      readiness: 'You can explain your choice to your future self in 10 years.',
      execution: 'Set a deadline. Consult 2 trusted advisors. Make the call and move forward.',
      confidence: 'A framework turns anxiety into clarity and action.',
    },
    tasks: [],
  },
  {
    id: 'offer-acceptance',
    skill: 'Offer Acceptance',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 15,
    difficulty: 1,
    signals: [
      'You have reviewed the offer letter line by line',
      'You understand all clauses: non-compete, IP assignment, at-will employment',
      'You have confirmed start date and onboarding details in writing',
    ],
    advice: {
      awareness: 'The offer letter is a contract. Read every word before signing.',
      understanding: 'Red flags: overly broad non-competes, vague IP clauses, no equity vesting schedule.',
      application: 'Have a lawyer or experienced friend review the letter if anything is unclear.',
      readiness: 'You can explain every clause to yourself and feel confident signing.',
      execution: 'Sign and return within 48 hours. Confirm start date, equipment, and first-week schedule.',
      confidence: 'A careful acceptance sets the tone for a professional relationship.',
    },
    tasks: [],
  },
  {
    id: 'research-budget',
    skill: 'Research Budget',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 2,
    signals: [
      'You have negotiated GPU/cloud compute budget for your projects',
      'You understand conference travel and publication budget policies',
      'You have clarity on IP ownership for side projects and publications',
    ],
    advice: {
      awareness: 'ML roles require compute resources. A $10K GPU budget can be worth more than a $10K salary bump.',
      understanding: 'Negotiate: cloud credits, GPU allocation, conference budget, publication rights, open-source time.',
      application: 'Research what comparable roles offer: AWS credits, GCP allocation, conference allowance.',
      readiness: 'You can articulate why compute and research budget matter for your productivity.',
      execution: 'Ask during negotiation, not after acceptance. Get it in the offer letter.',
      confidence: 'Research budget negotiation signals you understand what ML work actually requires.',
    },
    tasks: [],
  },
  {
    id: 'start-transition',
    skill: 'Start Transition',
    domain: 'Offer',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'You have a 30-60-90 day plan for your new ML role',
      'You have identified key stakeholders and onboarding resources',
      'You have scheduled check-ins with your manager for weeks 1, 4, and 12',
    ],
    advice: {
      awareness: 'The first 90 days define your trajectory. Plan them before you start.',
      understanding: 'ML onboarding: environment setup, data access, model repository, experiment tracking, team rituals.',
      application: 'Draft a 30-60-90 plan: learn | contribute | lead. Share it with your manager on day 1.',
      readiness: 'You can name 3 people you will build relationships with in your first month.',
      execution: 'Set up your dev environment before day 1. Read the team\'s latest papers and models.',
      confidence: 'A planned start turns new-job anxiety into structured momentum.',
    },
    tasks: [],
  },