import type { SkillNode } from '@/core/skill_state';
import { RESUME_TASKS } from './tasks/resume';
import { LINKEDIN_TASKS } from './tasks/linkedin';

// ─── CHAPTER 1: RESUME (6 nodes) ──────────────────────────────────
export const RESUME_SKILL_NODES: SkillNode[] = [
  {
    id: 'positioning-clarity',
    skill: 'Positioning Clarity',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You can describe your target ML role in one clear sentence',
      'Your resume headline matches "ML Engineer", "Applied Scientist", or "MLOps Engineer"',
      'Your tech stack includes a modeling framework and at least one deployment tool',
    ],
    advice: {
      awareness: 'An ML resume without clear positioning looks like a generic data enthusiast. Define your specialization.',
      understanding: 'Recruiters scan for: modeling framework, domain (NLP/CV/recommenders), and deployment experience. Not just "interested in AI".',
      application: 'Analyze 5 ML job postings. Extract common tools: PyTorch, TensorFlow, MLflow, SageMaker, etc.',
      readiness: 'You can state your target role, primary framework, and domain: NLP, computer vision, recommenders, or MLOps.',
      execution: 'Every resume section reinforces the same ML positioning.',
      confidence: 'A focused ML resume answers "Can this person ship a model that works?" immediately.',
    },
    tasks: RESUME_TASKS['positioning-clarity'] || [],
  },
  {
    id: 'ml-skills-matrix',
    skill: 'Skills Matrix',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have rated your framework proficiency on a 1-5 scale',
      'You can list 3 modeling and 3 MLOps tools you have used',
      'You have quantified at least one model result you shipped',
    ],
    advice: {
      awareness: 'Listing "PyTorch, pandas, Docker" is not enough. Recruiters want depth: tutorial, project, or production?',
      understanding: 'A skills matrix shows progression: followed tutorials → built projects → trained production models → owned pipelines.',
      application: 'Create a table: Tool | Type (Modeling/MLOps) | Level | Last Used | Project/Result Example.',
      readiness: 'You can defend every skill rating with a specific project or metric.',
      execution: 'Place the matrix prominently. ML hiring managers scan for framework and tool names first.',
      confidence: 'A honest skills matrix builds trust faster than inflated claims.',
    },
    tasks: RESUME_TASKS['ml-skills-matrix'] || [],
  },
  {
    id: 'resume-structure',
    skill: 'Resume Structure',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 25,
    difficulty: 1,
    signals: [
      'Your resume has a clear header with contact info, LinkedIn, and GitHub',
      'Experience bullets follow a problem-approach-result structure with model metrics',
      'Projects section includes at least one end-to-end pipeline, not just notebooks',
    ],
    advice: {
      awareness: 'A poorly structured ML resume hides your modeling experience behind formatting noise.',
      understanding: 'ML recruiters scan for: frameworks, metrics improved, models deployed, in that order.',
      application: 'Reformat one bullet: "Trained and deployed a churn model improving recall 18% while cutting inference cost 30%."',
      readiness: 'Every bullet has an ML metric: accuracy/AUC gain, latency, cost, or business KPI.',
      execution: 'Use a clean, single-column format that ATS parses correctly.',
      confidence: 'A structured resume tells a coherent ML career story.',
    },
    tasks: RESUME_TASKS['resume-structure'] || [],
  },
  {
    id: 'ml-portfolio-showcase',
    skill: 'ML Portfolio Showcase',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 3,
    signals: [
      'You have a documented ML portfolio with a pipeline diagram',
      'Portfolio includes: a training pipeline, model serving, and evaluation dashboards',
      'You have 2+ writeups of projects you built end-to-end',
    ],
    advice: {
      awareness: 'ML resumes without a real portfolio look theoretical. Show you have hands-on, end-to-end experience.',
      understanding: 'A portfolio proves you can build, train, evaluate, and deploy real models. Not just run tutorials.',
      application: 'Build one end-to-end project: data ingestion, training, evaluation, and a simple serving API.',
      readiness: 'You can walk through your portfolio in 3 minutes: problem, approach, pipeline, results.',
      execution: 'Link to GitHub with pipeline diagram, README, and evaluation writeups.',
      confidence: 'A portfolio turns "I am interested in ML" into "Here is what I have shipped."',
    },
    tasks: RESUME_TASKS['ml-portfolio-showcase'] || [],
  },
  {
    id: 'model-impact-stories',
    skill: 'Model Impact Stories',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 35,
    difficulty: 2,
    signals: [
      'Every experience bullet describes a model or pipeline you shipped',
      'Stories follow: Problem → Approach → Iteration → Result',
      'You have quantified impact: metric improvement, latency, cost, or revenue',
    ],
    advice: {
      awareness: '"Built a model" is weak. "Shipped a fraud model that cut false positives 40% while maintaining recall" is strong.',
      understanding: 'Model impact stories show: problem understanding, iteration discipline, and business impact.',
      application: 'Rewrite 3 bullets as impact stories: what was the problem, what did you try, what was the outcome.',
      readiness: 'You can tell each story in 2 minutes with technical depth and business context.',
      execution: 'Use action verbs: trained, deployed, optimized, validated, scaled.',
      confidence: 'Model impact stories prove you can ship, not just experiment.',
    },
    tasks: RESUME_TASKS['model-impact-stories'] || [],
  },
  {
    id: 'resume-ats',
    skill: 'ATS Optimization',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'Your resume has no tables, columns, or graphics that confuse ATS',
      'Keywords from ML job postings appear naturally: PyTorch, MLOps, NLP, LLM, CI/CD',
      'File format is PDF with selectable text',
    ],
    advice: {
      awareness: 'A beautiful resume that ATS rejects is useless. Many companies still screen with ATS before a human looks.',
      understanding: 'ATS scans for: frameworks, domain keywords, and standard section headings.',
      application: 'Paste your resume into a plain text editor. Check for garbled text and correct order.',
      readiness: 'Your resume parses cleanly with all ML keywords intact.',
      execution: 'Use standard headings: Skills, Experience, Projects, Education. No icons, no text boxes.',
      confidence: 'An ATS-optimized resume reaches ML recruiters and hiring systems.',
    },
    tasks: RESUME_TASKS['resume-ats'] || [],
  },
];

// ─── CHAPTER 2: LINKEDIN (6 nodes) ──────────────────────────────────
export const LINKEDIN_SKILL_NODES: SkillNode[] = [
  {
    id: 'headline-authority',
    skill: 'Headline Authority',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 15,
    difficulty: 1,
    signals: [
      'Your headline says "ML Engineer" or "Applied Scientist" not "AI Enthusiast"',
      'Headline includes a specific domain: NLP, Computer Vision, MLOps, Recommender Systems',
      'You have a clear value proposition in 120 characters',
    ],
    advice: {
      awareness: 'A weak headline makes you invisible to ML recruiters searching for "ML Engineer" or "Applied Scientist".',
      understanding: 'LinkedIn search weights headline heavily. ML keywords matter more than creativity.',
      application: 'Write 5 headline variants. Test them with a mentor or peer in ML.',
      readiness: 'Your headline contains: role, domain, and one standout signal (competition rank, metric, publication).',
      execution: 'Update headline. Remove "seeking", "open to work", and emojis unless purposeful.',
      confidence: 'A strong headline attracts inbound recruiter messages for ML roles.',
    },
    tasks: LINKEDIN_TASKS['headline-authority'] || [],
  },
  {
    id: 'about-section',
    skill: 'About Section',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 25,
    difficulty: 2,
    signals: [
      'Your About section tells an ML career story, not just lists skills',
      'It includes a specific project or competition result',
      'It ends with a clear call to action about roles you want',
    ],
    advice: {
      awareness: 'A blank About section wastes prime LinkedIn real estate. ML recruiters read it for narrative and fit.',
      understanding: 'The About section is your elevator pitch: who you are, what you have built, what you want.',
      application: 'Write 3 paragraphs: background, key project or competition result, what you are looking for.',
      readiness: 'You can read your About section aloud in under 30 seconds.',
      execution: 'Use first person. Include one specific metric. End with the roles/domains you are targeting.',
      confidence: 'A compelling About section turns profile views into connection requests from hiring managers.',
    },
    tasks: LINKEDIN_TASKS['about-section'] || [],
  },
  {
    id: 'network-connections',
    skill: 'Network Connections',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have 50+ connections in ML: engineers, scientists, hiring managers',
      'You engage with posts from ML leaders weekly',
      'You have requested informational interviews with 3+ ML practitioners',
    ],
    advice: {
      awareness: 'A small network limits your ML job pipeline. Many ML roles are filled through referrals.',
      understanding: 'Quality connections > quantity. Target ML engineers, applied scientists, and hiring managers.',
      application: 'Send 5 personalized connection requests this week. Mention a shared paper, competition, or project.',
      readiness: 'You have a warm connection at 3 target companies.',
      execution: 'Comment thoughtfully on technical posts. Share your own project results.',
      confidence: 'A strong network surfaces hidden ML opportunities before they are posted.',
    },
    tasks: LINKEDIN_TASKS['network-connections'] || [],
  },
  {
    id: 'kaggle-writeups',
    skill: 'Kaggle Writeups',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 40,
    difficulty: 3,
    signals: [
      'You have published 3+ competition or project writeups on LinkedIn or Medium',
      'Each writeup includes: problem, approach, result, and lessons learned',
      'Writeups demonstrate both modeling and iteration skill',
    ],
    advice: {
      awareness: 'Kaggle writeups are an ML portfolio that lives where recruiters already are.',
      understanding: 'A well-written writeup proves technical depth, persistence, and knowledge sharing.',
      application: 'Write your first writeup: "How I approached [competition/project] using [technique]."',
      readiness: 'You have 3 writeups that you can reference in interviews.',
      execution: 'Include plots, code snippets, and lessons learned. Tag #Kaggle #MachineLearning.',
      confidence: 'Writeups turn your profile into a content hub that attracts ML recruiters.',
    },
    tasks: LINKEDIN_TASKS['kaggle-writeups'] || [],
  },
  {
    id: 'ml-blog',
    skill: 'ML Blog',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 3,
    signals: [
      'You have published 2+ articles on ML topics: technique explainers, paper reviews, tool comparisons',
      'Each article includes technical depth and a practical takeaway',
      'Articles have engagement from ML professionals',
    ],
    advice: {
      awareness: 'An ML blog proves you can communicate complex ideas clearly, a core skill for senior roles.',
      understanding: 'Hiring managers value engineers who can write clear technical documentation and design docs.',
      application: 'Write your first article: "Understanding [technique]: what it is and when to use it."',
      readiness: 'You have 2 articles that demonstrate technical and communication skills.',
      execution: 'Include diagrams and code snippets. Keep it under 900 words.',
      confidence: 'An ML blog turns your profile into a thought leadership platform.',
    },
    tasks: LINKEDIN_TASKS['ml-blog'] || [],
  },
  {
    id: 'certifications-display',
    skill: 'Certifications Display',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'DeepLearning.AI, AWS ML Specialty, or equivalent is listed in Licenses & Certifications',
      'Certifications include credential IDs and verification URLs',
      'You have completed LinkedIn Skills Assessments for Python and Machine Learning',
    ],
    advice: {
      awareness: 'ML certifications signal structured learning, especially valuable for career-changers.',
      understanding: 'DeepLearning.AI is foundational. AWS/GCP ML certs signal cloud deployment fluency.',
      application: 'Add all certifications with dates. Schedule your next one to show progression.',
      readiness: 'Your top 2-3 certifications are visible and verifiable.',
      execution: 'Add credential URLs. Request endorsements for Machine Learning, Python, and Deep Learning.',
      confidence: 'Certifications + endorsements = social proof of your ML competency.',
    },
    tasks: LINKEDIN_TASKS['certifications-display'] || [],
  },
];

// ─── EXPORTS ───────────────────────────────────────────────────────
export {
  APPLICATION_SKILL_NODES,
  INTERVIEW_SKILL_NODES,
  OFFER_PREPARATION_SKILL_NODES,
  OFFER_SKILL_NODES,
} from './skill_nodes_extended';

import {
  APPLICATION_SKILL_NODES,
  INTERVIEW_SKILL_NODES,
  OFFER_PREPARATION_SKILL_NODES,
  OFFER_SKILL_NODES,
} from './skill_nodes_extended';

export const ALL_SKILL_NODES: SkillNode[] = [
  ...RESUME_SKILL_NODES,
  ...LINKEDIN_SKILL_NODES,
  ...APPLICATION_SKILL_NODES,
  ...INTERVIEW_SKILL_NODES,
  ...OFFER_PREPARATION_SKILL_NODES,
  ...OFFER_SKILL_NODES,
];
