import type { SkillNode } from '@/core/skill_state';
import { RESUME_TASKS } from './tasks/resume';
import { LINKEDIN_TASKS } from './tasks/linkedin';
import { APPLICATION_TASKS } from './tasks/applications';
import { INTERVIEW_TASKS } from './tasks/interviews';
import { OFFER_TASKS } from './tasks/offer';

// ─── CHAPTER 1: RESUME (6 nodes) ──────────────────────────────────
export const RESUME_SKILL_NODES: SkillNode[] = [
  {
    id: 'positioning-clarity',
    skill: 'Positioning Clarity',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'You can describe your target AI/ML role in one clear sentence',
      'Your resume headline matches "ML Engineer", "AI Engineer", or "Research Scientist"',
      'Your stack includes Python, PyTorch/TensorFlow, and cloud ML platforms',
    ],
    advice: {
      awareness: 'An AI/ML resume without clear positioning looks like a generic software engineer. Define your niche: NLP, CV, MLOps, or Generative AI.',
      understanding: 'Recruiters scan for: framework expertise, model types deployed, dataset sizes handled, and business metrics improved.',
      application: 'Analyze 5 AI/ML job postings. Extract common requirements: PyTorch, LLMs, vector DBs, model serving, A/B testing.',
      readiness: 'You can state your target role, primary framework, and domain specialization in one sentence.',
      execution: 'Every resume section reinforces the same AI/ML positioning.',
      confidence: 'A focused AI/ML resume answers "Can this person ship models to production?" immediately.',
    },
    tasks: RESUME_TASKS['positioning-clarity'] || [],
  },
  {
    id: 'ml-skills-matrix',
    skill: 'ML Skills Matrix',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have rated your PyTorch/TensorFlow proficiency on a 1-5 scale',
      'You can list 3 model architectures you have implemented',
      'You have quantified at least one model performance metric you achieved',
    ],
    advice: {
      awareness: 'Listing "Python, ML, DL" is not enough. Recruiters want depth: which models, which datasets, which metrics?',
      understanding: 'A skills matrix shows progression: implemented → trained → optimized → deployed → monitored.',
      application: 'Create a table: Skill | Level | Last Used | Model/Dataset | Metric Achieved.',
      readiness: 'You can defend every skill rating with a specific model, dataset, and evaluation metric.',
      execution: 'Place the matrix prominently. AI hiring managers scan for framework names and model types first.',
      confidence: 'An honest skills matrix builds trust faster than inflated claims.',
    },
    tasks: RESUME_TASKS['ml-skills-matrix'] || [],
  },
  {
    id: 'resume-structure',
    skill: 'Resume Structure',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 25,
    difficulty: 1,
    signals: [
      'Your resume has a clear header with contact info, LinkedIn, GitHub, and Kaggle',
      'Experience bullets follow STAR method with ML metrics: accuracy, latency, throughput',
      'Projects section includes model cards and dataset descriptions',
    ],
    advice: {
      awareness: 'A poorly structured AI resume hides your Transformer experience behind irrelevant formatting.',
      understanding: 'AI recruiters scan for: frameworks, model architectures, dataset sizes, and deployment platforms.',
      application: 'Reformat one bullet: "Trained ResNet-50 on 100K images achieving 94% accuracy, deployed to AWS SageMaker with 200ms latency."',
      readiness: 'A recruiter can find your top framework and best model metric within 6 seconds.',
      execution: 'Use clean, single-column format. AI roles often use startup ATS and manual review.',
      confidence: 'Clean structure signals you can organize experiments and present results clearly.',
    },
    tasks: RESUME_TASKS['resume-structure'] || [],
  },
  {
    id: 'projects-portfolio',
    skill: 'Projects Portfolio',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 3,
    signals: [
      'You have 2-3 ML projects with public GitHub repos and READMEs',
      'Each project includes: problem statement, dataset, model architecture, results, deployment',
      'Projects use real or realistic datasets, not just MNIST or Iris',
    ],
    advice: {
      awareness: 'Without projects, junior AI/ML engineers have no proof they can train and deploy models.',
      understanding: 'A portfolio project is worth more than a certificate. It shows end-to-end ML thinking.',
      application: 'Pick one dataset you care about. EDA, feature engineering, model selection, hyperparameter tuning, deployment.',
      readiness: 'You can walk through your project in 3 minutes: problem, approach, model choice, metric, deployment.',
      execution: 'Host on GitHub with README. Include Colab/Kaggle links, model card, and live demo if possible.',
      confidence: 'Projects turn "I learned PyTorch" into "Here is the LLM fine-tuning pipeline I built."',
    },
    tasks: RESUME_TASKS['projects-portfolio'] || [],
  },
  {
    id: 'model-deployment-stories',
    skill: 'Model Deployment Stories',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 35,
    difficulty: 2,
    signals: [
      'Every experience bullet describes a model you deployed to production',
      'Stories follow: Problem → Model → Metric → Deployment → Business Impact',
      'You have quantified impact: latency reduction, cost savings, accuracy improvement',
    ],
    advice: {
      awareness: '"Built a model" is weak. "Deployed a BERT-based classifier reducing ticket routing time by 40%" is strong.',
      understanding: 'Deployment stories show: model selection, optimization, serving infrastructure, and business value.',
      application: 'Rewrite 3 bullets as deployment stories: what was the problem, what model, what metric, where deployed, what impact.',
      readiness: 'You can tell each story in 2 minutes with technical depth and business context.',
      execution: 'Use action verbs: trained, optimized, deployed, monitored, A/B tested.',
      confidence: 'Deployment stories prove you can bridge research and production.',
    },
    tasks: RESUME_TASKS['model-deployment-stories'] || [],
  },
  {
    id: 'resume-ats',
    skill: 'ATS Optimization',
    domain: 'Resume',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'Your resume has no tables, columns, or graphics that confuse ATS',
      'Keywords from AI/ML job postings appear naturally: PyTorch, TensorFlow, LLM, MLOps, vector DB',
      'File format is PDF with selectable text',
    ],
    advice: {
      awareness: 'A beautiful resume that ATS rejects is useless. Big tech and startups both use ATS.',
      understanding: 'ATS scans for: frameworks, model types, cloud platforms, and standard section headings.',
      application: 'Paste your resume into a plain text editor. Check for garbled text and correct order.',
      readiness: 'Your resume parses cleanly with all AI/ML keywords intact.',
      execution: 'Use standard headings: Skills, Experience, Projects, Education. No icons, no text boxes.',
      confidence: 'An ATS-optimized resume reaches AI recruiters and hiring managers consistently.',
    },
    tasks: RESUME_TASKS['resume-ats'] || [],
  },
];

// ─── CHAPTER 2: LINKEDIN (6 nodes) ──────────────────────────────────
export const LINKEDIN_SKILL_NODES: SkillNode[] = [
  {
    id: 'headline-authority',
    skill: 'Headline Authority',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 15,
    difficulty: 1,
    signals: [
      'Your headline says "ML Engineer" or "AI Engineer" not "Data Scientist" or "Software Developer"',
      'Headline includes a specific domain: NLP, Computer Vision, Generative AI, MLOps',
      'You have a clear value proposition in 120 characters',
    ],
    advice: {
      awareness: 'A weak headline makes you invisible to AI recruiters searching for "LLM Engineer" or "PyTorch Developer".',
      understanding: 'LinkedIn search weights headline heavily. AI keywords matter more than creativity.',
      application: 'Write 5 headline variants. Test them with an AI recruiter or career coach.',
      readiness: 'Your headline contains: role, domain, and one framework or model type.',
      execution: 'Update headline. Remove "seeking", "open to work". Add "PyTorch" or "LLMs" if applicable.',
      confidence: 'A strong headline attracts inbound recruiter messages for AI roles.',
    },
    tasks: LINKEDIN_TASKS['headline-authority'] || [],
  },
  {
    id: 'about-section',
    skill: 'About Section',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 25,
    difficulty: 2,
    signals: [
      'Your About tells an AI career story, not just lists frameworks',
      'It includes a specific model you built and the business problem it solved',
      'It ends with a clear call to action and research interests',
    ],
    advice: {
      awareness: 'A blank About section wastes prime LinkedIn real estate. AI recruiters read it for research depth.',
      understanding: 'The About section is your narrative: who you are, what models you build, what problems you solve.',
      application: 'Write 200 words: background, key model/deployment, research interests, what you are looking for.',
      readiness: 'A stranger understands your AI specialty after reading your About.',
      execution: 'Use first person. Include one model metric. End with "Open to ML Engineer roles in NLP/GenAI".',
      confidence: 'A compelling About turns profile views into connection requests from AI leads.',
    },
    tasks: LINKEDIN_TASKS['about-section'] || [],
  },
  {
    id: 'network-connections',
    skill: 'Network Connections',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'You have 500+ connections including AI researchers, ML engineers, and hiring managers',
      'You engage weekly with AI content: papers, model releases, conference talks',
      'You have joined 3+ AI/ML LinkedIn groups or communities',
    ],
    advice: {
      awareness: 'A small network limits your visibility to AI opportunities. Most AI roles are filled through referrals.',
      understanding: 'AI hiring is relationship-driven. Conference connections, paper co-authors, and open-source collaborators matter.',
      application: 'Connect with 10 AI professionals weekly. Comment thoughtfully on their posts about models and papers.',
      readiness: 'Your network includes people at your target companies who know your work.',
      execution: 'Share your Kaggle solutions, paper summaries, or model fine-tuning experiments weekly.',
      confidence: 'An active AI network brings opportunities before they are posted publicly.',
    },
    tasks: LINKEDIN_TASKS['network-connections'] || [],
  },
  {
    id: 'kaggle-showcase',
    skill: 'Kaggle Showcase',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 40,
    difficulty: 2,
    signals: [
      'Your Featured section includes 2+ Kaggle competitions with rankings',
      'Each competition has a write-up explaining your approach and model choice',
      'You have linked your Kaggle profile and top notebooks',
    ],
    advice: {
      awareness: 'Kaggle medals are credible proof of ML skill. They validate you can compete with top practitioners.',
      understanding: 'Recruiters value Kaggle because it shows: feature engineering, model tuning, and leaderboard pressure.',
      application: 'Add 2 competitions to Featured. Write 100 words on approach, model, and lesson learned for each.',
      readiness: 'Your Kaggle profile is public and includes notebooks with clear explanations.',
      execution: 'Pin your best competition and most-downloaded dataset or notebook.',
      confidence: 'Kaggle showcase proves you can build models that perform under competitive evaluation.',
    },
    tasks: LINKEDIN_TASKS['kaggle-showcase'] || [],
  },
  {
    id: 'research-publications',
    skill: 'Research Publications',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 35,
    difficulty: 3,
    signals: [
      'Your Featured section includes papers, preprints, or technical blog posts',
      'Each publication has a 2-sentence summary for non-experts',
      'You have linked arXiv, Medium, or company engineering blog',
    ],
    advice: {
      awareness: 'Publications signal research depth. Even blog posts about model implementations show expertise.',
      understanding: 'AI recruiters look for: paper quality, reproducibility, and ability to communicate complex ideas.',
      application: 'Add 1 paper or 2 blog posts to Featured. Write layman summaries for each.',
      readiness: 'A non-technical recruiter can understand your contribution from the summary.',
      execution: 'Link to GitHub repos that reproduce paper results. Show code, not just claims.',
      confidence: 'Research publications differentiate you from engineers who only use APIs.',
    },
    tasks: LINKEDIN_TASKS['research-publications'] || [],
  },
  {
    id: 'certifications-display',
    skill: 'Certifications Display',
    domain: 'LinkedIn',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 20,
    difficulty: 1,
    signals: [
      'Your Licenses section includes AWS ML Specialty, TensorFlow Developer, or equivalent',
      'Each certification is linked to the verifying organization',
      'You have added skill badges for PyTorch, Keras, and cloud ML platforms',
    ],
    advice: {
      awareness: 'Certifications validate structured learning. They help non-technical recruiters assess your stack.',
      understanding: 'AWS ML Specialty and TensorFlow Developer are most recognized in industry AI roles.',
      application: 'Add all relevant certifications. Link to credential IDs. Add skill assessments for frameworks.',
      readiness: 'Your certifications match the requirements in your target job postings.',
      execution: 'Prioritize cloud ML and framework certs over generic "Data Science" certificates.',
      confidence: 'Certifications provide credibility when you lack years of production ML experience.',
    },
    tasks: LINKEDIN_TASKS['certifications-display'] || [],
  },
];

// ─── CHAPTER 3: APPLICATIONS (7 nodes) ──────────────────────────────
export const APPLICATION_SKILL_NODES: SkillNode[] = [
  {
    id: 'application-tracking',
    skill: 'Application Tracking',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have a spreadsheet tracking 20+ AI/ML job applications',
      'Each entry includes: company, team, model type, date, status',
      'You follow up on 50% of applications within 1 week',
    ],
    advice: {
      awareness: 'Applying blindly to AI roles is inefficient. Tracking reveals which companies value your specialty.',
      understanding: 'A tracker shows patterns: which teams respond, which model types are in demand, which channels work.',
      application: 'Create a tracker with columns: Company, Team, Role, Model Type, Date Applied, Status, Follow-up, Notes.',
      readiness: 'You can see your pipeline: applied, phone screen, ML take-home, onsite, offer.',
      execution: 'Set weekly review. Archive rejected roles. Prioritize teams building models you know.',
      confidence: 'A tracked pipeline turns chaos into an AI job search strategy.',
    },
    tasks: APPLICATION_TASKS['application-tracking'] || [],
  },
  {
    id: 'portfolio-github',
    skill: 'GitHub Portfolio',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 2,
    signals: [
      'Your GitHub has 3+ pinned ML repos with clear READMEs',
      'Each repo includes: problem, dataset, model, metric, deployment',
      'You have 100+ commits showing consistent coding activity',
    ],
    advice: {
      awareness: 'A sparse GitHub profile hurts AI applications. Recruiters check your code quality and project depth.',
      understanding: 'GitHub is your portfolio. It shows: code style, documentation habits, and project complexity.',
      application: 'Pin 3 best repos. Add README with architecture diagram, model card, and running instructions.',
      readiness: 'A stranger can clone, run, and understand your project in 10 minutes.',
      execution: 'Include requirements.txt, Dockerfile, and demo notebook. Show you think about reproducibility.',
      confidence: 'A strong GitHub turns "I know PyTorch" into "Here is my production-ready model repo."',
    },
    tasks: APPLICATION_TASKS['portfolio-github'] || [],
  },
  {
    id: 'ml-competition-scores',
    skill: 'ML Competition Scores',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have Kaggle, DrivenData, or AI Challenge rankings in top 20%',
      'Each competition has a write-up on your approach and model architecture',
      'You can explain your solution in an interview with technical depth',
    ],
    advice: {
      awareness: 'Competition rankings prove you can optimize models under pressure. They are credible interview talking points.',
      understanding: 'Recruiters value competitions because they show: feature creativity, ensemble strategies, and metric focus.',
      application: 'Document 2 competitions with: problem, EDA, model, ensemble, final rank, lesson learned.',
      readiness: 'You can explain your solution in 5 minutes with code snippets and visualizations.',
      execution: 'Include competition write-ups in your application. Link to repos with full code.',
      confidence: 'Competition scores validate your ability to beat baseline models systematically.',
    },
    tasks: APPLICATION_TASKS['ml-competition-scores'] || [],
  },
  {
    id: 'company-research',
    skill: 'Company Research',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 35,
    difficulty: 1,
    signals: [
      'You know the AI team structure at your target companies',
      'You can name their models, papers, or products using ML',
      'You have identified 2-3 teams that match your specialty',
    ],
    advice: {
      awareness: 'Generic AI applications fail. Teams want candidates who understand their model challenges.',
      understanding: 'Research reveals: model types, infrastructure, team size, and research vs product balance.',
      application: 'Read company engineering blogs. Find their ML papers. Check LinkedIn for team members.',
      readiness: 'You can ask informed questions about their model serving infrastructure or training pipelines.',
      execution: 'Tailor your cover letter to their specific ML challenges, not generic "AI is exciting".',
      confidence: 'Informed applications show you can research and adapt, key skills for ML roles.',
    },
    tasks: APPLICATION_TASKS['company-research'] || [],
  },
  {
    id: 'application-tailoring',
    skill: 'Application Tailoring',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 25,
    difficulty: 2,
    signals: [
      'Every resume you send highlights skills matching the job description',
      'Your cover letter mentions their models, infrastructure, or papers',
      'You have customized your project portfolio for the role type',
    ],
    advice: {
      awareness: 'A generic AI application is a rejection. Teams receive hundreds of "I love AI" resumes.',
      understanding: 'Tailoring shows: you read the job post, you understand their stack, you have relevant experience.',
      application: 'Match 3 skills from the job description to your projects. Rewrite bullets to use their keywords.',
      readiness: 'Every application has a clear link between their requirements and your proven skills.',
      execution: 'Spend 15 minutes per application. It is better than 50 generic applications.',
      confidence: 'Tailored applications get 3x more responses in competitive AI hiring.',
    },
    tasks: APPLICATION_TASKS['application-tailoring'] || [],
  },
  {
    id: 'referral-strategy',
    skill: 'Referral Strategy',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 40,
    difficulty: 2,
    signals: [
      'You have identified 2-3 potential referrers at each target company',
      'Your outreach message is specific about their work and your interest',
      'You have offered value first: feedback, code review, or paper summary',
    ],
    advice: {
      awareness: 'Referrals bypass ATS and get priority review. In AI, they often come from paper co-authors or open-source.',
      understanding: 'Good referrers are: former colleagues, conference connections, open-source collaborators, Kaggle teammates.',
      application: 'Find team members on LinkedIn. Engage with their posts. Ask for a 15-minute chat about their models.',
      readiness: 'Your referrer knows your work and can speak to your ML abilities specifically.',
      execution: 'Do not ask for a referral in the first message. Build relationship first, ask after 2-3 interactions.',
      confidence: 'A warm referral from an ML engineer is the strongest signal to hiring managers.',
    },
    tasks: APPLICATION_TASKS['referral-strategy'] || [],
  },
  {
    id: 'open-source-contributions',
    skill: 'Open Source Contributions',
    domain: 'Applications',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 50,
    difficulty: 3,
    signals: [
      'You have 3+ merged PRs in ML libraries: HuggingFace, scikit-learn, PyTorch',
      'Each PR has a clear issue description and test coverage',
      'You can explain the technical problem and your solution in an interview',
    ],
    advice: {
      awareness: 'Open-source contributions prove you can read complex ML code and collaborate with researchers.',
      understanding: 'Recruiters value OSS because it shows: code review skills, testing habits, and community engagement.',
      application: 'Find 3 good-first-issues in HuggingFace or PyTorch. Submit PRs with tests and documentation.',
      readiness: 'You can explain your PR in 3 minutes: problem, approach, trade-offs, and review feedback.',
      execution: 'Document contributions on your resume and LinkedIn. Link to PRs with line counts.',
      confidence: 'OSS contributions signal you are part of the ML community, not just a consumer of APIs.',
    },
    tasks: APPLICATION_TASKS['open-source-contributions'] || [],
  },
];

// ─── CHAPTER 4: INTERVIEWS (10 nodes) ─────────────────────────────
export const INTERVIEW_SKILL_NODES: SkillNode[] = [
  {
    id: 'interview-prep',
    skill: 'Interview Prep',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 1,
    signals: [
      'You have a checklist of ML interview topics: linear algebra, probability, optimization, architectures',
      'You have scheduled 3 mock interviews with AI engineers or researchers',
      'You have collected 20+ real AI/ML interview questions from Glassdoor and LeetCode',
    ],
    advice: {
      awareness: 'Walking into an AI interview unprepared is a waste of opportunity. ML interviews are deep and broad.',
      understanding: 'AI interviews cover: math fundamentals, model architectures, coding, system design, and MLOps.',
      application: 'Create a study plan: 2 weeks math, 2 weeks models, 2 weeks coding, 1 week system design.',
      readiness: 'You can explain backpropagation, attention mechanisms, and gradient descent without notes.',
      execution: 'Use Anki for flashcards. Practice coding on paper for onsite rounds.',
      confidence: 'Thorough preparation turns interview anxiety into structured performance.',
    },
    tasks: INTERVIEW_TASKS['interview-prep'] || [],
  },
  {
    id: 'ml-theory-deep-dive',
    skill: 'ML Theory Deep Dive',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 60,
    difficulty: 3,
    signals: [
      'You can derive gradient descent from first principles',
      'You can explain attention mechanisms with mathematical notation',
      'You can compare 5 model architectures and their inductive biases',
    ],
    advice: {
      awareness: 'AI interviews test depth. "I used BERT" is not enough. "Here is why self-attention works" is.',
      understanding: 'Theory questions: optimization landscapes, generalization bounds, bias-variance tradeoff, information theory.',
      application: 'Study ISL, ESL, and DL Goodfellow. Practice deriving key equations on paper.',
      readiness: 'You can whiteboard: backprop, attention, CNN filters, RNN vanishing gradients, VAE ELBO.',
      execution: 'For every model you claim, know: objective function, optimization, regularization, and failure modes.',
      confidence: 'Deep theory knowledge differentiates ML engineers from framework users.',
    },
    tasks: INTERVIEW_TASKS['ml-theory-deep-dive'] || [],
  },
  {
    id: 'coding-ml-pipelines',
    skill: 'Coding ML Pipelines',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 45,
    difficulty: 2,
    signals: [
      'You can implement a training loop from scratch in PyTorch',
      'You can write data loading, augmentation, and batching code',
      'You can debug shape mismatches and CUDA errors quickly',
    ],
    advice: {
      awareness: 'AI coding interviews are not LeetCode. They are data pipelines, model definitions, and training loops.',
      understanding: 'Expect: implement ResNet block, write custom loss, debug NaN gradients, optimize DataLoader.',
      application: 'Practice on LeetCode "ML" tagged problems. Implement papers from scratch without copy-paste.',
      readiness: 'You can write a full training script: data loading, model, loss, optimizer, loop, evaluation, save.',
      execution: 'Use clean code: type hints, docstrings, config files. Show you think about maintainability.',
      confidence: 'Clean ML code signals you can join a team and contribute to their codebase immediately.',
    },
    tasks: INTERVIEW_TASKS['coding-ml-pipelines'] || [],
  },
  {
    id: 'system-design-ml',
    skill: 'ML System Design',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 50,
    difficulty: 3,
    signals: [
      'You can design a recommendation system from data to serving',
      'You can discuss tradeoffs: batch vs real-time, accuracy vs latency, model size vs throughput',
      'You can draw architecture diagrams with data flows and component responsibilities',
    ],
    advice: {
      awareness: 'Senior AI roles require system design. "I trained a model" is not enough. "I designed the pipeline" is.',
      understanding: 'System design covers: data ingestion, feature store, training infrastructure, model registry, serving, monitoring.',
      application: 'Study ML system design cases: Netflix recommendations, Uber ETA, Google search ranking.',
      readiness: 'You can whiteboard a full pipeline: data source → feature engineering → training → deployment → monitoring.',
      execution: 'Discuss tradeoffs: online vs offline features, model staleness, A/B testing infrastructure, rollback.',
      confidence: 'System design interviews separate ML engineers from model trainers.',
    },
    tasks: INTERVIEW_TASKS['system-design-ml'] || [],
  },
  {
    id: 'mlops-cicd',
    skill: 'MLOps & CI/CD',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 40,
    difficulty: 3,
    signals: [
      'You can explain model versioning, A/B testing, and rollback strategies',
      'You have used MLflow, Weights & Biases, or Kubeflow for experiment tracking',
      'You can design a CI/CD pipeline for model training and deployment',
    ],
    advice: {
      awareness: 'Modern AI roles require MLOps. Training a model is 10% of the job. Deploying and monitoring is 90%.',
      understanding: 'MLOps questions: experiment tracking, model registry, feature stores, monitoring, retraining triggers.',
      application: 'Set up MLflow or W&B for a personal project. Practice versioning datasets and models.',
      readiness: 'You can explain: how to detect model drift, how to rollback, how to automate retraining.',
      execution: 'Mention specific tools: Docker, Kubernetes, Airflow, Feast, Evidently. Not just "I know MLOps".',
      confidence: 'MLOps knowledge proves you can own the full model lifecycle, not just the notebook.',
    },
    tasks: INTERVIEW_TASKS['mlops-cicd'] || [],
  },
  {
    id: 'model-evaluation',
    skill: 'Model Evaluation',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 35,
    difficulty: 2,
    signals: [
      'You can choose the right metric for imbalanced data, ranking, and generation tasks',
      'You can explain ROC-AUC, log-loss, BLEU, and perplexity with formulas',
      'You can design evaluation protocols: cross-validation, holdout, temporal splits',
    ],
    advice: {
      awareness: 'Wrong metrics lead to wrong models. AI interviews test whether you understand evaluation deeply.',
      understanding: 'Evaluation questions: when to use precision vs recall, how to handle class imbalance, offline vs online metrics.',
      application: 'Practice: design evaluation for fraud detection, recommendation, and text generation.',
      readiness: 'You can defend your metric choice with business context and statistical reasoning.',
      execution: 'Discuss: statistical significance, confidence intervals, and sample size requirements.',
      confidence: 'Strong evaluation skills prevent shipping models that fail in production.',
    },
    tasks: INTERVIEW_TASKS['model-evaluation'] || [],
  },
  {
    id: 'behavioral-ml-scenarios',
    skill: 'Behavioral ML Scenarios',
    domain: 'Interviews',
    state: 'locked',
    nextState: 'awareness',
    estimatedMinutes: 30,
    difficulty: 2,
    signals: [
      'You have 5 STAR stories about ML projects: challenges, failures, team conflicts',
      'You can discuss ethical considerations: bias, fairness, privacy in your models',
      'You can explain how you prioritize experiments and handle negative results',
    ],
    advice: {
      awareness: 'Behavioral interviews in AI are rigorous. They test collaboration, ethics, and scientific mindset.',
      understanding: 'Expect: "Tell me about a failed experiment", "How do you handle model bias?", "Describe a team conflict over approach."',
      application: 'Prepare 5 STAR stories: success, failure, conflict, ethical dilemma, learning moment.',
      readiness: 'Each story has clear situation, task, action, result, and reflection.',
      execution: 'Be honest about failures. AI teams value learning from negative results.',
      confidence: 'Strong behavioral answers show you can thrive in research-driven, uncertain environments.',
    },
    tasks: INTERVIEW_TASKS['